### ISSUE TITLE
provision/docker: use `docker exec` instead of sshd for `tsuru-admin ssh`

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#1002]
This issue continues the work started on #993. It will allow us to completely remove private key handling from tsuru server.

**Comment by tarsisazevedo** [comment]
done with tsuru/tsuru@00dc2c8e45af81f83ce3f1b3896a9236eb9fb224

**Comment by fsouza** [comment]
![137](https://cloud.githubusercontent.com/assets/108725/5674243/477e36f2-978e-11e4-92fc-08f0633f2e61.gif)
