### ISSUE TITLE
Bound plans to pools

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#1011]
Actually, a plan can't be bound to a pool, thus is not possible to make different service plan based on docker nodes.

For example, a service plan made with docker nodes with SSD storage and a service plan made with SATA nodes.

One solutions could be bind plan to pools, for example: ssd_pool made with docker nodes 1,2,3 and sata_pool made with docker 4,5,6.
Plan 'production' bound to ssd_pool
Plan 'testing' bound to sata_pool

any app created with `-p testing` would be deployed on docker 4, 5 or 6 and apps created with production plan, would be deployed on docker 1, 2 or 3.

**Comment by tarsisazevedo** [comment]
Can we close it @guestisp?

**Comment by fsouza** [comment]
Since we took a different path, I'm closing this issue.
