### ISSUE TITLE
App migration between pools

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#1013]
Based on #1011 and #1012 an app should be migrated across pool.
Let's assume an app created on `sata_pool`, we should be able to migrate it over a different pool, for example, an ssd pool:

`tsuru app-migrade oldpool newpool`

Differences between migration and cloning:

Clone: a new app, with a new name, is created based on the old app. All is preserved (storage, file, team, users, and so on)

Migration: like cloning, but with the same name preserved and the old app is automatically destroyed when migration is done.

**Comment by tarsisazevedo** [comment]
Done in tsuru/tsuru-client@23d65cc33af445d8670b656c7497852970a0050e and tsuru/tsuru@9ff7dac3810891538cfdede59db82a5c4e1b54ab
