### ISSUE TITLE
Full deploy log

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#1021]
are there any full deploy log feature in Tsuru?
Look at this: http://viaduct.io/features at the bottom of the page, there is a sample using CLI:
```
Deploying... You can view the full log at :
https://my.viaduct.io/applications/qoffee/deployments/25
```

Any feature like this in tsuru? If missing, could be a cool feature to add (but using UUID and not sequential ID like the sample above)

**Comment by fsouza** [comment]
The full log deployment is now available in the dashboard.
