### ISSUE TITLE
tsr should warn about inability to contact gandalf on startup

### ISSUE THREAD

**Issue by msabramo** [tsuru/tsuru#1042]
And maybe mongo and redis too. 

If I am correct then tsr is pretty limited without these other things. 

For example I got tsr running on my Mac but I can't do `user-create` without gandalf.

I would make it a warning and not a fatal error because I'm developing and I was able to get useful development work done without gandalf. I will need to set up gandalf now to get further but it was nifty that I didn't need it to start the server and poke at it. 

I figure folks who administer tsuru might want to find out right away if they're missing a key piece. 

I guess another way to handle this is to make any missing infrastructure in the config file a fatal error but then allow developers to invoke tsr with a special `--dev` option that eliminates the hard requirement of having gandalf, tsuru, redis, or perhaps even a config file. IIRC, I had to create a `/etc/tsuru/tsuru.conf` to get tsuru to start. It might be nice to relax this when developing. 

Comments welcome. And I might take a stab at whatever is decided.

**Comment by fsouza** [comment]
This issue is now pretty straightforward, something like:

```
import "github.com/tsuru/hc"

func main() {
    ...
    fmt.Println("Checking the status of components:")
    results = hc.Check()
    // loop through results printing status, failing if result.Status is not equal to hc.HealthCheckOK
    ...
}
```

Here's how the healthcheck handler works: https://github.com/tsuru/tsuru/blob/9a921e4fa5876d0ffef218b50b61af9d11233fba/api/healthcheck.go#L23.

@msabramo do you wanna work on it? Thank you!
