### ISSUE TITLE
Create a tsuru screencast

### ISSUE THREAD

**Issue by msabramo** [tsuru/tsuru#1043]
I'm trying to advocate for using tsuru at my company and I think one of the obstacles is that people don't quite understand or remember what it does even after I explain it. I was thinking of creating a screencast to illustrate. I think that will help a lot of people to better appreciate what it does. Wanted to make sure there is not one already floating around somewhere before I embark on this. 

Obviously it would be desirable to either have screencasts with narration in multiple languages (Portuguese and English being obvious first candidates) or just try to have one with just typing and no narration, which might be self-explanatory and understandable to a wide variety of people. 

The simplest would be a very simple and short one that shows someone typing `git push tsuru master` and then a deploy happens and a web site becomes available.

**Comment by andrestc** [comment]
Closing to keep just #630 to track this.
