### ISSUE TITLE
Travis CI tests failing intermittently

### ISSUE THREAD

**Issue by msabramo** [tsuru/tsuru#1045]
Most pull requests fail in either the Go 1.4 or Go tip sub job, but there is no obvious pattern, so I am guessing that the tests fail intermittently. Haven't looked in detail though.

**Comment by andrewsmedina** [comment]
It looks like some problem with Travis CI + MongoDB. In drone.io we don't have this problem: https://drone.io/github.com/tsuru/tsuru

**Comment by msabramo** [comment]
Some ideas at https://github.com/travis-ci/travis-ci/issues/3075#issuecomment-68629130

Try adding `sudo dmesg` to `after_failure` to see if OOMs are happening.

**Comment by cezarsa** [comment]
Good call @msabramo. It's definitely related to OOMs as we can see in https://travis-ci.org/tsuru/tsuru/jobs/46092093#L2702
```
[10314713.731361] Out of memory in UB 197947879: OOM killed process 1852 (mongod) score 0 vm:3174284kB, rss:70808kB, swap:2168kB
[10314821.568655] Out of memory in UB 197947879: OOM killed process 8832 (mysqld) score 0 vm:908892kB, rss:107020kB, swap:0kB
[10314821.635923] Out of memory in UB 197947879: OOM killed process 9137 (sh) score 0 vm:4348kB, rss:672kB, swap:0kB
[10314821.636752] Out of memory in UB 197947879: OOM killed process 9141 (sleep) score 0 vm:4252kB, rss:528kB, swap:0kB
``` 
However I'm not sure about how to solve this. We could try killing some processes before starting the tests. We don't need mysqld running. Also setting GOMAXPROCS=1 might help.

**Comment by msabramo** [comment]
There are a few ideas for solving OOM failures over at https://github.com/travis-ci/travis-ci/issues/3075#issuecomment-68629130

I wonder if we can add a `ps` or `top` that sorts by memory to see what processes are using the most memory.

**Comment by msabramo** [comment]
Maybe something like this?

```
vagrant@vagrant-ubuntu-trusty-64:~$ top -b -n 1 -o RES | head -n 15
top - 05:59:04 up 6 min,  1 user,  load average: 0.01, 0.18, 0.13
Tasks: 103 total,   1 running, 102 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.1 us,  1.8 sy,  0.3 ni, 94.5 id,  0.2 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem:   1017856 total,   572344 used,   445512 free,    27980 buffers
KiB Swap:        0 total,        0 used,        0 free.   234176 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 1093 zookeep+  20   0 1355588  39936  11944 S  0.0  3.9   0:01.53 java
 1605 root      20   0  112688  34532   1092 S  0.0  3.4   0:00.00 ruby
 1454 root      20   0  182348  34432   2724 S  0.0  3.4   0:01.67 puppet
 1287 root      20   0  966408  25200   5872 S  0.0  2.5   0:00.30 nodejs
 1271 root      20   0  966408  25192   5872 S  0.0  2.5   0:00.30 nodejs
 1281 root      20   0  966408  25140   5872 S  0.0  2.5   0:00.31 nodejs
 1292 root      20   0  966408  25128   5872 S  0.0  2.5   0:00.30 nodejs
 1029 root      20   0  966408  23620   5840 S  0.0  2.3   0:00.36 node
```

**Comment by msabramo** [comment]
Added the `top` command above in https://github.com/tsuru/tsuru/pull/1060

**Comment by msabramo** [comment]
From looking at the last Travis CI job, it looks like maybe the tests are just putting too much data into MongoDB?

```
$ mongostat -n 1
connected to: 127.0.0.1
insert  query update delete getmore command flushes mapped  vsize    res faults                   locked db idx miss %     qr|qw   ar|aw  netIn netOut  conn       time 
    *0     *0     *0     *0       0     1|0       0  2.58g  5.38g    24m      0 tsuru_api_handler_test:0.0%          0       0|0     0|0    62b     9k     1   19:03:28 
Done. Your build exited with 1.
```

**Comment by fsouza** [comment]
We haven't see many failues in travis recently, maybe it was a temporary issue with MongoDB?

It started happening suddenly, and then stopped happening suddenly. @msabramo what do you think?

**Comment by msabramo** [comment]
@cezarsa did a few tweaks I think that might've fixed it. E.g.:

- https://github.com/tsuru/tsuru/commit/9e79730b23576a21907f96df22f95f478cfc4046
- https://github.com/tsuru/tsuru/commit/63c56db8837e53413e635592693aa307b70e1046

**Comment by dcarley** [comment]
It looks like this is back:

- Go 1.5: https://travis-ci.org/tsuru/tsuru/jobs/76511670
- Go tip: https://travis-ci.org/tsuru/tsuru/jobs/76511671

It makes it hard to external contributors to tell whether the project is stable and whether their pull requests are working. Can you re-open this issue?

**Comment by fsouza** [comment]
@dcarley sure! Seems to be OOM errors again. I'm thinking about creating a fork or a branch for further investigation.

**Comment by fsouza** [comment]
@dnsaoki2 has just fixed it via cf3a571ad08c92f129e175c68d0f2ba2a9b07738.

@dcarley thanks for raising it again1

**Comment by dcarley** [comment]
Thanks, both!

**Comment by cezarsa** [comment]
I broke it again yesterday. Looks like another flaky test that doesn't
break locally. I couldn't debug it long enough but at least it's happening
across all CIs, I'll fix it today.
