### ISSUE TITLE
Question: is tsuru using logrus?

### ISSUE THREAD

**Issue by msabramo** [tsuru/tsuru#1053]
I was just looking at this package the other day as it looked like a pretty nice and powerful logging package.

I noticed that it shows up in `Godeps/Godeps.json`, but nowhere else.

```
[marca@marca-mac2 tsuru]$ ag logrus
Godeps/Godeps.json
14:			"ImportPath": "github.com/Sirupsen/logrus",
```

**Comment by andrewsmedina** [comment]
tsuru does not use logrus.

**Comment by msabramo** [comment]
Oh maybe this means that something else that tsuru is using is using logrus?

**Comment by cezarsa** [comment]
basically: tsuru/tsuru -> fsouza/go-dockerclient -> docker/docker -> logrus

**Comment by msabramo** [comment]
Ah, interesting. Thanks!

I wonder if you guys are open to using logrus in tsuru? I read a little about it and it seemed like it had some neat features over the golang stdlib logger like coloring and such.
