### ISSUE TITLE
ec2 ebs optimized

### ISSUE THREAD

**Issue by jblancett** [tsuru/tsuru#1058]
I would like the ec2 instances tsuru creates to be ebs optimized.  This could be done with a simple addition like so:
https://github.com/jblancett/tsuru/commit/b6b653eadc13d887f79c2679493e0534de78c3fd
However, I'd think it would be better to be added as a tsr config option or a param that can be passed maybe in the machine template?  I'm just not well versed enough in Go to make this happen at the moment

**Comment by cezarsa** [comment]
Waiting for go-amz/amz#3 being merged. We'll also need to switch from go-amz v1 branch to v2 (or v2-dev) branch.

**Comment by jblancett** [comment]
@cezarsa looks like its been merged now :)

**Comment by jblancett** [comment]
https://aws.amazon.com/blogs/aws/now-available-new-c4-instances/
With these brand new instance types, ebs-optimized is automatically selected

**Comment by fsouza** [comment]
Seems like they didn't include EBSOptimized option in the RunInstances type. I've just opened go-amz/amz#23.

**Comment by jblancett** [comment]
this is great news! thanks :)
