### ISSUE TITLE
If tsuru support multi locations?

### ISSUE THREAD

**Issue by kinosang** [tsuru/tsuru#1063]
Just use one tsuru-server-api to manage multi hipache(s) and docker nodes like

```
Server 1
Tsuru-server-api
Docker registry

Server A on Location 1
Hipache
Database

Docker Server for Server A on Location 1

Server B on Location 2
Hipache
Database

Docker Server for Server B on Location 2
```

Then user can choose create their app in which location.

I think it's a useful function. But I'm not good in  Golang...

**Comment by jonaskac** [comment]
:+1: 

Would be awesome if the load balancer, whatever one you use, could be updated via Tsuru.

**Comment by kinosang** [comment]
@jonaskac It's still an assumption. I'll try to do it after I get start with Golang.

**Comment by cezarsa** [comment]
As soon as 0.10.0 is released it will be possible to have two separate hipache routers in each location, the router will be part of the plan chosen when creating an application. You'll be able to have multiple hipache configurations in tsuru.conf. (I'll add documentation for this feature early next week)

This way something like this would be possible:
```
Server 1
Tsuru-server-api
Docker registry
Database (mongodb)

Server A on Location 1
Hipache 1
Redis 1

Docker Server for Server A on Location 1

Server B on Location 2
Hipache 2
Redis 2

Docker Server for Server B on Location 2
```

In tsuru.conf you would have:
```
routers:
  hipache1:
    type: hipache
    redis-server: redis1
  hipache2:
    type: hipache
    redis-server: redis2
```

Note that this still assumes that you have a single mongodb database, which of course could still use replica sets for HA.

**Comment by kinosang** [comment]
@cezarsa That sounds good.

**Comment by jblancett** [comment]
The multiple hipaches is already possible by using redis slaves.  Tsuru only needs to write to the redis master.

**Comment by kinosang** [comment]
@jblancett Oh, just forgot it. But I think it's better to manage location with `tsuru-admin`.

**Comment by jblancett** [comment]
I believe its better to not have to specify all your routers in tsuru.conf.
Tsuru only needs to write to the primary redis, which is then distributed to the slaves via pubsub
This means you can scale out the routers independently of tsuru and tsuru doesn't even have to be aware of where they are.
to put it simply, pubsub > push
I really hope tsuru doesn't move away from this possibility by making you specify all of your routers

**Comment by kinosang** [comment]
@jblancett Ok, you are right. I'll try to build my own user panel to manage all of my routers instead of make change on tsuru.

**Comment by kinosang** [comment]
@jonaskac @cezarsa @jblancett Okay, all guys, I think the function I need might not be a part of tsuru, it's more like a function of a user panel. I'm writing a panel to control tsuru, docker registry and routers. Images can be transfer between locations by user, load balance is optional, and it doesn't need to make changes on tsuru and docker.

It will look like:
```
Main Server: my panel

Location 1 (might have multi server):
Tsuru-server-api
Docker registry
mongodb
Hipache
Redis
Docker
some other things

Location n: ...
```

**Comment by cezarsa** [comment]
@jblancett That's not what the change I described is about. We'll keep supporting hipache with redis master/slave configuration the same way it works today, and you'll never have to declare redis slave servers in tsuru.conf.

The new `routers:` config key was created for supporting multiple routers configurations. As a side effect, this allow us to have multiple routers of the same kind, and that's the scenario I tried to describe.

Having multiple completely independent hipache routers would not be a common configuration, but it could be useful if you want routers in geographically separated regions. Master/Slave replication would be quite expensive in this case, and that's where having multiple routers could be useful. In each entry inside the `routers:` key you have to declare only which is the master redis server for that router.

**Comment by jblancett** [comment]
@cezarsa I understand now thanks for clearing that up!  Sounds like a good plan :+1:

**Comment by jblancett** [comment]
@kinosang have you seen the tsuru-dashboard? Maybe you can expand upon it to do what you want.
https://github.com/tsuru/tsuru-dashboard

**Comment by kinosang** [comment]
@jblancett Yep, already got it.
