### ISSUE TITLE
Dockers dependent on Tsuru running

### ISSUE THREAD

**Issue by jonaskac** [tsuru/tsuru#1072]
I'm sometimes having issues that all services stops working e.g. when the tsuru servers reboots.

This is the output:

```
Traceback (most recent call last):
  File "/usr/local/bin/tsuru_unit_agent", line 9, in <module>
    load_entry_point('tsuru-unit-agent==0.3.4', 'console_scripts', 'tsuru_unit_agent')()
  File "/usr/local/lib/python2.7/dist-packages/tsuru_unit_agent/main.py", line 50, in main
    actions[args.action](args)
  File "/usr/local/lib/python2.7/dist-packages/tsuru_unit_agent/main.py", line 10, in run_action
    envs = client.register_unit(args.app_name)
  File "/usr/local/lib/python2.7/dist-packages/tsuru_unit_agent/client.py", line 19, in register_unit
    **params)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tsuru.tuzame.com', port=8080): Max retries exceeded with url: /apps/*****/units/register (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
```

This means that the application stops working, and this is really bad. Is there any thoughts on this? I thought that the unit-agent was removed, or am I missing something?

**Comment by cezarsa** [comment]
tsuru-unit-agent hasn't been removed, and it probably won't. However, errors registering the unit could be ignored when starting an existing container. I'll take a look at it.

**Comment by jonaskac** [comment]
@cezarsa thanks man, they ar stopping my units from starting. The point is that tsuru is only going to be provisioning dockers right? The agent is obsolete?

My point is that if the tsuru server stops working for some reason, the dockers and load balancing functions will keep working if they are on different servers?

**Comment by cezarsa** [comment]
They should keep working independently, it's a bug that they currently don't.
The problem is, the agent is responsible for fetching an updated version of environment variables from the API (set with `tsuru env-set`) every time the container starts. It's also responsible for notifying the the API that the container is healthy and alive.
However, if the API is not available the moment the container starts, it should still be able to start using previously set environment variables, and it should keep trying to notify the API that it's alive until the moment the API comes back.

**Comment by jonaskac** [comment]
Great, that's what I'm looking for.

However, my tsuru server is running and I'm getting this error:
> http://localhost:2375: cannot connect to Docker endpoint
And it might be because of that that I'm getting that error in the containers.

**Comment by cezarsa** [comment]
Where is this error being printed to? Could you try running `tsr api --config=<your conf>`  while also running `tail -f /var/log/syslog | grep tsr`?

**Comment by jonaskac** [comment]
This is the output:
`Jan  9 21:01:25 tsuru tsr[9020]: FATAL: listen tcp 0.0.0.0:8080: bind: address already in use`

Hmmm, which is alright I guess since the tsuru server is up and running. Right?

**Comment by cezarsa** [comment]
This is on hold of docker/docker#10052. If it end up not being merged we'll probably switch to managing port allocation in tsuru, but this is going to need more time. I've removed this from the 0.10.0 milestone for not.

**Comment by cezarsa** [comment]
PR to docker has been refused. We'll switch to managing port allocation in tsuru.
