### ISSUE TITLE
docker node name inconsistency

### ISSUE THREAD

**Issue by jblancett** [tsuru/tsuru#1073]
I've noticed an inconsistency in how to identify your docker nodes with the cli tools.
For example, with `tsuru-admin containers-move` it only works if you specify the hostname only, without the protocol and port around it. Example:
`tsuru-admin containers-move ec2-54-174-22-35.compute-1.amazonaws.com ec2-54-174-37-14.compute-1.amazonaws.com ec2-54-174-22-35.compute-1.amazonaws.com`
Then, try to identify a node the same way with `tsuru-admin docker-node-remove` and it won't work.  With that command you have to specify protocol and port around it, like
`tsuru-admin docker-node-remove http://ec2-54-174-22-35.compute-1.amazonaws.com:2375`

This could be solved in a number of ways, one would be accepting either format with all commands.  Alternatively, or even in addition, when nodes are registered they could be given a nickname, similar to how docker containers get nicknamed, and could be identified with that.

**Comment by msabramo** [comment]
:+1: for making it consistent.
Bonus points for being lenient. 
Bonus bonus points for doing the nickname thing. Could borrow code from docker?

**Comment by cezarsa** [comment]
I'm in for leniency in both docker-node-remove and containers-move using unambiguous url fragments.
Not sure about nicknames though, not enough benefits for the added code complexity.
