### ISSUE TITLE
If you try to create a user when gandalf is down, the error is not helpful

### ISSUE THREAD

**Issue by msabramo** [tsuru/tsuru#1078]
If tsr is up but gandalf is down:

```
$ tsuru-admin user-create ${EMAIL}
Error: Failed to connect to tsuru server (127.0.0.1:8080), it's probably down.
```

and nothing is logged by `tsr` to stdout/stderr.

In truth, tsr **is** listening on port 8080; the actual problem is that gandalf is not running, but you cannot tell.

**Comment by andrewsmedina** [comment]
@msabramo `user-create` will be removed from `tsuru-admin` in the next `tsuru-admin` release. To create an user you should use `tsuru` client.

**Comment by msabramo** [comment]
Interesting. 

In any case I think this happened because I had some modified files.
