### ISSUE TITLE
tsuru-client: add "ssh" subcommand

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#1090]
This command should work like the `tsuru-admin ssh` command:

    $ tsuru ssh <container-id>

We can get the id of the container running tsuru app-info. We could also support the app name:

    $ tsuru ssh <app-name>

In this case, we would connect directly to the container of the app when the app has only one container, or let the user choose which container connect to. Something like:

    $ tsuru ssh myapp
    INFO: this app has multiple containers:

     - a3d93
    - a33df

Select the container (or type "any" for any container): <answer>
We could include the -a/--any flag.

**Comment by andrewsmedina** [comment]
is necessary to add docs about this command in tsuru client usage guide.

**Comment by tarsisazevedo** [comment]
done at tsuru/tsuru-admin@afd45efa384ba9d9e1731aeb364000717e312bc1 and tsuru/tsuru-client@a6f5cf0420cd4cef4c1e2830931e51139acd5532
