### ISSUE TITLE
make a dockerized setup for tsuru deployment

### ISSUE THREAD

**Issue by wagnersza** [tsuru/tsuru#1091]

**Comment by wagnersza** [comment]
under construction in https://github.com/tsuru/dockerized-setup

**Comment by CvX** [comment]
Hi, what's the status of this idea? I see that referenced repo is now deprecated.

**Comment by andrestc** [comment]
Hi @CvX,

We are currently working on a component called `tsuru installer` that is bundled in `tsuru client`. It is still in experimental state but we have plans to improve it and make it production ready. You can check its [documentation here](https://docs.tsuru.io/stable/experimental/installer.html).

**Comment by cezarsa** [comment]
Also, instead of having a single repository with multiple Dockerfiles (as was the case with tsuru/dockerized-setup), now each project has its own Dockerfile and all tsuru components are already available as docker images. `tsuru installer` uses these images to start tsuru components.
