### ISSUE TITLE
Doubt about segregate scheduler

### ISSUE THREAD

**Issue by nekrox** [tsuru/tsuru#1097]
If i use segregate scheduler with several host for each team, when i scale my app, the containers are distributed in all hosts for a segregated team like round robin?

**Comment by cezarsa** [comment]
Yes, the scheduler will always try to distribute your application equally across the available hosts.

**Comment by fsouza** [comment]
Closing this issue, since it was a question and it's now answered. Please feel free to open new issues in the future!
