### ISSUE TITLE
Support docker data volume as service

### ISSUE THREAD

**Issue by danielfree** [tsuru/tsuru#1100]
It'll be nice to have a docker data volume service: create docker data volume using service-add, and  link data volume to app container using service-bind. In this way tsuru can manage both database and data storage via the same interface.

**Comment by cezarsa** [comment]
This is somewhat difficult for us to implement currently, and I'm not sure if this should even be a goal. We would have to control which volume is available on each Node and how they map with units. Units would have different data available to them unless we backed this volumes in a network storage. All that would add a lot of complexity.

Using an external object storage (Swift / AWS S3...) is generally the recommended approach for storing data. If this doesn't work, it's feasible to mount external nfs/smb endpoints inside the container itself using hooks in tsuru.yaml.

Do you have a use case where either of these approaches wouldn't work?

**Comment by danielfree** [comment]
@cezarsa you are right, for legacy apps that use filesystem dir to read/write files, external nfs/smb endpoints can do the job.

**Comment by vmalaga** [comment]
@cezarsa I am trying to mount an external nfs vol with the hook on trusu.yaml but i get an error from the container:

    remote: mount.nfs: Operation not permitted
    remote: Exit status 32

I have at requirements.apt nfs-common and start the rpcbind and rpc.statd daemons needed for nfs locking, this is my tsuru.yaml

    hooks:
      build:
        - sudo /sbin/rpcbind
        - sudo /sbin/rpc.statd
        - sudo mkdir /home/ubuntu/mailbox && sudo mount -t nfs nfs02:/mnt/VMAIL /home/ubuntu/mailbox

You know if I need anything else?

**Comment by andrewsmedina** [comment]
@vmalaga to mount nfs in a docker container this container should be a "privileged" container. tsuru does not support container with "privileged" mode.

what you can do is mount nfs in the node and share this volume with your app. the "shared fs" is not documented yet. 

You can see more info here: https://github.com/tsuru/tsuru/issues/985

**Comment by vmalaga** [comment]
I have try shared fs at tsuru.conf but this option mount this volumen on every app-container without any option to decide which app can mount it

There is any option for this ?

**Comment by andrewsmedina** [comment]
@vmalaga with shared volumes enabled tsuru will create shared volumes for all apps. But, is possible create isolated volumes for each app:

    docker:
      sharedfs:
        app-isolation: true

**Comment by vmalaga** [comment]
@andrewsmedina what i mean is, if i have 2 NFS vols and i want that 

* nfsserver:/vol01 is mounted on app_cms and app_erp
* nfsserver:/vol02 is mounted on app_db and app_db2 but not at the rest of apps

What i can't find is if i can have more than one sharedfs on tsuru
Could be nice to have a NFS service so only apps that require a nfs vol could be started in privileged mode and have a sharedfs, not all apps

**Comment by mwduarte** [comment]
Hi Vicente, about the sharedfs support on tsuru take a look in issue #1163.

I had the same doubt about this feature of tsuru you are having now.

There, I post the steps I follow to discovery how it works.

Regards.

Date: Fri, 24 Apr 2015 07:35:48 -0700

**Comment by cweagans** [comment]
There are a few applications that don't support using S3 as a storage service. For those applications, it would be cool if the platform could compensate a bit, though I agree that building a full-blown network-backed redundant storage service is totally out of scope and too complex.

I'd suggest creating a service that's basically an S3 gateway. The container would simply mount s3 inside, and then expose NFS mounts when new instances of the service are created. This way, the data container can be responsible for authenticating with S3 and handling those details, and the only thing the consuming containers need to worry about is mounting an NFS volume from the Storage service.

Would this be a reasonable middle-ground? I know mounting S3 isn't really ideal, but it certainly helps those apps where application-level S3 management isn't desired or possible.

**Comment by devekko** [comment]
interesting write up using Maestro and Drupal and the file share issue

http://www.luiselizondo.net/a-production-ready-docker-workflow-part-2-the-storage-problem/
4 part series

**Comment by guestisp** [comment]
Interesting reading.
IMHO, that implementation already exists in tsuru with SharedFS capability as per #734

**Comment by devekko** [comment]
its also interesting from the Drupal paas called Aegir perspective

the article using solution architecture similar in many ways to Aegir
