### ISSUE TITLE
autoscale machine in pool

### ISSUE THREAD

**Issue by tarsisazevedo** [tsuru/tsuru#1110]
We have to autoscale machines in pool. If a machine become full of containers, tsuru should create another machine in IaaS and add it to pool and rebalance units.

**Comment by jonaskac** [comment]
:+1:

**Comment by cezarsa** [comment]
Closed, related commits: f18234d 1ef726a 5fe4ab3 7fd90b6 db01d5d 358dc7b 083720d 07da6b5 60ea8e9 aac3970 9bdaf97 cfa802c 491dbae a170eed 018b7f4 93c91e6 a75acff 7e9f8d8 54940be 018e085 7f071f0 a809ef7 59e0926 df9f40f a7b0826 a27d1b4 74f755c 869c86b 0df1f23 9af245b 5c89d6c 9a921e4 1abcdf9 741e78a 

I really need to remember to reference issue in commits :/
