### ISSUE TITLE
app: support removing all units from the application

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1111]
Sometimes it may be useful to have 0 units.

**Comment by lucasweiblen** [comment]
does this means just to remove the following lines?

https://github.com/tsuru/tsuru/blob/master/app/app.go#L402
https://github.com/tsuru/tsuru/blob/master/app/app.go#L403
https://github.com/tsuru/tsuru/blob/master/app/app.go#L404

**Comment by fsouza** [comment]
I think so, running some tests can prove it

FTR, you can link a selected area: https://github.com/tsuru/tsuru/blob/master/app/app.go#L402:L404.

**Comment by lucasweiblen** [comment]
heheh didnt know how to select a area :+1: 

I would like to try to solve this issue but I am having some issues to run all tests inside the box provisioned by tsuru-bootstrap.

Do you have any idea what could possible be happening?
I tried go get ./... and make test , both returning some issues.

**Comment by fsouza** [comment]
What's the output you get when running ``go test ./...``?

**Comment by lucasweiblen** [comment]
browsing the issues I found #1018 .. if I remember well I'm having the same problems but almost sure Mongo and Redis were running.. will try again tonight!

**Comment by lucasweiblen** [comment]
well, it seems Mongo and Redis were not running when I tried yesterday hehe, now I'm managing to run the tests.. thanks

think I will handle #1018 as well

**Comment by fsouza** [comment]
Closed via #1118.
