### ISSUE TITLE
cmd/tsuru-admin: add command to list routers

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1113]
We should have a command for listing the available routers for creating new plans:

```
% tsuru-admin router-list
```

**Comment by lucasweiblen** [comment]
anybody working on this issue?

**Comment by fsouza** [comment]
Nope, you can work on it, if you will.

**Comment by msabramo** [comment]
@lucasweiblen is shredding it up lately! Thanks for all your work!

**Comment by lucasweiblen** [comment]
I will give it a try!
Thanks @msabramo :)

**Comment by dcarley** [comment]
Lucas completed this in tsuru/tsuru-admin#2

**Comment by fsouza** [comment]
@dcarley thank you for pointing it!
