### ISSUE TITLE
cmd: improve app-shell error output

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#1115]
Currently `app-shell` is returning the http error:

    $ tsuru app-shell -a tsuru-dashboard3
    Error: HTTP/1.1 404

The command should return an user friendly error message.

**Comment by fsouza** [comment]
@wpjunior do you wanna work on it?

**Comment by wpjunior** [comment]
Yeah!, It is a good opportunity to learn more go lang!
