### ISSUE TITLE
tsuru-server-api doesn't start

### ISSUE THREAD

**Issue by mdekkers** [tsuru/tsuru#1124]
I get the following on trying to start tsuru-api-server:

    init: tsuru-server-api main process (3495) terminated with status 1
    init: tsuru-server-api main process ended, respawning
    tsr[3502]: WARNING: config key 'routers:hipache:type' not found, fallback to top level 'hipache:*' router config
    tsr[3502]: FATAL: no reachable servers

here is my tsuru.conf file

    listen: "0.0.0.0:8080"
    debug: true
    host: http://192.168.25.15:8080 # This port must be the same as in the "listen" conf
    admin-team: admin
    auth:
        user-registration: true
        scheme: native
    database:
        url: 192.168.25.12:27017
        name: tsurudb
    queue: redis
    redis-queue:
        host: 192.168.25.13
        port: 6379
    git:
        unit-repo: /home/application/current
        api-server: http://192.168.25.11:8000
    provisioner: docker
    docker:
        segregate: false
        router: hipache
        collection: docker_containers
        repository-namespace: tsuru
        deploy-cmd: /var/lib/tsuru/deploy
        cluster:
            storage: mongodb
            mongo-url: 192.168.25.12:27017
            mongo-database: cluster
        run-cmd:
            bin: /var/lib/tsuru/start
            port: "8888"
        ssh:
            add-key-cmd: /var/lib/tsuru/add-key
            user: ubuntu
        servers:
            - http://192.168.25.21:2375
    hipache:
        domain: tsuru.int
        redis-server: 192.168.25.12:6379

all services are running and reachable, except tsuru-server-api
I followed the installation guide from here: http://docs.tsuru.io/en/stable/installing/index.html
any help would be appreciated

**Comment by fsouza** [comment]
"no reachable servers" is an error from our mongodb driver, we should definitely improve it.

Can you ensure that you can connect to the configured mongo-url? You can run the command ``mongo 192.168.25.12:27017`` to check that.

Thanks for reporting!

**Comment by mdekkers** [comment]
thanks, I think it's time to go to sleep - mongodb was bound to localhost...

**Comment by fsouza** [comment]
No problem, the error didn't help at all. I've just created issue #1125 for improving the error message.

Thanks for reporting.
