### ISSUE TITLE
tsuru-admin create-user

### ISSUE THREAD

**Issue by mdekkers** [tsuru/tsuru#1127]
following the documentation here http://docs.tsuru.io/en/stable/installing/api.html on the "Creating admin user" section:

    tsuru-admin user-create myemail@somewhere.com

I get 

    Error: command "user-create" does not exist
    tsuru-admin --version
    tsuru-admin version 0.9.1.

nothing in the list of available commands indicates anything that allows me to create a user. Has this been moved somewhere?

**Comment by fsouza** [comment]
Hi @mdekkers. Yes, it has been moved and the documentation has been fixed by #1122, but we haven't updated the live documentation yet.

Thanks for reporting.
