### ISSUE TITLE
cmd/tsuru: add filters in app-list

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#1134]
`app-list` list all application that the logged user has access. It would be nice if `app-list` had some filters. `grep` solves this problem when you need to filter the apps by name, but sometimes you will need to list all apps that uses a specific platform or by teamowner, eg:

    $ tsuru app-list --platform=python

We can start adding `platform`, `teamowner`, `owner`, `name` filters. Where the name can accept a regex pattern.

**Comment by lucasweiblen** [comment]
anyone working on this issue?

**Comment by andrewsmedina** [comment]
@lucasweiblen no. Feel free to work on in this issue.

**Comment by lucasweiblen** [comment]
nice
