### ISSUE TITLE
Containers should kill themselves if they were removed from tsuru api database

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#1135]
Containers should kill themselves if they were removed from tsuru api database.

This could be handled by the status reporter present in tsuru-circus plugin. If the status reporting api call returns 404 it means that the container should not exist anymore.

**Comment by cezarsa** [comment]
After talking with @magnotorres and @fsouza we think the API should return 410 error if the container does not exist anymore with some specific message. 404 is too risky and could happen by accident. e.g. misconfigured DNS

**Comment by msabramo** [comment]
> Containers should kill themselves

Suicide is never the answer.

Sorry, couldn't resist :)

**Comment by fsouza** [comment]
![nspilogo_lg](https://cloud.githubusercontent.com/assets/108725/6627832/d190e3b2-c8df-11e4-94ef-9c51540d60c2.jpg)

**Comment by cezarsa** [comment]
This was fixed by tsuru/bs.
