### ISSUE TITLE
Lean containers

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#1136]
I'm writing down some discussions we had recently about simplifying containers.

Our platforms currently have some big dependencies, mainly tsuru-unit-agent, tsuru-circus and circus.

* `tsuru-unit-agent` is responsible for running hooks and reading an updated list of environment variables from tsuru API server every time the container is started.
* `tsuru-circus` is responsible for: periodically pinging tsuru API server notifying container status; streaming logs back to tsuru; and sending container metrics to tsuru.
* `circus` is responsible for managing Procfile processes and provide a plugin infrastructure which allow `tsuru-circus` to run.

We believe these functionalities should be provided outside the container. I'll try to enumerate some steps we might take to accomplish this goal.

* `tsuru-unit-agent`
  * Make environment variables part of the image. To get there we would need some kind of two-step build phase. Somewhat like it's proposed in the Twelve-Factor document (build + release => run). The second step would have to be executed every time a new env is set, generating a new image;
  * build hooks, tsuru could run them as part of the deploy pipeline;
  * restart-after hooks, not a problem anymore, tsuru is already responsible for running them;
  * restart-before hook, this is a problem. I'm not sure how to solve it without some intermediate process running inside the container. Maybe something ugly like tsuru running `bash -c 'hook && app'`, but this would mess up signals sent by docker to the main process. I'll take any better suggestion on this point.

* `tsuru-circus`
  * Every functionality provided by it could be provided by an external container running on the same node and using docker API locally to monitor its siblings. There are project already dedicated to a similar task, like https://github.com/gliderlabs/logspout. We can easily extend on their idea adding metrics and heartbeat, thus covering everything `tsuru-circus` does in a much more isolated way.

* `circus`
  * One of our goals is to run each Procfile process on isolated containers (#647). Doing this (and getting rid of `tsuru-circus`) would effectively eliminate the need for circus inside the container.

**Comment by jblancett** [comment]
Another thing that would make the containers smaller is using debian as a base instead of ubuntu

**Comment by fsouza** [comment]
I'm closing this issue. We've finished all the changes in the tsuru code base, and there's now one last thing that we need to do in bs: add support for metrics, collecting them from Docker. I've just opened tsuru/bs#2 for handling metrics.
