### ISSUE TITLE
tsr: add migration management

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1137]
Currently, when we have migrations between versions, we provide some script or use the start-up process to run the migration, we should provide a more decent process for running and tracking migrations between versions. We should be able to register and track execution of migration functions, allowing the user to run a command like ``tsr migrate``.

Once we have this, we should convert the migrateImage stuff to a migration function.

Providing a ``--dry`` flag for this command would be awesome as well!

**Comment by cezarsa** [comment]
`--dry` is considered harmful
