### ISSUE TITLE
cmd/tsuru: unit-add gives "unparseable chunk" error when sending "please wait"

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1151]
```
% tsuru unit-add 3

---- Starting 3 new units ----
 ---> Started unit 26cf3f4a16...
 ---> Started unit 456cd4f6de...
Error: Unparseable chunk: "please wait...\n"
```

**Comment by cezarsa** [comment]
I'm rather intrigued by this bug. unit-add doesn't create a KeepAliveWriter instance. The only place it's created is in the deploy handler in api/deploy.go. Also, the only place "please wait" string appears is in this same handler.
I don't see how a "please wait" string can show up during a unit-add operation. There is something **really** wrong going on.
