### ISSUE TITLE
cmd/tsuru: unify service-info and service-doc

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1152]
``tsuru service-info`` could display the documentation of the service, if any is available.

**Comment by lucasweiblen** [comment]
in this case we would need to display documentation for the service AND service-info right? Is there a better way to do this than returning the JSON representation of a map? 
something like: 
`
b, _ := json.Marshal(instances)
serviceMap := map[string][]byte{"doc": s.Doc, "info": b}
b2, _ := json.Marshal(serviceMap)
w.Write(b2)
return nil
`

**Comment by andrewsmedina** [comment]
You can send the serialized "Service" and add a "Instances" attribute.

**Comment by lucasweiblen** [comment]
good idea! thanx @andrewsmedina
