### ISSUE TITLE
unit-remove is removing wrong docker container

### ISSUE THREAD

**Issue by mwduarte** [tsuru/tsuru#1153]
Hi tsuru team, first off all, i would like to congrats you for the grates job you are doing with tsuru.

I'm testing 0.10.3 tsr version with 015.2 client version for 1 week ann the only issue I hit is when I run "tsuru unit-remove" and tsuru removes wrong container Id, bellow I detail this issue.

it seems your code is getting wrong docker ID or a random one.

I didn't find one issue direct related to this problem but I saw you heave a brunch identified "unit-remove", is this related to this problem?

Let me know if you need more pieces of information about this.  

Thanks, regards.

```
milton_duarte@ts:~/tsuru-dashboard$ /usr/bin/tsr version
tsr version 0.10.3.
```

tsuru.conf:
```
milton_duarte@ts:~/tsuru-dashboard$ cat /etc/tsuru/tsuru.conf
listen: "0.0.0.0:8080"
host: http://10.0.2.5:8080
debug: true
admin-team: admin

database:
  url: 127.0.0.1:27017
  name: tsurudb

git:
  unit-repo: /home/application/current
  api-server: http://127.0.0.1:8000

auth:
  user-registration: true
  scheme: native

repo-manager: gandalf
provisioner: docker

routers:
  hipache1:
    type: hipache
    domain: paas.rbs.com.br
    redis-server: localhost:6379

queue: redis
redis-queue:
  host: localhost
  port: 6379

docker:
  collection: docker_containers
  registry: 10.0.2.5:3030
  repository-namespace: tsuru
  router: hipache1
  deploy-cmd: /var/lib/tsuru/deploy
  segregate: true
  cluster:
    storage: mongodb
    mongo-url: 127.0.0.1:27017
    mongo-database: dockercluster
  run-cmd:
    bin: /var/lib/tsuru/start
    port: "8888"
  ssh:
    add-key-cmd: /var/lib/tsuru/add-key
    user: ubuntu
```
```
milton_duarte@ts:~/tsuru-dashboard$ tsuru version
tsuru version 0.15.2.
```
```
milton_duarte@ts:~/tsuru-dashboard$ tsuru app-list
+-----------------+-------------------------+---------------------------------+
| Application     | Units State Summary     | Address                         |
+-----------------+-------------------------+---------------------------------+
| blog            | 1 of 1 units in-service | blog.paas.rbs.com.br            |
+-----------------+-------------------------+---------------------------------+
| teste-andre     | 2 of 2 units in-service | teste-andre.paas.rbs.com.br     |
+-----------------+-------------------------+---------------------------------+
| tsuru-dashboard | 1 of 1 units in-service | tsuru-dashboard.paas.rbs.com.br |
+-----------------+-------------------------+---------------------------------+
```
```
CONTAINER ID        IMAGE                                        COMMAND                CREATED             STATUS              PORTS                     NAMES
1fc403394f6b        10.0.2.5:3030/tsuru/app-blog:v3              "/bin/bash -lc 'tsur   2 hours ago         Up 2 hours          0.0.0.0:49194->8888/tcp   2107930c469a236f7878   
f7ee55a888f7        10.0.2.5:3030/tsuru/app-tsuru-dashboard:v9   "/bin/bash -lc 'tsur   2 hours ago         Up 2 hours          0.0.0.0:49193->8888/tcp   1a7744e20f8f78f173f1   
3cb8dc472e79        10.0.2.5:3030/tsuru/app-teste-andre:v5       "/bin/bash -lc 'tsur   2 hours ago         Up 2 hours          0.0.0.0:49192->8888/tcp   83b88e94aaa5978c90fc   
946d0f24cad7        10.0.2.5:3030/tsuru/app-teste-andre:v5       "/bin/bash -lc 'tsur   2 hours ago         Up 2 hours          0.0.0.0:49191->8888/tcp   798ccc8f5d1735b4e930  
```
```
milton_duarte@ts:~/tsuru-dashboard$ tsuru app-info -a blog
Application: blog
Repository: git@10.170.92.43.nip.io:blog.git
Platform: php
Teams: devops-rbs
Address: blog.paas.rbs.com.br
Owner: milton.duarte@gruporbs.com.br
Team owner: devops-rbs
Deploys: 3
Units: 1
+------------+---------+-----------+-------+-------------+
| Unit       | State   | Host      | Port  | IP          |
+------------+---------+-----------+-------+-------------+
| 1fc403394f | started | 127.0.0.1 | 49194 | 172.17.0.67 |
+------------+---------+-----------+-------+-------------+

App Plan:
+---------------+--------+------+-----------+--------+---------+
| Name          | Memory | Swap | Cpu Share | Router | Default |
+---------------+--------+------+-----------+--------+---------+
| autogenerated | 0 MB   | 0 MB | 100       |        | false   |
+---------------+--------+------+-----------+--------+---------+
```
```
milton_duarte@ts:~/tsuru-dashboard$ tsuru app-info -a teste-andre
Application: teste-andre
Repository: git@10.170.92.43.nip.io:teste-andre.git
Platform: php
Teams: devops-rbs
Address: teste-andre.paas.rbs.com.br
Owner: andre.trevisani@gruporbs.com.br
Team owner: devops-rbs
Deploys: 7
Units: 2
+------------+---------+-----------+-------+-------------+
| Unit       | State   | Host      | Port  | IP          |
+------------+---------+-----------+-------+-------------+
| 946d0f24ca | started | 127.0.0.1 | 49191 | 172.17.0.60 |
| 3cb8dc472e | started | 127.0.0.1 | 49192 | 172.17.0.61 |
+------------+---------+-----------+-------+-------------+

App Plan:
+---------------+--------+------+-----------+--------+---------+
| Name          | Memory | Swap | Cpu Share | Router | Default |
+---------------+--------+------+-----------+--------+---------+
| autogenerated | 0 MB   | 0 MB | 100       |        | false   |
+---------------+--------+------+-----------+--------+---------+
```
```
milton_duarte@ts:~/tsuru-dashboard$ tsuru app-info -a tsuru-dashboard
Application: tsuru-dashboard
Repository: git@10.170.92.43.nip.io:tsuru-dashboard.git
Platform: python
Teams: admin
Address: tsuru-dashboard.paas.rbs.com.br
Owner: admin@example.com
Team owner: admin
Deploys: 7
Units: 1
+------------+---------+-----------+-------+-------------+
| Unit       | State   | Host      | Port  | IP          |
+------------+---------+-----------+-------+-------------+
| f7ee55a888 | started | 127.0.0.1 | 49193 | 172.17.0.64 |
+------------+---------+-----------+-------+-------------+

App Plan:
+---------------+--------+------+-----------+--------+---------+
| Name          | Memory | Swap | Cpu Share | Router | Default |
+---------------+--------+------+-----------+--------+---------+
| autogenerated | 0 MB   | 0 MB | 100       |        | false   |
+---------------+--------+------+-----------+--------+---------+

```
```
milton_duarte@ts:~/tsuru-dashboard$ tsuru unit-add 3 -a teste-andre

---- Starting 3 new units ----
 ---> Started unit 70dffc323b...
 ---> Started unit 1bda4cbc46...
 ---> Started unit cd00afcaed...

---- Binding and checking 3 new units ----
 ---> Bound and checked unit 70dffc323b
 ---> Bound and checked unit cd00afcaed
 ---> Bound and checked unit 1bda4cbc46

---- Adding routes to 3 new units ----
 ---> Added route to unit 70dffc323b
 ---> Added route to unit 1bda4cbc46
 ---> Added route to unit cd00afcaed
```
```
milton_duarte@ts:~/tsuru-dashboard$ docker ps
CONTAINER ID        IMAGE                                        COMMAND                CREATED              STATUS              PORTS                     NAMES
cd00afcaed71        10.0.2.5:3030/tsuru/app-teste-andre:v5       "/bin/bash -lc 'tsur   About a minute ago   Up About a minute   0.0.0.0:49197->8888/tcp   a5d1d178eb8151e51c99   
70dffc323b6e        10.0.2.5:3030/tsuru/app-teste-andre:v5       "/bin/bash -lc 'tsur   About a minute ago   Up About a minute   0.0.0.0:49195->8888/tcp   488f100a37fe964fab4b   
1bda4cbc467c        10.0.2.5:3030/tsuru/app-teste-andre:v5       "/bin/bash -lc 'tsur   About a minute ago   Up About a minute   0.0.0.0:49196->8888/tcp   6b99527f13e905228d0a   
1fc403394f6b        10.0.2.5:3030/tsuru/app-blog:v3              "/bin/bash -lc 'tsur   2 hours ago          Up 2 hours          0.0.0.0:49194->8888/tcp   2107930c469a236f7878   
f7ee55a888f7        10.0.2.5:3030/tsuru/app-tsuru-dashboard:v9   "/bin/bash -lc 'tsur   2 hours ago          Up 2 hours          0.0.0.0:49193->8888/tcp   1a7744e20f8f78f173f1   
3cb8dc472e79        10.0.2.5:3030/tsuru/app-teste-andre:v5       "/bin/bash -lc 'tsur   2 hours ago          Up 2 hours          0.0.0.0:49192->8888/tcp   83b88e94aaa5978c90fc   
946d0f24cad7        10.0.2.5:3030/tsuru/app-teste-andre:v5       "/bin/bash -lc 'tsur   2 hours ago          Up 2 hours          0.0.0.0:49191->8888/tcp   798ccc8f5d1735b4e930  
```
```

milton_duarte@ts:~/tsuru-dashboard$ tsuru app-info -a teste-andre
Application: teste-andre
Repository: git@10.170.92.43.nip.io:teste-andre.git
Platform: php
Teams: devops-rbs
Address: teste-andre.paas.rbs.com.br
Owner: andre.trevisani@gruporbs.com.br
Team owner: devops-rbs
Deploys: 7
Units: 5
+------------+---------+-----------+-------+-------------+
| Unit       | State   | Host      | Port  | IP          |
+------------+---------+-----------+-------+-------------+
| 946d0f24ca | started | 127.0.0.1 | 49191 | 172.17.0.60 |
| 3cb8dc472e | started | 127.0.0.1 | 49192 | 172.17.0.61 |
| 70dffc323b | started | 127.0.0.1 | 49195 | 172.17.0.68 |
| 1bda4cbc46 | started | 127.0.0.1 | 49196 | 172.17.0.69 |
| cd00afcaed | started | 127.0.0.1 | 49197 | 172.17.0.70 |
+------------+---------+-----------+-------+-------------+

App Plan:
+---------------+--------+------+-----------+--------+---------+
| Name          | Memory | Swap | Cpu Share | Router | Default |
+---------------+--------+------+-----------+--------+---------+
| autogenerated | 0 MB   | 0 MB | 100       |        | false   |
+---------------+--------+------+-----------+--------+---------+

```
```
milton_duarte@ts:~/tsuru-dashboard$ tsuru app-info -a teste-andre
Application: teste-andre
Repository: git@10.170.92.43.nip.io:teste-andre.git
Platform: php
Teams: devops-rbs
Address: teste-andre.paas.rbs.com.br
Owner: andre.trevisani@gruporbs.com.br
Team owner: devops-rbs
Deploys: 7
Units: 5
+------------+---------+-----------+-------+-------------+
| Unit       | State   | Host      | Port  | IP          |
+------------+---------+-----------+-------+-------------+
| 946d0f24ca | started | 127.0.0.1 | 49191 | 172.17.0.60 |
| 3cb8dc472e | started | 127.0.0.1 | 49192 | 172.17.0.61 |
| 70dffc323b | started | 127.0.0.1 | 49195 | 172.17.0.68 |
| 1bda4cbc46 | started | 127.0.0.1 | 49196 | 172.17.0.69 |
| cd00afcaed | started | 127.0.0.1 | 49197 | 172.17.0.70 |
+------------+---------+-----------+-------+-------------+

App Plan:
+---------------+--------+------+-----------+--------+---------+
| Name          | Memory | Swap | Cpu Share | Router | Default |
+---------------+--------+------+-----------+--------+---------+
| autogenerated | 0 MB   | 0 MB | 100       |        | false   |
+---------------+--------+------+-----------+--------+---------+
```
```
milton_duarte@ts:~/tsuru-dashboard$ tsuru unit-remove 4 -a teste-andre
Units successfully removed!
```
************ Here you can see that tsuru removed docker containers from Apps "blog" and "tsuru-dashboard" and stil remains three docker instances that belongs to App teste-andre*************
```
milton_duarte@ts:~/tsuru-dashboard$ docker ps
CONTAINER ID        IMAGE                                    COMMAND                CREATED             STATUS              PORTS                     NAMES
cd00afcaed71        10.0.2.5:3030/tsuru/app-teste-andre:v5   "/bin/bash -lc 'tsur   3 minutes ago       Up 3 minutes        0.0.0.0:49197->8888/tcp   a5d1d178eb8151e51c99   
70dffc323b6e        10.0.2.5:3030/tsuru/app-teste-andre:v5   "/bin/bash -lc 'tsur   3 minutes ago       Up 3 minutes        0.0.0.0:49195->8888/tcp   488f100a37fe964fab4b   
1bda4cbc467c        10.0.2.5:3030/tsuru/app-teste-andre:v5   "/bin/bash -lc 'tsur   3 minutes ago       Up 3 minutes        0.0.0.0:49196->8888/tcp   6b99527f13e905228d0a   
```
```

milton_duarte@ts:~/tsuru-dashboard$ tsuru app-list
+-----------------+-------------------------+---------------------------------+
| Application     | Units State Summary     | Address                         |
+-----------------+-------------------------+---------------------------------+
| blog            | 0 of 0 units in-service | blog.paas.rbs.com.br            |
+-----------------+-------------------------+---------------------------------+
| teste-andre     | 3 of 3 units in-service | teste-andre.paas.rbs.com.br     |
+-----------------+-------------------------+---------------------------------+
| tsuru-dashboard | 0 of 0 units in-service | tsuru-dashboard.paas.rbs.com.br |
+-----------------+-------------------------+---------------------------------+

```

**Comment by mwduarte** [comment]
Bellow are the tsr daemon logs:


Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the reserve-units-to-add action
Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the provision-add-units action
Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the provision-add-units-to-host action
Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the insert-empty-container action
Mar 27 14:56:55 ts tsr[17652]: message repeated 2 times: [ [pipeline] running the Forward for the insert-empty-container action]
Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the create-container action
Mar 27 14:56:55 ts tsr[17652]: create container for app teste-andre, based on image 10.0.2.5:3030/tsuru/app-teste-andre:v5, with cmds [/bin/bash -lc tsuru_unit_agent http://10.0.2.5:8080 b165d8bba78a89e9e2288b25068f7d097adbd6dc teste-andre /var/lib/tsuru/start && tail -f /dev/null]
Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the create-container action
Mar 27 14:56:55 ts tsr[17652]: create container for app teste-andre, based on image 10.0.2.5:3030/tsuru/app-teste-andre:v5, with cmds [/bin/bash -lc tsuru_unit_agent http://10.0.2.5:8080 b165d8bba78a89e9e2288b25068f7d097adbd6dc teste-andre /var/lib/tsuru/start && tail -f /dev/null]
Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the create-container action
Mar 27 14:56:55 ts tsr[17652]: create container for app teste-andre, based on image 10.0.2.5:3030/tsuru/app-teste-andre:v5, with cmds [/bin/bash -lc tsuru_unit_agent http://10.0.2.5:8080 b165d8bba78a89e9e2288b25068f7d097adbd6dc teste-andre /var/lib/tsuru/start && tail -f /dev/null]
Mar 27 14:56:55 ts tsr[17652]: [scheduler] Possible nodes for container 488f100a37fe964fab4b: []string{"127.0.0.1"}
Mar 27 14:56:55 ts tsr[17652]: [scheduler] Possible nodes for container a5d1d178eb8151e51c99: []string{"127.0.0.1"}
Mar 27 14:56:55 ts tsr[17652]: [scheduler] Possible nodes for container 6b99527f13e905228d0a: []string{"127.0.0.1"}
Mar 27 14:56:55 ts tsr[17652]: [scheduler] Chosen node for container 488f100a37fe964fab4b: "http://127.0.0.1:2375" Count: 20004
Mar 27 14:56:55 ts tsr[17652]: [scheduler] Chosen node for container a5d1d178eb8151e51c99: "http://127.0.0.1:2375" Count: 30005
Mar 27 14:56:55 ts tsr[17652]: [scheduler] Chosen node for container 6b99527f13e905228d0a: "http://127.0.0.1:2375" Count: 40006
Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the start-container action
Mar 27 14:56:55 ts tsr[17652]: starting container 70dffc323b6ebb60b33a679ad7baec8805b91a5089cbbac958835ab03156db79
Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the start-container action
Mar 27 14:56:55 ts tsr[17652]: starting container 1bda4cbc467cc7746cf498bc7f47682736795425589c1384d36e03ba83083509
Mar 27 14:56:55 ts tsr[17652]: [pipeline] running the Forward for the start-container action
Mar 27 14:56:55 ts tsr[17652]: starting container cd00afcaed7145a41088699a8382082ea556677dcb9358e4340df7308c44202d
Mar 27 14:56:55 ts kernel: [23521.967971] device veth955fb67 entered promiscuous mode
Mar 27 14:56:55 ts kernel: [23521.968178] IPv6: ADDRCONF(NETDEV_UP): veth955fb67: link is not ready
Mar 27 14:56:55 ts kernel: [23522.039382] IPv6: ADDRCONF(NETDEV_CHANGE): veth955fb67: link becomes ready
Mar 27 14:56:55 ts kernel: [23522.039403] docker0: port 3(veth955fb67) entered forwarding state
Mar 27 14:56:55 ts kernel: [23522.039409] docker0: port 3(veth955fb67) entered forwarding state
Mar 27 14:56:55 ts kernel: [23522.067676] device vetha4cd083 entered promiscuous mode
Mar 27 14:56:55 ts kernel: [23522.067989] IPv6: ADDRCONF(NETDEV_UP): vetha4cd083: link is not ready
Mar 27 14:56:55 ts kernel: [23522.067997] docker0: port 4(vetha4cd083) entered forwarding state
Mar 27 14:56:55 ts kernel: [23522.068005] docker0: port 4(vetha4cd083) entered forwarding state
Mar 27 14:56:56 ts tsr[17652]: [pipeline] running the Forward for the update-database-container action
Mar 27 14:56:56 ts tsr[17652]: [pipeline] running the Forward for the set-network-info action
Mar 27 14:56:56 ts kernel: [23522.183255] IPv6: ADDRCONF(NETDEV_CHANGE): vetha4cd083: link becomes ready
Mar 27 14:56:56 ts kernel: [23522.243364] device veth6f8f120 entered promiscuous mode
Mar 27 14:56:56 ts kernel: [23522.243612] IPv6: ADDRCONF(NETDEV_UP): veth6f8f120: link is not ready
Mar 27 14:56:56 ts kernel: [23522.243616] docker0: port 5(veth6f8f120) entered forwarding state
Mar 27 14:56:56 ts kernel: [23522.243653] docker0: port 5(veth6f8f120) entered forwarding state
Mar 27 14:56:56 ts tsr[17652]: [pipeline] running the Forward for the update-database-container action
Mar 27 14:56:56 ts tsr[17652]: [pipeline] running the Forward for the set-network-info action
Mar 27 14:56:56 ts kernel: [23522.393128] IPv6: ADDRCONF(NETDEV_CHANGE): veth6f8f120: link becomes ready
Mar 27 14:56:56 ts tsr[17652]: [pipeline] running the Forward for the update-database-container action
Mar 27 14:56:56 ts tsr[17652]: [pipeline] running the Forward for the set-network-info action
Mar 27 14:56:56 ts tsr[17652]: [pipeline] running the Forward for the bind-and-healthcheck action
Mar 27 14:56:56 ts tsr[17652]: [pipeline] running the Forward for the add-new-routes action
Mar 27 14:56:56 ts tsr[17652]: [pipeline] running the Forward for the update-app-image action
Mar 27 14:57:10 ts kernel: [23537.052951] docker0: port 3(veth955fb67) entered forwarding state
Mar 27 14:57:11 ts kernel: [23537.116208] docker0: port 4(vetha4cd083) entered forwarding state
Mar 27 14:57:11 ts kernel: [23537.244172] docker0: port 5(veth6f8f120) entered forwarding state
Mar 27 14:59:44 ts tsr[17652]: [scheduler] Possible nodes for remove a container: []string{"127.0.0.1"}
Mar 27 14:59:44 ts tsr[17652]: [scheduler] Chosen node for remove a container: "http://127.0.0.1:2375" Count: 7
Mar 27 14:59:44 ts tsr[17652]: Removing container 946d0f24cad76ce41e43f254b1e38a32ff9d2379d96893bca0f814e3eeb70815 from docker
Mar 27 14:59:54 ts kernel: [23700.517058] docker0: port 6(veth854092f) entered disabled state
Mar 27 14:59:54 ts kernel: [23700.518852] device veth854092f left promiscuous mode
Mar 27 14:59:54 ts kernel: [23700.518863] docker0: port 6(veth854092f) entered disabled state
Mar 27 14:59:54 ts tsr[17652]: Removing container 946d0f24cad76ce41e43f254b1e38a32ff9d2379d96893bca0f814e3eeb70815 from database
Mar 27 14:59:54 ts tsr[17652]: [scheduler] Possible nodes for remove a container: []string{"127.0.0.1"}
Mar 27 14:59:54 ts tsr[17652]: [scheduler] Chosen node for remove a container: "http://127.0.0.1:2375" Count: 6
Mar 27 14:59:54 ts tsr[17652]: Removing container 3cb8dc472e792a9e6859129747445fa899e40af2e6dd51b8bf97c84d14f3cd68 from docker
Mar 27 15:00:04 ts kernel: [23710.992979] docker0: port 7(vethec4f481) entered disabled state
Mar 27 15:00:04 ts kernel: [23710.994530] device vethec4f481 left promiscuous mode
Mar 27 15:00:04 ts kernel: [23710.994538] docker0: port 7(vethec4f481) entered disabled state
Mar 27 15:00:05 ts tsr[17652]: Removing container 3cb8dc472e792a9e6859129747445fa899e40af2e6dd51b8bf97c84d14f3cd68 from database
Mar 27 15:00:05 ts tsr[17652]: [scheduler] Possible nodes for remove a container: []string{"127.0.0.1"}
Mar 27 15:00:05 ts tsr[17652]: [scheduler] Chosen node for remove a container: "http://127.0.0.1:2375" Count: 5
Mar 27 15:00:05 ts tsr[17652]: Removing container f7ee55a888f73549c6751da7e36c0fd98104a3defc991ab771c5929c0813c05c from docker
Mar 27 15:00:15 ts kernel: [23721.362719] docker0: port 1(veth8d7fd45) entered disabled state
Mar 27 15:00:15 ts kernel: [23721.365374] device veth8d7fd45 left promiscuous mode
Mar 27 15:00:15 ts kernel: [23721.365388] docker0: port 1(veth8d7fd45) entered disabled state
Mar 27 15:00:15 ts tsr[17652]: Removing container f7ee55a888f73549c6751da7e36c0fd98104a3defc991ab771c5929c0813c05c from database
Mar 27 15:00:15 ts tsr[17652]: [scheduler] Possible nodes for remove a container: []string{"127.0.0.1"}
Mar 27 15:00:15 ts tsr[17652]: [scheduler] Chosen node for remove a container: "http://127.0.0.1:2375" Count: 4
Mar 27 15:00:15 ts tsr[17652]: Removing container 1fc403394f6bedba01612ef83641de225298727381d25aa32407e87d4cdf975f from docker
Mar 27 15:00:25 ts kernel: [23731.857324] docker0: port 2(veth08434a7) entered disabled state
Mar 27 15:00:25 ts kernel: [23731.859081] device veth08434a7 left promiscuous mode
Mar 27 15:00:25 ts kernel: [23731.859093] docker0: port 2(veth08434a7) entered disabled state
Mar 27 15:00:25 ts tsr[17652]: Removing container 1fc403394f6bedba01612ef83641de225298727381d25aa32407e87d4cdf975f from database
Mar 27 15:00:30 ts dhclient: DHCPREQUEST of 10.0.2.5 on eth0 to 10.0.2.3 port 67 (xid=0x62447cb0)
Mar 27 15:00:30 ts dhclient: DHCPACK of 10.0.2.5 from 10.0.2.3
Mar 27 15:00:30 ts dhclient: bound to 10.0.2.5 -- renewal in 480 seconds.

**Comment by cezarsa** [comment]
Thanks for reporting @mwduarte! We're taking a look at it right now.

**Comment by cezarsa** [comment]
@mwduarte We found out that this is a bug on master currently, but it's not affecting the current 0.10.3 stable release. How did you install tsuru server? If you are using tsuru/now it defaults to installing `nightly` build packages. To confirm this, could you please run `apt-cache show tsuru-server`?

**Comment by mwduarte** [comment]
I follow the instructions on tsuru/now (https://github.com/tsuru/now), running the command:

./run.bash --host-name paas.rbs.com.br

Bellow the required information and the Ubuntu release used.

Regards.

milton_duarte@ts:~$ uname -a
Linux ts 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
milton_duarte@ts:~$ apt-cache show tsuru-server
Package: tsuru-server
Priority: extra
Section: devel
Installed-Size: 10593
Maintainer: Globo.com <tsuru@corp.globo.com>
Architecture: amd64
Version: 0.10.3+1SNAPSHOT20150326034511+0000-1~trusty1
Depends: sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), libsqlite3-0
Filename: pool/main/t/tsuru-server/tsuru-server_0.10.3+1SNAPSHOT20150326034511+0000-1~trusty1_amd64.deb
Size: 2199860
MD5sum: d337faa422f083808ffd1f439694e2f8
SHA1: 72c43a3071059fc84fff7f2eacdf97dd0ab49a4f
SHA256: 6ef575016c806fdc616484921c27f770b9c6da239b482ef93e954365a6ccc6fc
Description-en: tsuru-server is the server side of the Tsuru PaaS.
 This package includes two services: Tsuru API and Tsuru SSH agent. All jobs
 are disabled by default, to enable any of them, edit the file
 /etc/default/tsuru-server.
Description-md5: 178d777e45d5e11c7dc989a386051f86

Package: tsuru-server
Status: install ok installed
Priority: extra
Section: devel
Installed-Size: 10593
Maintainer: Globo.com <tsuru@corp.globo.com>
Architecture: amd64
Version: 0.10.3+1SNAPSHOT20150325034212+0000-1~trusty1
Depends: sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), libsqlite3-0
Conffiles:
 /etc/init.d/tsuru-server-api 28e8722356b6e2222fb3e8509e53bfe4
 /etc/tsuru/tsuru.conf 58240701018750de2bf0d265788cff3d
 /etc/default/tsuru-server eaacbaa4149df8f0fc5668d020fce19c
 /etc/init/tsuru-server-api.conf 607abb968aa4df1950bfa8cbc10dcf83
Description-en: tsuru-server is the server side of the Tsuru PaaS.
 This package includes two services: Tsuru API and Tsuru SSH agent. All jobs
 are disabled by default, to enable any of them, edit the file
 /etc/default/tsuru-server.
Description-md5: 178d777e45d5e11c7dc989a386051f86
Homepage: http://tsuru.io

Package: tsuru-server
Priority: extra
Section: devel
Installed-Size: 10023
Maintainer: Globo.com <tsuru@corp.globo.com>
Architecture: amd64
Version: 0.10.3-0~trusty1
Depends: sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), libsqlite3-0
Filename: pool/main/t/tsuru-server/tsuru-server_0.10.3-0~trusty1_amd64.deb
Size: 2097060
MD5sum: ceadc4a069740859ed023535cb73eacf
SHA1: a77cb362f434bba30a8722dc81b237ce9f5bc838
SHA256: dc2b041a73aa055cb0191feecf6bbb884393ce16cb2c0e3efd5aec2688259403
Description-en: tsuru-server is the server side of the Tsuru PaaS.
 This package includes two services: Tsuru API and Tsuru SSH agent. All jobs
 are disabled by default, to enable any of them, edit the file
 /etc/default/tsuru-server.
Description-md5: 178d777e45d5e11c7dc989a386051f86

**Comment by mwduarte** [comment]
Ok @cezarsa , I'll install the version bellow, it's ok related to this issue, right?

Thanks.

Package: tsuru-server
Priority: extra
Section: devel
Installed-Size: 10023
Maintainer: Globo.com <tsuru@corp.globo.com>
Architecture: amd64
Version: 0.10.3-0~trusty1
Depends: sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), libsqlite3-0
Filename: pool/main/t/tsuru-server/tsuru-server_0.10.3-0~trusty1_amd64.deb
Size: 2097060
MD5sum: ceadc4a069740859ed023535cb73eacf
SHA1: a77cb362f434bba30a8722dc81b237ce9f5bc838
SHA256: dc2b041a73aa055cb0191feecf6bbb884393ce16cb2c0e3efd5aec2688259403
Description-en: tsuru-server is the server side of the Tsuru PaaS.
 This package includes two services: Tsuru API and Tsuru SSH agent. All jobs
 are disabled by default, to enable any of them, edit the file
 /etc/default/tsuru-server.
Description-md5: 178d777e45d5e11c7dc989a386051f86

**Comment by fsouza** [comment]
Hi @mwduarte, this package that you showed should work fine. I've just opened #1154 so we can improve version reporting in the nightly package.

Thanks for reporting this issue! We're already working to fix it.

**Comment by mwduarte** [comment]
Thanks all, you are really doing a great job here.

Congrats, again.

Best regards.
