### ISSUE TITLE
tsuru command posts password over http

### ISSUE THREAD

**Issue by adamclerk** [tsuru/tsuru#1157]
Am I sending my password over an unsecured http connection? Granted: I could be reading the source code wrong. Please correct me if I am.

Even if I tried to secure my target via pass through ssl and nginx (haven't yet attempted) tsuru is changing the url schema from `https` to `http`.

Is there already a solution to secure the tsuru target? 

Auth Post
=======
https://github.com/tsuru/tsuru/blob/5823cc661dad5ea555ee26baeb8ee1663f8b1ed4/cmd/auth.go#L30-L49

```go
func nativeLogin(context *Context, client *Client) error {
	var email string
	if len(context.Args) > 0 {
		email = context.Args[0]
	} else {
		fmt.Fprint(context.Stdout, "Email: ")
		fmt.Fscanf(context.Stdin, "%s\n", &email)
	}
	fmt.Fprint(context.Stdout, "Password: ")
	password, err := PasswordFromReader(context.Stdin)
	if err != nil {
		return err
	}
	fmt.Fprintln(context.Stdout)
	url, err := GetURL("/users/" + email + "/tokens")
	if err != nil {
		return err
	}
	b := bytes.NewBufferString(`{"password":"` + password + `"}`)
	request, err := http.NewRequest("POST", url, b)
```

Schema Change
=============
https://github.com/tsuru/tsuru/blob/5823cc661dad5ea555ee26baeb8ee1663f8b1ed4/cmd/target.go#L112-L122

```go
func GetURL(path string) (string, error) {
	var prefix string
	target, err := ReadTarget()
	if err != nil {
		return "", err
	}
	if m, _ := regexp.MatchString("^https?://", target); !m {
		prefix = "http://"
	}
	return prefix + strings.TrimRight(target, "/") + path, nil
}
```

**Comment by adamclerk** [comment]
Nevermind. I missed the `!m`. I also ran a modified version of the function through playground
https://play.golang.org/p/mXg9fTBl_s

as you were :sry: :sweat_smile:

**Comment by andrewsmedina** [comment]
No problem. By the way, you can enable https in tsuru api without nginx. Just changing some config values: http://docs.tsuru.io/en/stable/reference/config.html?highlight=https#use-tls
