### ISSUE TITLE
WebSockets for app-shell

### ISSUE THREAD

**Issue by jblancett** [tsuru/tsuru#1162]
need to set upgrade headers in app-shell response so tsuru api will work through a reverse proxy
more info here: #1161

**Comment by jblancett** [comment]
this was fixed via https://github.com/tsuru/tsuru/issues/1148

**Comment by fsouza** [comment]
Hi @jblancett, it doesn't work behind nginx yet, because we don't set the proper headers for WebSocket. #1148 fixed just the communication with TLS enabled servers.

**Comment by jblancett** [comment]
its working through mine

**Comment by jblancett** [comment]
I take that back, my mistake >.<
