### ISSUE TITLE
docker:ssh

### ISSUE THREAD

**Issue by jblancett** [tsuru/tsuru#1166]
tsr api still expects docker:ssh config even though it is deprecated and removed from docs

**Comment by cezarsa** [comment]
Actually ``docker:ssh:user`` is still necessary, it was removed from docs by mistake.

However, the current name is misleading. This config is used to select the username chosen to start the docker container. We should change it to ``docker:user`` and use ``docker:ssh:user`` as a fallback for backward compatibility.

**Comment by jblancett** [comment]
sounds good @cezarsa thanks!
