### ISSUE TITLE
cmd: JoinWithUserDir not working on Windows

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1169]
The ``HOME`` environment variable doesn't exist on Windows, we should use something else (probably ``USERPROFILE`` or ``HOMEPATH``).

**Comment by marceloboeira** [comment]
@fsouza sorry if it is a 'rookie' question, but I'm starting to study GO, so I just want to make sure, does tsuru already have a proper way to check the target environment OS ? so it can be checked and handled here: 
https://github.com/tsuru/tsuru/blob/3ecf7dfef31452791f47dbd1e67aa3e519e49bf0/cmd/utils.go#L19

So far I could not find anything specific, so  I was thinking to use something like:
`os.Getenv("WINVER") ` or even `os.PathSeparator`

If you could clear that for me, I would be happy to send a pl soon as possible. Thanks.

Reference:
http://stackoverflow.com/questions/19847594/how-to-reliably-detect-os-platform-in-go

**Comment by fsouza** [comment]
@marceloboeira you should check ``runtime.GOOS``, or use build tags/file suffix to conditionally include a file in the build.

Something like:

```
% cat home_windows.go
package cmd

import "os"

var home = os.Getenv("HOMEPATH")
% cat home_unix.go
package cmd

// +build: !windows

import "os"

var home = os.Getenv("HOME")
```

And then use the variable ``home`` in the JoinWithUserDir function.

**Comment by marceloboeira** [comment]
@fsouza alright, get it, thanks :+1:
