### ISSUE TITLE
tsuru app-list don't work after app-remove

### ISSUE THREAD

**Issue by vmalaga** [tsuru/tsuru#1176]
If i remove an app the tsuru api return error:

    root@tsurudev:~# tsuru app-remove -a irmadmin
    Are you sure you want to remove app "irmadmin"? (y/n) y
    App "irmadmin" successfully removed!
    root@tsurudev:~# tsuru app-list 
    Error: json: error calling MarshalJSON for type app.App: repository not found

After a few seconds the tsuru api returns to normal operation

**Comment by andrewsmedina** [comment]
@vmalaga thanks for report. this issue is already fixed on master.
