### ISSUE TITLE
cmd/tsuru-admin team-list

### ISSUE THREAD

**Issue by jblancett** [tsuru/tsuru#1183]
the `tsuru team-list` command only shows teams you are a member of, which makes sense.
There should also be a `tsuru-admin team-list` to get a list of all teams

**Comment by cezarsa** [comment]
Fixed by 2526c238def63d5c4c2a9a72f1ef33cb2f7fbe18 and tsuru/tsuru-client@a721fd5ae815ef583437a62a690b58add36f9903
Now if an admin user runs `tsuru team-list` it will show all teams.
