### ISSUE TITLE
Is it possible to bind app to a specific port (e.g. 80)

### ISSUE THREAD

**Issue by haifengkao** [tsuru/tsuru#1185]
Can tsuru bind an app to a specific port of the host system?
I think it is possible with hipache, but I don't know where to config it in tsuru. Is there any place I should look for?

**Comment by jonaskac** [comment]
:+1:

**Comment by fsouza** [comment]
@haifengkao what do you mean exactly? Having a dedicated port in hipache for the application? Or binding the application to more than one port, other than the provided ``$PORT``?

**Comment by haifengkao** [comment]
I mean the first one: having a dedicated port in hipache for the application

**Comment by cezarsa** [comment]
Hipache can listen on port any port configured on hipache.conf file, but it will only listen on this one port, as far as I know, there's no way of making it listen on multiple ports. Hipache routing is based on the `Host` HTTP header so listening on only one port is enough for routing HTTP based applications.

Can you provide a scenario where having hipache listening on multiple ports would be useful?

**Comment by haifengkao** [comment]
This issue has been brought up by some Dokku users. I don't know what their scenarios are. But for me, I want to avoid DNS lookup time. If I can use ip address/port to specify the server locations, the response time can be greatly reduced. 
Using paid DNS like Amazon Route 53 can be another option, but it's faster if no DNS is involved.

**Comment by cezarsa** [comment]
You can make a request to hipache using only ip and port, however you would need to specify the Host header in the request as hipache needs it to route the request.
Something like `curl -H "app.host.name" <hipache_ip>:<hipache_port>`

**Comment by guilhermebr** [comment]
Closing this issue due age and inactivity.
