### ISSUE TITLE
app-restart recovery

### ISSUE THREAD

**Issue by jblancett** [tsuru/tsuru#1188]
if app-restart fails while bringing up the new containers for whatever reason, such as timeout talking to docker api, or health checks fail, app is left stuck in locked state and with double the containers it previously had.  Ideally tsuru would catch any errors during this process and roll back to the previous state

**Comment by cezarsa** [comment]
We've improved and made safer a lot of the replace units pipeline (used in restart, deploy, env-set, ...) during the development of 0.12.0. I just tried it now and wasn't able to cause inconsistencies with app-restart anymore.
Also, tsuru will now explicitly log that a rollback is happening and which steps are being executed to rollback to previous state.
