### ISSUE TITLE
Architecture of Workflow in Tsuru (to authors)

### ISSUE THREAD

**Issue by dmitryck** [tsuru/tsuru#1191]
I read all documentation of TSURU
It's good, BUT i could not find a most important information!

What is the Architecture of workflow!??

example:
A. App developers has they own machines
B. For testing applications must be a testing server
C. For working www application must be a production server

AND THERE IS NO INFO how i must use tsuru in that architecture!!
1. On witch of this machines (A, B, C) what of the tsuru component i need to install???
2. And how developing application, how testing it???

OR Tsuru system suggests the alternative to A, B, C method of workflow??

Please, can you explain that moment in one place of documentation, or, maybe, make a picture of workflow (developing, testing, production) using tsuru..??

THANK YOU!

**Comment by fsouza** [comment]
Hi @dmitryck, thanks for raising this question.

tsuru provides an environment for running your application, with Docker nodes for hosting application code. We indeed has this flaw in our documentation, and there's an issue for improving our documentation regarding the architecture of a running cloud: #162. This topic has also been raised by another user/contributor in issue #560, but then we moved the discussion to something else.

I'm not sure I get the question right, but tsuru doesn't impose any _development_ workflow, but I can talk about our internal workflow, which is very similar to the case you described: 

In the local machine, developers will have only tsuru client installed, there's no other component running on a developer machine. Whenever he/she wants to deploy the application code to some environment, they will just invoke ``git push`` or ``tsuru app-deploy``.

For B and C, you can have one central tsuru API server managing multiple Docker pools:

![Multi pool tsuru arch](https://cloud.githubusercontent.com/assets/108725/7518094/4df167a6-f4af-11e4-8cb9-dfc428cfeab5.png)

And the developer can choose the pool they want to use in their application:

```
% tsuru pool-list
+-------+-----------------------+
| Team  | Pools                 |
+-------+-----------------------+
| admin | testingpool, prodpool |
+-------+-----------------------+
% tsuru app-create myapp-test python --pool testingpool
% tsuru app-create myapp-prod python --pool prodpool
```

For more details, see: http://docs.tsuru.io/en/master/using/application-pool.html.

The pool management has been redesigned and the working flow I've described below is landing in the next version of tsuru (to be launched later today).

I'm not sure this answer your question, so please us know if there's any other point you need clarification!

**Comment by dmitryck** [comment]
Thank you @fsouza very match!!
It's very useful information!!

But a have another question, seeing this picture:
If i have made TWO application (test and prod) with two different pools, i will have TWO GIT repository of my code too?? And no one central GIT control of my application code?

Is this right?:
1. at first, i GIT PUSH my TEST APP CODE on TESTINGPOOL, and testing
2. then, if testing app is correct, i must some how get it code in my PROD APP
3. and then i GIT PUSH my PROD APP on PRODPOOL
??

sorry if i say something wrong...)

Or there ALWAYS ONE GIT REPOSITORY of my app, created in tsuru, no matter if i testing it somewhere or not ..?
And deploy app on testingpool or prodpool is always a ONE deploy from one directory of app code, just with some different parameters.. ?

THANX!

**Comment by fsouza** [comment]
Hi @dmitryck! 

Yes, each tsuru app has one Git repository. In this case, you'd have two Git repositories, and you'd need to push the code to the testing app, check that it works, and then push the code to the prod app.

So, suppose that your code is in the directory "/Users/me/projects/awesomeapp", and you have two applications: "awesome-test" and "awesome-prod". Now think that you have just finished a new feature and wants to send it to production, but before you want to ensure that it works in the testing environment, the flow would be:

```shell
% pwd
/Users/me/projects/awesomeapp
% git push [awesome-test repository] master

[ensure that the feature is working in the testing environment]

% git push [awesome-prod repository] master
```

Please not that you do not need two pools for that, you could have both apps within a single pool.

As an alternative to the two ``git push`` calls, you could also use ``tsuru app-swap``:

```shell
% pwd
/Users/me/projects/awesomeapp
% git push [awesome-test repository] master

[ensure that the feature is working in the testing environment]

% tsuru app-swap awesome-test awesome-prod
```

**Comment by dmitryck** [comment]
@fsouza 
Thanx a lot!!

Now i need just to start your tsuru workflow, but i can't do it - always some troubles(
In proccess...)

PS. i think that tsuru one of the best of paas
and i want as soon as possible start working with it

**Comment by andrestc** [comment]
Hi @dmitryck, I'm closing this as the issue seems resolved. As pointed by @fsouza, we should work on #162, to improve our documentation on this subject.

Thanks and feel free to re-open/open a new issue if needed.
