### ISSUE TITLE
error in docker node "http://127.0.0.1:2375": persistent connection closed

### ISSUE THREAD

**Issue by haifengkao** [tsuru/tsuru#1194]
I am using tsuru/now script to install tsuru on an ubuntu 14.04 machine.
When I tried to push [the example](https://github.com/tsuru/basebuilder/tree/master/examples/python) to tsuru, I got the following error message: 
                                                                                                                         
> Counting objects: 6, done.
> Delta compression using up to 8 threads.
> Compressing objects: 100% (3/3), done.
> Writing objects: 100% (6/6), 654 bytes | 0 bytes/s, done.
> Total 6 (delta 0), reused 0 (delta 0)
> remote: error in docker node "http://127.0.0.1:2375": persistent connection closed
> To git@my_domain.com:hellopy.git
>  * [new branch]      master -> master

The installation command is 

>  ./run.bash --template server --host-ip my_ip_addr --host-name my_domain.com

I tried to reboot the machine several times, but the error persists. I got the same issue when I push nodejs or ruby repositories.

**Comment by fsouza** [comment]
Hi @haifengkao, thanks for reporting this. I've fixed this bug earlier today, everything should work fine in tomorrow's nightly packages. You can also try it building from source (running tsuru now again).

**Comment by haifengkao** [comment]
I have been running tsuru now for several times, but I still got 

> remote: error in docker node "http://127.0.0.1:2375": persistent connection closed

Is there a way to verify whether tsuru now really pulls the fixed version?

**Comment by fsouza** [comment]
@haifengkao how are you calling tsuru-now? Can you share your parameters?

**Comment by haifengkao** [comment]
run.bash --template server --host-ip 164.32.231.153 --host-name some.domain.com

**Comment by fsouza** [comment]
@haifengkao ah, just confirmed, our task that regenerates the nightly package has failed, so the package is still broken. Sorry about that :-(

I will let you know when we fix it.

If you prefer, you can download tsr from master:

```
% sudo apt-add-repository ppa:tsuru/golang
% sudo apt-get update
% sudo apt-get install golang
% echo 'export GOPATH=$HOME' >> $HOME/.bashrc
% source $HOME/.bashrc
% go get github.com/tsuru/tsuru/cmd/tsr
% sudo stop tsuru-server-api
% sudo sed -i "s;/usr/bin/tsr;$HOME/bin/tsr;" /etc/init/tsuru-server-api.conf
% sudo start tsuru-server-api
```

**Comment by fsouza** [comment]
@haifengkao we've regenerated all nightly packages, can you try again? Thanks!

**Comment by haifengkao** [comment]
Thanks, it works now. This kind of issue worries me. Should I use `run.bash --tsuru-pkg-stable` in the future to avoid the same issue?

**Comment by fsouza** [comment]
@haifengkao I'm glad it works now! Running ``--tsuru-pkg-stable`` is ideal, unless you're planning to test upcoming changes or willing to contribute to tsuru (in this case you'd install tsuru from source).

May I close this issue?

**Comment by haifengkao** [comment]
Thanks. Issue closed.
