### ISSUE TITLE
cmd/tsuru app-rebuild

### ISSUE THREAD

**Issue by jblancett** [tsuru/tsuru#1200]
For a number of possible reasons, it is sometimes necessary to rebuild an app's container image from the current platform.  For example, I have some apps that haven't had code changes in months while the platform they're on has changed quite a bit due to changes in the past few tsuru releases.  After the latest tsuru upgrade, some of these apps no longer function correctly, tsuru constantly tries to restart them.  My suspicion is tsuru_unit_agent reporting in an old way that the current tsuru doesn't understand, or something like that.  Pushing an insignificant code change does fix it because that forces the image to be rebuilt from current platform.  an app-rebuild command would prevent the need for pushing bogus commits
The process would be just like deploy, but use last pushed code

**Comment by jblancett** [comment]
Maybe there could even be a configurable amount of time where tsuru would automatically do this if the app image gets too old

**Comment by cezarsa** [comment]
I like this idea, we already considered something of the sort. One problem we have implementing this today is that we don't have the original application code used in git push or app-deploy. Our default hooks make sure the generated archive is removed and we also do not save the archive name.

Some things would have to change. One option is making the generated archive persistent and tsuru storing the last generated archive's name in its database. Another option would be creating a docker image importing from scratch containing only the application's code and pushing it docker registry. One possible advantage of latter is that using this image would remove the need for an external storage for archives.

**Comment by jblancett** [comment]
ahh yes I can see how that would be an issue.  if the app is deployed via app-deploy it does it even still use archive-server?

**Comment by cezarsa** [comment]
Running app-deploy is even worse on that matter, no archive is created on any external storage. Uploaded files are sent directly from tsuru server to a container based on the platform's image, when this container is commited it's already mixed with platform files.
