### ISSUE TITLE
App-deploy. Error in docker  node: Unable to find user

### ISSUE THREAD

**Issue by dmitryck** [tsuru/tsuru#1205]
Hello,
What it can be??

```
$ tsuru app-deploy --app appname .
Uploading files...Error: error in docker node "http://127.0.0.1:2375": API error (500):
Cannot start container 04a8a015f0638add383292a23fd5c6a49b802ab7b44cb9cdd821105831e86aea:
[8] System error: Unable to find user ubuntu
```

This user, ubuntu, in this case - user of what? why deploy process must find some user, named like this?

Because in my other deploys there were no errors...
I just create new app in new platform with new pool... and suddenly this error..

THANX!

**Comment by fsouza** [comment]
Hi @dmitryck, tsuru is looking for the "ubuntu" user inside the container created for building the application image. Which platform you're using? Did you create it? How did you install it?

**Comment by dmitryck** [comment]
@fsouza, ok... i got it! thank you...

i create platform with ruby 2.2.2 installed from official docker repository 
https://github.com/docker-library/ruby/blob/4ccabb5557ce2001aa1ae2a5f719340eb33c0383/2.2/Dockerfile
i created it by command tsuru-admin platform-add.. and params

and when run inside this new platform-container command:
```
cat /etc/passwd | grep ubuntu
```
there is no output - no user named ubuntu..!
so... i don't understand, for now.. how can i fix it

----
PS. and don't understand, what part of deploying process demands do some operations from this user ubuntu..  because, it seems, there is no configs or something like this, where ubuntu user is mentioned.. i thought that default is always root..
