### ISSUE TITLE
HTTPS routing with application-specific certificates

### ISSUE THREAD

**Issue by dcarley** [tsuru/tsuru#1206]
We'd like to serve applications over HTTPS with certificates that are specific to an individual application and can be managed by the users/teams that own the application. Something similar to "application SSL certificates" in Deis, but with multi-tenancy:

http://docs.deis.io/en/latest/using_deis/app-ssl/

This is a continuation of a conversation my colleague @actionjack started in the Gitter channel:

https://gitter.im/tsuru/tsuru?at=556c71d69f3a9b7b060a1fce

---

We think there are two sections of work to implement this:
1. Add support for an additional router that supports TLS+SNI and can be configured using an API
   
   It seems that the currently supported routers aren't suitable. Hipache supports a single TLS certificate but not SNI or dynamic configuration of certificates (hipache/hipache#129). Galeb doesn't support TLS and it looks like the underlying libraries XNIO (https://issues.jboss.org/browse/XNIO-227) and Undertow (https://issues.jboss.org/browse/XNIO-227) don't yet support SNI.
   
   We're thinking that [vulcand](https://docs.vulcand.io/) would be a good candidate. It is entirely API driven, supports SNI, and only requires one additional dependency (etcd). It shouldn't be too much work to implement the `router.Router` interface for this as an additional choice of router.
2. Add certificate support for applications
   
   This would probably depend on application CNAMEs and have a similar commands like `tsuru cert-add -a app …` and `tsuru cert-remove -a app …`. We'd need to add a notion that routers could optionally support certificate functionality (perhaps a method on `router.Router` that returns an error?). If supported by an application's chosen router then the certificate and key would be pushed to the router (maybe Tsuru would also store a copy?).

---

So, we were wondering:
1. Does this sound like a reasonable approach?
2. Would you be amenable to merging such changes?

**Comment by cezarsa** [comment]
That's a very nice approach. I definitely agree that we need a better router support and vuncand seems like a nice option. SNI support is specially useful. We would love to receive these contributions and merge these changes!
Some points about a router implementation for vulcand: I think it would be preferable to integrate with vulcand's HTTP API instead of directly interfacing with etcd.
Also, we could have a new interface called something like router.SecureRouter including only methods to add/remove certificates. API handlers for cert-{add/remove} would check if chosen route implements this interface and fail otherwise.

**Comment by dcarley** [comment]
Both of those points sound good.

vulcand has an [api package](http://godoc.org/github.com/mailgun/vulcand/api) that I think means we could do it all in Go without implementing an HTTP client. It'll bring in a lot of dependencies though. What would you prefer?

No promises as to how soon this will get implemented..

**Comment by cezarsa** [comment]
It's okay to depend on vulcand's api package, no problem adding one more dependency, we only need to remember adding it to Godeps.
You can take your time on it. We are kind of busy right now getting lean containers off the ground, but we may be able to start working on routers in the future. I'll make sure to ping you if we get to it though, so there's no risk of us working on the same thing.

**Comment by cezarsa** [comment]
Me and @fsouza are going to give it a shot today and tomorrow, not sure how far we'll get but we hope to get some basic support for vulcand working.

**Comment by dcarley** [comment]
Hold up, I have a branch with vulcand implementing the router interface. But the trays rely on an upstream pull request being merged. I'll push in a few hours, if you want to look?

**Comment by cezarsa** [comment]
Sure, we would love to take a look at it. Meanwhile, we're also working on #1209, things will break on your branch because of it but we can help fixing it.

**Comment by dcarley** [comment]
Here it is: https://github.com/tsuru/tsuru/compare/tsuru:master...dcarley:vulcand_router

**Comment by fsouza** [comment]
@dcarley thanks! We're testing it locally right now.

**Comment by cezarsa** [comment]
@dcarley We were able to successfully run your branch after changing the tests to use a etcd engine instead of memng. After your pull request (mailgun/vulcand#214) is merged upstream we can change it back.
Would you like to create a pull request for us to merge it and apply our changes on top of it? (Actually we can create it and merge it if you say it's okay)

**Comment by cezarsa** [comment]
Oh and thanks a lot for working on it! That was really nice work, it's working perfectly! As soon as it's merged we'll even update tsuru/now to use vulcand instead of hipache by default.

**Comment by dcarley** [comment]
I've rebased against #1209: https://github.com/tsuru/tsuru/compare/tsuru:master...dcarley:vulcand_router_net_url

Feel free to take those commits and tack some on the end to fix the memng problem. I'm not sure how to best handle that, whether you want to include etcd as a dependency for the tests?

Some random thoughts as I was doing this:

- As mentioned in one of the commits, I didn't use `router.Retrieve()` because I wasn't clear what it's purpose was. Does this matter?
- It might be useful to have some generic integration tests for everything that implements the `router.Router` interface because there are some inconsistencies or undefined behaviours, e.g. how to handle duplicate routes.
- It would be possible to get vulcand into an inconsistent state whereby it would refuse to add backends/routes because they already exist. I guess this might be the problem for other routers too? Does that matter?
- vulcand doesn't have any pretty "application not configured" and "application not responding" pages like Hipache does by default. Although there's a discussion in mailgun/vulcand#54 about how it might be possible with fallback routes and another backend.

**Comment by cezarsa** [comment]
Thanks a lot @dcarley I've just merged it. I'm adding etcd as a dependency in our CI servers right now. I don't think it's too big of a problem to depend on it, we already do that for MongoDB and Redis and there's the advantage that the code running on tests is the same tsuru will run in production. After memng is fixed and if running etcd proves to be too much of a hassle we can change the code to use it.

About your thoughts:

1. It's necessary for app-swap to work correctly. The way the code for app-swap code works isn't very straightforward, I'll take a look at simplifying it and making app-swap work.
2. I agree, I'll take a look at it.
3. I see this could happen if someone manually called vulcand api inserting entries with the same ID tsuru would use, I don't think that's a problem. Is there a situation where tsuru itself would cause this problem to happen?
4. I don't think that's too much of a problem, we can try some proposed solutions latter and maybe contribute back some lacking functionality.
5. Yep, we'll keep supporting hipache, it's our only router that works with websockets currently.

**Comment by dcarley** [comment]
> It's necessary for app-swap to work correctly. The way the code for app-swap code works isn't very straightforward, I'll take a look at simplifying it and making app-swap work.

I'm using `router.Store()` in `AddBackend()` and `router.Remove()` in `RemoveBackend()`, and I think the tests confirm that `Swap()` is doing the right thing. I'm just not using `router.Retrieve()` anywhere because it wasn't clear what the arguments were or why I shouldn't use the same private functions that are used to construct names.

> I see this could happen if someone manually called vulcand api inserting entries with the same ID tsuru would use, I don't think that's a problem. Is there a situation where tsuru itself would cause this problem to happen?

Probably not. I might be worrying for no reason.

Other points, don't worry and thanks!

I'm not sure that ae02a3b94753b3ad30bb4c1f2bdb47a2032e13cb is correct. From memory, although I should have said in the commit message, it only matches requests for `GET /`.

**Comment by cezarsa** [comment]
You're right, I just pushed 5803382e9ce77c0b40e3d1a49bd6066333d25d52 dropping the Path rule

**Comment by dcarley** [comment]
:+1:

**Comment by dcarley** [comment]
In hindsight, it might be better if the tests startup an instance of vulcand and send requests through it. Closer to integration testing. If you don't object and I get some spare time then I'll look into it.

**Comment by andrestc** [comment]
We have added support for configuring app TLS certificates and passing them to the router. Currently, only planB is integrated with tsuru api to store the certificates and terminate the TLS connections. [Release notes](https://github.com/tsuru/tsuru/commit/902633f3619c902f81bfc32532f2c1a999e1712e)

We support `certificate-set -a <app> -c <cname>`, `certificate-unset -a <app> -c <cname>` and `certificate-list -a <app>` and currently tsuru does not store any copy of the pub or private keys.

To enable TLS support in a router, it must implement the `router.TLSRouter` interface:

```
type TLSRouter interface {
	AddCertificate(cname, certificate, key string) error
	RemoveCertificate(cname string) error
	GetCertificate(cname string) (string, error)
}
```

This should be fairly easy to do for `vulcand` since it already supports setting certificates using its api.

Should we keep this issue untill all routers support TLS or create issues for each router that fits? cc @cezarsa @dcarley

**Comment by dcarley** [comment]
Sadly, I'm no longer using Tsuru.

I'm really glad for you and your users that you landed this feature though :tada:
