### ISSUE TITLE
Adding nodes should require a pool parameter

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#1208]
Now every node needs a pool metadata. Calling `docker-node-add` without a pool metadata should raise an error.
Another option is having a default pool name configured somewhere (tsuru.conf?) and this pool name will be used if none is provided.

**Comment by andrestc** [comment]
@cezarsa I believe we can close this issue since pool is a required parameter for [docker-node-add](https://github.com/tsuru/tsuru/blob/master/provision/docker/handlers.go#L249). Or do you think we should also support default pools for docker-node-add?

**Comment by cezarsa** [comment]
No need for a default pool I think, and as the validation is already in place we can close this.
