### ISSUE TITLE
Should router.AddRoute/RemoveRoute take net.URL?

### ISSUE THREAD

**Issue by dcarley** [tsuru/tsuru#1209]
The current signatures for `router.AddRoute` and `router.RemoveRoute` take an address as a `string`:
```go
type Router interface {
…
	AddRoute(name, address string) error
	RemoveRoute(name, address string) error
```
There are inconsistencies with how `address` is passed in by the various router tests:
- `routertest` uses `host:port`
- `hipache` uses `http://host:port`
- `galeb` uses both `host:port` and `http://host:port`

Whereas the `docker` provisioner, which is the only place that these methods are used outside of tests, always uses a URL of the form `http://host:port` ([reference](https://github.com/tsuru/tsuru/blob/0.11.1/provision/docker/docker.go#L106-L108))

Would it be preferable to change `address string` to `address net.URL` in order to remove some of this ambiguity and additional parsing?

**Comment by andrewsmedina** [comment]
I'm +1 to use `net.URL` instead string.

**Comment by dcarley** [comment]
Thanks!
