### ISSUE TITLE
unit removing status

### ISSUE THREAD

**Issue by jblancett** [tsuru/tsuru#1212]
When you remove units they sometimes take a few minutes to fully get removed.  If you do something else before they do, like say an app-restart, it brings up the number of units you had before the remove.  I think when a unit is being removed it's status should change to "removing" so that further commands ignore it, including app-info

**Comment by jblancett** [comment]
Another thought on this.  If number of expected units for an app were stored in the database, rather than just counting the number of active units, it would avoid this problem all together.

**Comment by fsouza** [comment]
At master unit-remove doesn't run in background anymore, and we ensure the application is locked during the entire process.

@jblancett do you think it's fine to close this issue?
