### ISSUE TITLE
Feature request / discussion: User permissions

### ISSUE THREAD

**Issue by dhilton** [tsuru/tsuru#1220]
We have a use case for being able to restrict create-user permission to a new class / role of user, we call a team lead(s). This role allows us to delegate admin from a central platform team, to team leads, restricting who can add a user to the platform and thus a team. 

Has there been any discussions / thoughts about this use case before or any prior art to adding such a model to the platform? We've looked at how the admin team works and understand the model employed here - if we were to implement such a model, what would be the preferences for how this might be done?

**Comment by dhilton** [comment]
Our current thinking is that option 2 gets us to a workable place quicker, but we note that option 3 is a longer term goal. We've looked at https://github.com/shavac/go.sec - specifically adding the ACL and RBAC mentioned there as it comes with a MongoDB engine, which makes integrating it with the Server application in Tsuru easier. This option 3 however, will require quite a change we reckon based on an initial view formed by reading the code of the client, admin client and the dashboard. 

Cloud Foundry for example implements a similar organisation, space, team and user model http://docs.pivotal.io/pivotalcf/concepts/roles.html 

The scenarios we see :

* TL installs the Tsuru client
* TL creates Users on Tsuru using the Tsuru client - one for each member of the team
* TL adds the new users to the correct Team
* TL will manually send login details to Users
* TL can remove Users if someone leaves the Team
* TL will need to monitor their own Quota this is not part of the scope of this story
* Normal Devs cannot allocate a Team to a Pool
* TL cannot allocate a Team to a Pool
* TL can call team-user-remove
* Normal Dev cannot call team-user-remove
* Normal Dev cannot add new Users
* Normal Dev cannot add Users to a Team
* Normal Dev cannot app-set-team-owner to change the team owner
* TL would like to unlock apps if they are locked - this is not in current scope

Where TL is a "Team lead" role. A team can have multiple team leads who are a subset of the team members. 

This type of change would allow us to operate a federated, self-service model across multiple parts of our organisation.

**Comment by andrewsmedina** [comment]
Thinking more about this issue I believe that we can solve it in a flexible way introducing roles and permissions.

An user can have more than one role, and a role can have one or more permissions. In this way "team leader" can be a "role".

What do you think about it?

**Comment by dhilton** [comment]
I think we'd love that kind of setup - but the worry is how long / large such an implementation might be and the casscading breaking changes in commandline tools and the dashboard. As long as that type of cross repo change is managed correctly, it's all good - I guess the only outstanding question is around how much of a priority this is for all parties. We'll have a chat internally see what we can do.

**Comment by andrewsmedina** [comment]
I believe that issue https://github.com/tsuru/tsuru/issues/1278 should fix this issue

**Comment by cezarsa** [comment]
A new authorization system will be introduced in tsuru 0.13.0 and should solve this issue. More details are available in http://docs.tsuru.io/en/master/managing/users-and-permissions.html
