### ISSUE TITLE
Dependencies & vendoring 

### ISSUE THREAD

**Issue by RichardKnop** [tsuru/tsuru#1221]
Use vendoring for dependencies. See:

https://groups.google.com/forum/#!msg/golang-dev/nMWoEAG55v8/iJGgur7W_SEJ

**Comment by andrewsmedina** [comment]
fixed by https://github.com/tsuru/tsuru/commit/eb6bf7be75f98610fe30d6ab3cc88cc1a661f11e

**Comment by RichardKnop** [comment]
Godeps does support vendoring now btw... so you can continue using godeps.

**Comment by fsouza** [comment]
@RichardKnop indeed, but it vendors unused packages and test files along with the relevant code. When running ``go test ./...``, we don't want to run test for our dependencies, so we just dropped it out.

An alternative solution would be to stop using ``go test ./...``, but we preferred to switch to govendor instead.

**Comment by RichardKnop** [comment]
@fsouza Ok, makes sense.

In my projects I usually have a Makefile and run tests like:

```make test```

See here: https://github.com/RichardKnop/machinery/blob/master/Makefile#L17

**Comment by andrewsmedina** [comment]
@RichardKnop we have a `make test`. But the test command runs `go test ./...`: https://github.com/tsuru/tsuru/blob/master/Makefile#L29
