### ISSUE TITLE
iaas: implement IaaS for Docker Machine

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1223]
Using Docker Machine as an IaaS, we would support any driver that is supported by Docker Machine. The interface would be something like:

```
% tsuru-admin docker-node-add iaas=docker-machine name=mydocker1 driver=digitalocean digitalocean-access-token=0ab77166d407f479c6701652cee3a46830fef88b8199722b87821621736ab2d4 
```

Besides the "iaas", all the other parameters would be the flags used in the docker-machine command. The exception is the "name", that is not a flag in docker-machine, but will be an option in docker-node-add.

Admins would be able to create templates as well, just like the CloudStack and EC2 iaas.

In the first moment, we're not going to drop the ec2 nor the cloudstack iaas. CloudStack isn't supported in Docker Machine yet, and we don't wanna break current user flows.

**Comment by andrestc** [comment]
We added support for the [dockermachine iaas](https://github.com/tsuru/tsuru/tree/master/iaas/dockermachine) and the reference documentation was added [here](https://github.com/tsuru/tsuru/commit/16ed9ffc2c15f4d55b30a51289aa0eb1a8f78bfb).

I think we can close this issue and wait for some feedback to further extend this iaas(there are probably more options we can support to let the user customize the docker engine). What do you think, @fsouza?

Once this get stable, we can create issues to implement our own iaas's using dockermachine drivers.

**Comment by fsouza** [comment]
![giphy](https://cloud.githubusercontent.com/assets/108725/19493950/dc6fac30-954a-11e6-9230-143705c6d670.gif)
