### ISSUE TITLE
docker-node-list don't list nodes properly

### ISSUE THREAD

**Issue by tarsisazevedo** [tsuru/tsuru#1224]
When I run a `docker-node-add params...` tsuru says it was added successfully but if I run `docker-node-list` immediately it don't show my node.

**Comment by fsouza** [comment]
I'm going to work on this issue. I thought about the following statuses:

- pending: when the node is being created (i.e.: bs is not running yet) 
- error: when the bs creation task fails
- waiting: when the bs container is successfully created and the host is ready for running containers
