### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by RichardKnop** [tsuru/tsuru#1230]
Has anybody thought about API versioning?

I noticed there is at least one breaking change in REST API between 0.11.1 and 0.11.2.

Endpoint for adding teams to a pool has changed.

I suggest APIs should be stable for a major version, versioned (probably in path, something like /api/v0/, api/v1). Deprecated endpoints should only be removed in a major new release.

Is there any plan to version APIs?

**Comment by andrewsmedina** [comment]
@RichardKnop I believe that we will start to using API versioning in 1.0.

**Comment by RichardKnop** [comment]
@andrewsmedina Thanks
