### ISSUE TITLE
API to bind/unbind service returns invalid JSON

### ISSUE THREAD

**Issue by RichardKnop** [tsuru/tsuru#1233]
`curl -H 'Authorization: Bearer sometoken' -XDELETE https://my-tsuru-environment.com/services/instances/testteam4-flask-app-db/testteam4-flask-app`

```
{"Message":"---- Unsetting 5 environment variables ----\n"}
{"Message":"---- Setting 1 new environment variables ----\n"}
{"Message":"\nInstance \"testteam4-flask-app-db\" is not bound to the app \"testteam4-flask-app\" anymore.\n"}
```

The same problem when binding a service.

`curl -H 'Authorization: Bearer sometoken' -XPUT https://my-tsuru-environment.com/services/instances/testteam4-flask-app-db/testteam4-flask-app`

```
{"Message":"---- Setting 6 new environment variables ----\n"}
{"Message":"\nInstance \"testteam4-flask-app-db\" is now bound to the app \"testteam4-flask-app\".\n"}
{"Message":"The following environment variables are available for use in your app:\n\n"}
{"Message":"- PG_PASSWORD\n"}
{"Message":"- PG_HOST\n"}
{"Message":"- PG_PORT\n"}
{"Message":"- PG_USER\n"}
{"Message":"- PG_DATABASE\n"}
{"Message":"- TSURU_SERVICES\n"}
```

Is it a valid JSON?

I am trying to bind and unbind a service to/from app using the REST API.

My Ruby client throws JSON::ParserError when trying to parse the response above.

**Comment by cezarsa** [comment]
These API calls return a list of `\n` separated JSON chunks, so before parsing them you'd have to split the response by `\n` and parse each chunk individually. This same protocol is used by all blocking API calls to stream responses back to client. (logs, deploy, app restart...)

Each json chunk can have only two possible fields, `Message` and `Error`. If `Error` is not empty the stream will end and the operation should be considered unsuccessful.

I can see this as a not ideal for third-party clients, as in the case of service bind, getting the list of exported fields from this stream would not be pretty. We're open to having a different kind of response depending on the request's Accept header. Maybe we could support something like `application/json-stream` and `application/json`.

**Comment by andrewsmedina** [comment]
@RichardKnop there are some libs that parse json from a stream. https://github.com/brianmario/yajl-ruby is one of them.
