### ISSUE TITLE
Proposal: Introduction of service-app binding metadata

### ISSUE THREAD

**Issue by gciotta** [tsuru/tsuru#1237]
Following a discussion with @fsouza, I'd like to propose the introduction of metadata in the app↔service-instance binding.

Let me explain it with a fictional use case. Let's imagine that we're building a simple service which takes care of health-checking some applications via HTTP. An instance of this service will be made available in tsuru under the name healthcheck. At this point, We'd like to connect an app to it so it gets health-checked. The app is called "fooapp". We could do it this way:

``` bash
$ tsuru service-bind healthcheck -a fooapp -d check-url=/check check-frequency=15
```

The above syntax introduces a way to pass additional information to the service instance in case this is needed for the two parties to cooperate. The information should then travel to the service provisioning API:

```
POST /resources/myinstance/bind-app HTTP/1.1
...
app-host=myapp.cloud.tsuru.io&meta-check-url=/check&meta-check-frequency=15
```

In the above example, the metadata is prefixed with the `meta` prefix to avoid clashes with internal tsuru paramers (now or in the future).

With this feature we will probably be able to handle natively some of the [use cases](https://github.com/tsuru/healthcheck-as-a-service#adding-a-new-url-to-be-monitored) currently handled with tsuru client plugins.

**Comment by tarsisazevedo** [comment]
:+1:
