### ISSUE TITLE
Potential timeouts while doing platform-add/platform-update

### ISSUE THREAD

**Issue by keymon** [tsuru/tsuru#1239]
Issue description
-----------------------

With the current implementation of the commands to add platforms, `tsuru-admin platform-add` and `tsuru-admin platform-remove`, the process can easily fail due timeouts in Load Balancers or intermediate proxies.

The reason is that tsuru API server will just stream the output of the execution of the `docker build`,  without using websockets or implementing any kind of heartbeat. 

The `docker build` is a process that very likely will hang for a while in some operation without sending any output (e.g. package db update), triggering random timeouts.

You can test this easily with a dockerfile like this:

```
from    ubuntu:14.04
run sleep 120
```

Current solution in other endpoints
--------------------------------------------

Currently  `tsuru-api` implements some short of heartbeat for some endpoints, specifically the `/apps/{appname}/repository/clone`. Basically writes a "Please wait..." every 30 seconds. 

In more detail:
 * API Controller is in this file: https://github.com/tsuru/tsuru/blob/0.11.2/api/server.go
    * For the case of [`/apps/{appname}/repository/clone`](https://github.com/tsuru/tsuru/blob/0.11.2/api/server.go#L166), it calls  [this deploy() function](https://github.com/tsuru/tsuru/blob/0.11.2/api/deploy.go#L23) which [adds wrapper on the HTTP connection](https://github.com/tsuru/tsuru/blob/0.11.2/api/deploy.go#L75) using [io/keepalive_writer.go:NewKeepAliveWriter](https://github.com/tsuru/tsuru/blob/0.11.2/io/keepalive_writer.go#L26)
 * there are two endpoints for the platform, [add](https://github.com/tsuru/tsuru/blob/0.11.2/api/server.go#L158) and [update](https://github.com/tsuru/tsuru/blob/0.11.2/api/server.go#L159), which call [api/platform.go:platformAdd](https://github.com/tsuru/tsuru/blob/0.11.2/api/platform.go#L15) and [api/platform.go:platformUpdate](https://github.com/tsuru/tsuru/blob/0.11.2/api/platform.go#L30)

Potential solutions
-----------------------

We propose several solutions:

 1.  We could add the same logic in the platform add/update related endpoints to avoid timeouts. It it just add a pair or lines of code (we might send a PR soon).

 2. But using websockets would be a better approach for this problem. Specially as tsuru is adding websockets in several places (see https://github.com/tsuru/tsuru/commit/8c75d1d05996f3f0f28c40ec83333a838b87c15a). This would require more changes.

 3. Additionally to implement websockets, it would be better an implementation that runs this kind of taks completely asynchronously, triggering a batch job in background which can be monitor with the current connection or a new one later. But to implement that it is needed a big re-architecture of the Tsuru API service, add some job management logic, etc...

Which kind of approach do you prefer for your project?

**Comment by cezarsa** [comment]
We're being conservative about websockets usage for now. Using them only when data has to be sent the other way around.
Doing 1 is fine. We're moving some parts of tsuru architecture to 3 (using monsterqueue) but I don't think adding this extra layer is necessary for platform-add/update as getting logs back from the async task to stream back to the client would be tricky.

**Comment by keymon** [comment]
Thank you for your feedback. 

As the related PR #1240 has been merged, feel free to close this issue.
