### ISSUE TITLE
tsuru.yaml: add more hooks

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1241]
We could add more hooks to tsuru.yaml, so users could run commands before installing SO dependencies or before installing platform dependencies. Here is an example (don't take it too serious, who would want Java in a Python applicaton?):

```
% cat tsuru.yaml
hooks:
  before-so-dependencies:
    - echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
    - echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
  before-platform-dependencies:
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib/
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so /usr/lib/
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib/
% cat requirements.apt
oracle-java7-installer
python-dev
libjpeg-dev
libfreetype6-dev
zlib1g-dev
% cat requirements.txt
PIL
```

The names of the hooks would probably change.

**Comment by leandrosouza** [comment]
+1
I've the same idea/problem

**Comment by fsouza** [comment]
I'm deliberately merging #1146 in this one. We could have two more hooks:

- rollback (when user invokes app-deploy-rollback)
- "deploy aborted" (when the deployment is aborted, because of a healthcheck failure - invoked only if build hooks has been invoked)

**Comment by lucasgomide** [comment]
One more suggest..

- deploy successful

**Comment by igorfernandes** [comment]
+1

I've the same problem
