### ISSUE TITLE
Inconsistencies in the tsuru API when an object is not found

### ISSUE THREAD

**Issue by dhilton** [tsuru/tsuru#1242]
The tsuru API is a little bit inconsistent when returning the state of an object, if it doesn't exist.

For example, when you try to remove an application that doesn't exist, the API returns a 404.

When you try to remove a user that doesn't exist, the API returns a 500.

My personal preference is that when you try to delete something that doesn't exist it should return a 404, but at least be consistent if possible. Happy to help with a PR if that makes sense.

**Comment by fsouza** [comment]
Hi @dhilton, we should handle 404 in user-remove as well. Please feel free to send the pull request.

Thank you!

**Comment by fsouza** [comment]
@dhilton thanks for reporting and fixing the user-remove inconsistency.

Have you seen this kind of inconsistency in other endpoints as well?

**Comment by dhilton** [comment]
I'm having a look now - we're running a suite of performance tests which create and delete lots of teams, apps and such like - will see if we have any other such issues.

**Comment by fsouza** [comment]
I think we're done with all not founds. I'm closing this issue, @dhilton please feel free to reopen it if you find status code inconsistencies in the API.

Thanks!
