### ISSUE TITLE
cmd/tsuru-admin: improve error message when pool is not found

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1245]
For example:

```
% tsuru-admin pool-teams-add pool-1 team-1
Error: not found
```

What's not found? I know it's the pool, because it doesn't check whether the provided teams exist, but we should provide a better error message.

**Comment by tarsisazevedo** [comment]
closed at tsuru/tsuru-admin@692c404b33ac67f0b3f268ec18e648a4059b2960
