### ISSUE TITLE
Support for redis sentinel and cluster on redis backends

### ISSUE THREAD

**Issue by morpheu** [tsuru/tsuru#1247]
Actually, tsuru api only support connection to a single instance of redis master. It would be nice to have a sentinel based connection to a redis cluster.

**Comment by cezarsa** [comment]
Closed by commits ff2810fc7efdacc6236e637c876ad46a782ff0c0
1063d2872c1ee3b4184a0984c3bd99355e054ac3
effc104801ed95fd08bb9115f3f385b755f48745
71adcc3ed3f1d7f52fe5f4e7358f48d7843cd671
