### ISSUE TITLE
FeatureRequest: Return actual service status message

### ISSUE THREAD

**Issue by mtekel** [tsuru/tsuru#1248]
When you currently ask for status of a service, you will only get 'up', 'down', 'pending' and 'not implemented for this service', as defined here: https://github.com/tsuru/tsuru/blob/master/service/endpoint.go#L201 . (Speaking of which, documentation should probably be updated with addition of 404 response possibility: http://docs.tsuru.io/en/latest/services/api.html#checking-the-status-of-an-instance)

It would be nice if tsuru would also return body of the response it got from service. This can contain some additional information about the service status, e.g. in case of elasticsearch:
```
{
  "cluster_name" : "elasticsearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0
}
```
This is quite useful from the user standpoint, as you could see what's really going on (very useful when e.g. there are some issues with the service).

**Comment by fsouza** [comment]
Just pushed that. Now when the service API returns 200, we read the body and display it to the user.
