### ISSUE TITLE
Add platform from Docker image (instead of Dockerfile)

### ISSUE THREAD

**Issue by dcarley** [tsuru/tsuru#1252]
The process of adding/building platforms on a new environment takes quite a long time.

What do you think of the ability to add a platform from an existing image in a public (or private) Docker registry? It would allow you to use [automated builds](https://docs.docker.com/docker-hub/builds/) to perform the build once, saving time and providing better consistency across multiple installs/environments.

**Comment by keymon** [comment]
An alternative is just create a simple Dockerfile which just refers to the desired image. It can be hosted in a github repo or a gist.
