### ISSUE TITLE
router/vulcand: app-remove leaves CNAMEs behind

### ISSUE THREAD

**Issue by dcarley** [tsuru/tsuru#1254]
If you're using the vulcand router and you remove an app that has a CNAME, the CNAME isn't cleaned up and it prevents an app of the same name from being recreated again.

It looks like the implementation of `RemoveRoute()` does this for hipache. But I'm wondering:

- should this be part of the spec for the `router.Router` interface?
- should `UnsetCName()` be used instead? If so, who by?
- would it be possible to test either using the new generic tests? (which are really nice, btw)

You can reproduce this with [tsuru-bootstrap](https://github.com/tsuru/tsuru-bootstrap) and `TSURU_BOOTSTRAP=nightly` (version warnings omitted from output):
```
vagrant@vagrant-ubuntu-trusty-64:~$ tsuru cname-add -a tsuru-dashboard tsuru-dashboard.192.168.50.4.xip.io
cname successfully defined.
vagrant@vagrant-ubuntu-trusty-64:~$ tsuru app-remove -a tsuru-dashboard
Are you sure you want to remove app "tsuru-dashboard"? (y/n) y
App "tsuru-dashboard" successfully removed!
vagrant@vagrant-ubuntu-trusty-64:~$ tsuru app-create tsuru-dashboard python
Error: tsuru failed to create the app "tsuru-dashboard": Backend already exists
```

**Comment by cezarsa** [comment]
Thanks for reporting! The RemoveBackend method is now removing all cnames associated to this backend. This should be the correct implementation and I've added a generic test to make sure all routers behave like this.
