### ISSUE TITLE
Issue: Able to register docker node twice

### ISSUE THREAD

**Issue by mtekel** [tsuru/tsuru#1258]
When trying to register nodes, duplicity check is based on the URI. But it is possible to have two different URIs for the same server, e.g. https://1.1.0.1:4243 and https://1.1.00.1:4243. Tsuru thinks these are two different nodes. But they are not. When doing any network operations, both URIs resolve into same IP. This confuses e.g. container re-balance, which thinking that these are different nodes, places 2x more containers on the affected node:

```
gds@ubuntu:~/workspace/alphagov/docker-cluster$ tsuru-admin docker-node-add --register address=http://10.129.0.168:4243 pool=default </dev/null
Error: Node address shouldn't repeat


gds@ubuntu:~/workspace/alphagov/docker-cluster$ tsuru-admin docker-node-add --register address=http://10.129.00.168:4243 pool=default </dev/null
Node successfully registered.
gds@ubuntu:~/workspace/alphagov/docker-cluster$ tsuru-admin docker-node-list 
+---------------------------+---------+--------+----------------------------------+
| Address                   | IaaS ID | Status | Metadata                         |
+---------------------------+---------+--------+----------------------------------+
| http://10.129.0.168:4243  |         | ready  | LastSuccess=2015-08-20T14:26:36Z |
|                           |         |        | pool=default                     |
+---------------------------+---------+--------+----------------------------------+
| http://10.129.0.241:4243  |         | ready  | LastSuccess=2015-08-20T14:26:36Z |
|                           |         |        | pool=default                     |
+---------------------------+---------+--------+----------------------------------+
| http://10.129.0.251:4243  |         | ready  | LastSuccess=2015-08-20T14:26:36Z |
|                           |         |        | pool=default                     |
+---------------------------+---------+--------+----------------------------------+
| http://10.129.00.168:4243 |         | ready  | LastSuccess=2015-08-20T14:26:36Z |
|                           |         |        | pool=default                     |
+---------------------------+---------+--------+----------------------------------+
gds@ubuntu:~/workspace/alphagov/docker-cluster$ tsuru-admin container
container-move        containers-move       containers-rebalance  
gds@ubuntu:~/workspace/alphagov/docker-cluster$ tsuru-admin containers-rebalance 
Are you sure you want to rebalance containers? (y/n) y
Rebalancing 3 units...
Moving unit ead9a4e4267f1e5e37fe935dfd2e0f115010507ee3731a60b190d5c34c5e7e8f for "postgresapi" from 10.129.0.241...
Moving unit e1be8628d1c5b5d0a754e129912bb8b6fb3f7e374bb2c83d45b128e2fb376b7f for "dashboard" from 10.129.0.168...
Moving unit 7a74097be2107ab2cb9c4932ea92e70ab0534c3beb995f516d87625dfc77e52f for "elasticsearchapi" from 10.129.0.168...
```

I think tsuru should do some more strict duplicity, or even URI validity check. Or perhaps have its own mechanism to identify the nodes, to be able to discover if they are unique or duplicate.

**Comment by fsouza** [comment]
I don't think that this is a bug, nor that we should handle this scenario.

In order to safely fix this issue, we'd need to have something like an agent running in the node, and both the node and the API would agree on the host ID.

Just normalizing the IP address doesn't fix the issue, because multiple names could point to the same node. Just resolving the name doesn't fix the issue either, because the node could have a Docker daemon bound to multiple network interfaces.

@mtekel could you give more context on how you faced this issue in the first moment? Thanks!

**Comment by mtekel** [comment]
Hi,

I realize this is not too important. We had some scripts that would automatically add new nodes to tsuru. We then realized that if we change naming, then we could end up with some nodes being added twice. This is also problem with SSH - it keeps node IDs based on hostname, not on whatever the node resolves to. So when you ssh to the same node under new name, it asks you to verify identity, as it has never seen that node before (it doesn't check/realize that it is the same ssh daemon it connects to).

In the end, agent (perhaps running in a big sibling container) should clearly identify the node, but I realize this is not a priority now.
