### ISSUE TITLE
Incorrect JSON response from unit-add(?)

### ISSUE THREAD

**Issue by jpprins1** [tsuru/tsuru#1264]
unit-add responds with:
{"Message":"\n---- Starting 1 new unit ----\n"}
{"Message":" ---\u003e Started unit a2d711baac...\n"}
{"Message":"\n---- Binding and checking 1 new units ----\n"}
{"Message":" ---\u003e Bound and checked unit a2d711baac\n"}
{"Message":"\n---- Adding routes to 1 new units ----\n"}
{"Message":" ---\u003e Added route to unit a2d711baac\n"}

Which probably should be an array:
[{"Message":"\n---- Starting 1 new unit ----\n"},
{"Message":" ---\u003e Started unit a2d711baac...\n"},
{"Message":"\n---- Binding and checking 1 new units ----\n"},
{"Message":" ---\u003e Bound and checked unit a2d711baac\n"},
{"Message":"\n---- Adding routes to 1 new units ----\n"},
{"Message":" ---\u003e Added route to unit a2d711baac\n"}]

Javascript Eval did not like it, so I needed a workaround..

**Comment by fsouza** [comment]
@jpprins1 this is actually a JSON stream, and not an array. You'd need to capture the streaming and eval the object every time you get a full object.

You'd need to find a way of handling JSON streaming with AngularJS :S

**Comment by andrewsmedina** [comment]
@jpprins1 you can use oboejs to parse json stream with angular: http://oboejs.com/examples

**Comment by jpprins1** [comment]
Ah didn't know about JSON streams ;) Thanks for the explanation and I'll try oboejs!
