### ISSUE TITLE
unit-delete: API delete with body 

### ISSUE THREAD

**Issue by jpprins1** [tsuru/tsuru#1265]
AngularJS does not allow you to send and body with an HTTP delete. (Think this could be the case with more frameworks)

Would it be possible to also allow the number of units to be specified via a querystring parameter?
For example: "/apps/:app_name/units?number=1"

**Comment by fsouza** [comment]
Hi @jpprins1, we can definitely make this adjustment in the API. Thanks for reporting!

**Comment by jpprins1** [comment]
Ok, great!!

**Comment by fsouza** [comment]
@jpprins1 latest release of tsuru already take this on the querystring:

```
% curl -XDELETE -H "Authorization: Bearer ${TSURU_TOKEN}" ${TSURU_TARGET}/apps/myapp/units?units=1&process=web
```

We're no longer sending anything in the body for DELETE requests.
