### ISSUE TITLE
Do not always restart when inject an environment variable

### ISSUE THREAD

**Issue by emerleite** [tsuru/tsuru#1271]
Should be a way to inject an environment variable without restart the application. For example, if your application can deal with new variables without restart, it avoid destroy and recreate all units again.

One possible solution is to have an option in tsuru.yml to prevent those restarts.

**Comment by fsouza** [comment]
We could have a flag in env-set and env-unset, for example:

```
% tsuru env-set -a myapp NAME=VALUE --no-restart
% tsuru env-unset -a myapp OLDNAME=OLDVALUE --no-restart
% tsuru app-deploy -a myapp .
```

**Comment by guestisp** [comment]
+1 for a flag.

**Comment by emerleite** [comment]
:+1:
