### ISSUE TITLE
Client 0.17.1 copies the symlink instead of the linked file

### ISSUE THREAD

**Issue by cirocavani** [tsuru/tsuru#1273]
I have a symlink to a file in another folder out of deploy image. Using 'tsuru app-deploy', the image created had a 'local' copy of that file.

With 0.17.1, the behavior has changed to copy only the link (not the file), breaking deployment.

**Comment by tarsisazevedo** [comment]
It's a side effect of this commit tsuru/tsuru-client@5febbbffcb684981a5fb8c084fa13ad69e17664e 
Before that, tsuru client used to create hard link instead of symlink.

I think we can add `--follow-link` flag in `tsuru app-deploy`  to follow symlink.
