### ISSUE TITLE
Example of configuring tsuru server for many sites

### ISSUE THREAD

**Issue by dmitryck** [tsuru/tsuru#1274]
Hello! I have a question

1. A have three domain names - for example aaa.com, bbb.com, ccc.com
2. A have installed tsuru-server-api server and other components on my host
3. A have DNS records, wich bind this domain names to my tsuru host IP
4. A have three tsuru app - aaa, bbb, ccc.. ready to running..

so..
What and where a must configuring in a tsuru server for this sites worked?
aaa application - for aaa.com, bbb for bbb.com and ccc for ccc.com

hipache.conf? tsuru.conf? or other?
is there any example of this - one tsuru server/host and many public sites?

Thanx!

**Comment by andrewsmedina** [comment]
Hi @dmitryck you can add a cname record in you dns for your three domains  with hipache address as value of these cname's.

After that you should use the tsuru command: `tsuru cname-add` to define the app cname:

    tsuru cname-add <cname> -a <appname>

**Comment by cezarsa** [comment]
Another option is having three entries in the `routers` entry in your tsuru.conf file. Something like:
```
routers:
  aaa-router:
    type: hipache
    domain: aaa.com
  bbb-router:
    type: hipache
    domain: bbb.com
...
```
As @andrewsmedina said you'll need DNS entries pointing *.aaa.com, *.bbb.com to the IP address of your hipache server.

When creating a new application you'll then have to select a plan with the chosen router.

The same thing applies if you choose to use vulcand instead of hipache.

**Comment by dmitryck** [comment]
thanx @andrewsmedina and @cezarsa !! i'll try soon hoq it works

and another 2 question
1. tsuru cname-add <cname> -a <appname> - this command make some some config file at fact somewere in tsuru server?

2. when a make change in tsuru.conf and add a "routers" i need to restart tsuru-server-api...
so... when i want to add a new site, example ddd.com - a can't add it without restarting and stoping three other working sites aaa.com, bbb.com and ccc.com? 

adding a new site it's always restart?

**Comment by andrewsmedina** [comment]
@dmitryck when you add a cname via "tsuru cname-add", tsuru store this info in the MongoDB and add this new "cname" conf in the hipache (via Redis). So, it does not need restarts.

About add new router backends, you need to change the tsuru.conf nad restart the tsuru api. The routers (hipache) don't needed to be restarted. The tsuru api restart does not affect the running applications.

**Comment by dmitryck** [comment]
@andrewsmedina 
I see..

Thank you!!

**Comment by andrewsmedina** [comment]
@dmitryck can we close this issue?
