### ISSUE TITLE
Scoped API token for registering Docker nodes

### ISSUE THREAD

**Issue by dcarley** [tsuru/tsuru#1275]
We've been experimenting with using [CoreOS](https://coreos.com/) for Docker nodes because they're easier to maintain than Ubuntu VMs. We currently have our config management identifying new nodes within an environment and registering them with Tsuru API.

Ideally we'd like new nodes to register themselves with the API, but we're reluctant to give them an API token that has full admin access. Is there anything that we can do to achieve this short of implementing #1220?

**Comment by andrewsmedina** [comment]
I believe that issue https://github.com/tsuru/tsuru/issues/1278 should fix this issue
