### ISSUE TITLE
inside app Curl 127.0.0.1:8888 is response, outside appaddr.xip.io not

### ISSUE THREAD

**Issue by dmitryck** [tsuru/tsuru#1276]
docker ps at server

```
7cc1d8545c36  tsuru/app-rails1:v16    "tsuru_unit_agent ht   About a minute ago 
Up About a minute   0.0.0.0:32843->8888/tcp   rails1-40ffb5027e7c251c24ce
```

curl 127.0.0.1:8888 inside app container

```
...
<h1>Welcome aboard</h1>
<h2>You&rsquo;re riding Ruby on Rails!</h2>
...
```

outside url http rails1.addr.xip.io not:

```
Application Not Responding
Please try again in a few moments.
```

other apps, that i have - response well
only this rails app is not!

netstat in this app container:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5555          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:5556          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      -               
tcp6       0      0 ::1:8888                :::*                    LISTEN      -   
```

what can be a problem
Thank you!

**Comment by andrewsmedina** [comment]
@dmitryck your app should be bound to 0.0.0.0 to be accessed outside of the container.

**Comment by dmitryck** [comment]
@andrewsmedina 
Yes, 0.0.0.0:8888 and 127.0.0.1:8888 inside app container are curl'ing well.. RubyOnRails welcome page code on both...

**Comment by andrewsmedina** [comment]
@dmitryck can you paste your Procfile ?

**Comment by dmitryck** [comment]
@andrewsmedina 
web: bundle exec rails server -p 8888

is it correct? docker port  always connect to =>8888

**Comment by andrewsmedina** [comment]
@dmitryck your Procfile is ok. can you try to access the application externally by <host-ip>:<port> ? Another think that you can try is to use the "tsuru-admin app-routes-rebuild" command.

**Comment by dmitryck** [comment]
@andrewsmedina, thank you..
 
"access the application externally by : ?" - what does it mean? "by : ?"

tsuru-admin app-routes-rebuild - "Nothing to do, routes already correct"

**Comment by andrewsmedina** [comment]
Sorry about that. What I mean is to you try to access externally your application by `<hostip>:<port>`.  You can see these info using `app-info` command.

**Comment by dmitryck** [comment]
@andrewsmedina

from host machine (from inside), access externally is:
curl: (52) Empty reply from server 

yes.. emty reply..... 
and other apps, that working well from outside, are response well on a specific port from inside of host machine

**Comment by dmitryck** [comment]
@andrewsmedia

and.. from app-info..

Units [web]: 1
+------------+---------+-----------+-------+------------+
| Unit       | State   | Host      | Port  | IP         |
+------------+---------+-----------+-------+------------+
| 43fa35d554 | started | 127.0.0.1 | 32774 | 172.17.0.7 |
+------------+---------+-----------+-------+------------+

i don't understand what is the IP mean - last column...

a login on a host machine, where is the docker and tsuru api server
run
docker ps
see all app containers
and curl
0.0.0.0:PORT .. by each app
right?

and the app that not response outside are - curl: (52) Empty reply from server 
but strange, that they are response from inside of a container, so that they running inside is 100%

**Comment by dmitryck** [comment]
@andrewsmedina 

i understood what was a problem..

for sinatra in code:
```
set :bind, '0.0.0.0'
set :port, 8888
```

for rails in Procfile:
```
web: bundle exec rails s -b 0.0.0.0 -p 8888
```

suppose, the app by it self was not listening 0.0.0.0 and not bind it to app.. or something...

but why curl 0.0.0.0:8888 inside app container are working well before?
and.. in tsuru docs in ruby on rails app deploy section, there is no -b 0.0.0.0 instruction..
maybe in my rails configuration something wrong?

**Comment by andrewsmedina** [comment]
@dmitryck in the docs there is no `-b 0.0.0.0` the there is `-e production`. When the `-e production` is defined `rails server` binds the application to `0.0.0.0`

**Comment by andrewsmedina** [comment]
hi @dmitryck can you close this issue?
