### ISSUE TITLE
tsuru new authorization system

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#1278]
The goal is to change the authorization system to be more flexible based on `users`, `permissions` and `roles`.
An user can have more than one role, and a role can have one or more permissions.

Use cases
=========

These are examples of roles that the new authorization system should support:

admin
-----

* can do eveything
* can create roles
* can add and remove permissions in all roles
* can add roles in users

cloud manager
-------------

* can create pools
* can add nodes to pools
* can remove nodes
* can't remove users
* can't remove users from teams
* cant remove apps from nodes
* can add 'pool managers' to a specific pool

team leader in team 'x'
-----------------------

* can create users
* can create team 'x'
* can add and remove users (team membems) in team 'x'
* can unlock team 'x' apps
* can create team 'x' apps

team member in team 'x'
-----------------------

* can deploy in the team 'x' apps
* can see team 'x' apps
* can't remove team 'x' apps
* can see members of team 'x'
* can't add new users to team 'x'
* can't remove users from team 'x'
* can't create team 'x' apps

pool manager for pool 'z'
-------------------------

* can rebalance pool 'z'
* can move unit between pool 'z' nodes 
* can see all apps in pool 'z'
* can't remove apps in pool 'z'
* can add units in pool 'z' apps

service manager
---------------

* can create new services
* can view service instances related with its services
* allow and disallow teams to use its services

read only developer in app 'y
-----------------------------

* see app 'y'
* view app 'y' logs, envs
* can't set and unset envs in app 'y'
* can''t make deploys in app 'y'

How to check permissions
========================

```
func restart(w http.ResponseWriter, r *http.Request, t auth.Token) error {
	...
	permissions.Check(t, "app.update.restart", []ContextIntance{
		permissions.App{Name: appName},
		permissions.Team{Teams: u.Teams()},
		permissions.Pool{Name: instance.Pool},
	})
	...
}
```

Adding permissions
==================

```
package permissions
...
r := register{}
r.addWithContextCB("app", []ContextType{App, Team, Pool}, func(r *register) {
    r.addCB("update", func(r *register) {
        r.addCB("env", func(r *register) {
            r.add("set", "unset")
        })
    })
})
```

Client commands
===============

```
tsuru role-add <role name> <context type>
tsuru role-permission-add <role name> <permission name>
tsuru user-role-add <role name> <context value>
```

e.g.
```
tsuru role-add team-member team
tsuru role-permission-add team-member "app.deploy" "app.update"
tsuru user-role-add myuser team-member teamA
```

**Comment by leandrosouza** [comment]
nice
+1

**Comment by keymon** [comment]
cool

**Comment by cezarsa** [comment]
A new authorization system will be introduced in tsuru 0.13.0 and should solve this issue. More details are available in http://docs.tsuru.io/en/master/managing/users-and-permissions.html

**Comment by fsouza** [comment]
woot.

**Comment by tarsisazevedo** [comment]
:clap: :clap: :clap: :clap: :clap: :clap:
