### ISSUE TITLE
containers-move: moving stopped container leaves wrong port 0 on router

### ISSUE THREAD

**Issue by morpheu** [tsuru/tsuru#1280]
When issue a "containers-move" from one machine to another, if any stopped containers are involved on process, tsuru will try to add port 0 on router for newly created container.

**Comment by flaviamissi** [comment]
Is the expected behavior not to add any ports on the new container?

**Comment by fsouza** [comment]
Docker will report a HostPort on stopped containers only if we're using the tsuru port allocator (which isn't the default option), so I suggest that we do not call AddRoute when the HostPort is 0.

@flaviamissi do you wanna work on that?

**Comment by flaviamissi** [comment]
Depends on the priority @fsouza, if it's something that has to be delivered quick then I can't work on it, otherwise yeah I can take it (:

**Comment by fsouza** [comment]
@flaviamissi this is not urgent, as it doesn't compromise the behavior of tsuru, so please take your time! We'll let you know if someone else start working on this issue.

**Comment by flaviamissi** [comment]
Awesome, thanks! :D

**Comment by fsouza** [comment]
@flaviamissi thanks for working on that :-)
