### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by leandrosouza** [tsuru/tsuru#1283]
I have been trying use the metrics to my apps via dashboard but without success.
Can you have more details how I implements this feature ?

I'm have been trying use statsd with elastisearch and logstash with elasticsearch 

My statsd conf
{
  port: 8125,
  backends: [ "statsd-elasticsearch-backend" ],
  debug: true,
  elasticsearch: {
     port:          9200,
     host:          "localhost",
     path:          "/",
     indexPrefix:   ".measure-tsuru",
     //indexTimestamp: "year",  //for index statsd-2015
     //indexTimestamp: "month", //for index statsd-2015.01
     indexTimestamp: "day",     //for index statsd-2015.01.01
     countType:     "counter",
     timerType:     "timer",
     timerDataType: "timer_data",
     gaugeDataType: "gauge",
     formatter:     "default_format"
  }
}

statsd log
0 Sep 20:14:07 - DEBUG: metrics:
20 Sep 20:14:07 - DEBUG: {"counters":{"statsd.bad_lines_seen":0,"statsd.packets_received":0,"statsd.metrics_received":0},"gauges":{"statsd.timestamp_lag":0},"timers":{},"timer_counters":{},"sets":{},"counter_rates":{"statsd.bad_lines_seen":0,"statsd.packets_received":0,"statsd.metrics_received":0},"timer_data":{},"pctThreshold":[90],"statsd_metrics":{"processing_time":0}}
20 Sep 20:14:07 - DEBUG: ES payload:
20 Sep 20:14:07 - DEBUG: {"index":{"_index":".measure-tsuru-2015.09.20","_type":"counter"}}
{"ns":"statsd","grp":"bad_lines_seen","tgt":"","act":"","val":"0","@timestamp":"1442790847000"}
{"index":{"_index":".measure-tsuru-2015.09.20","_type":"counter"}}
{"ns":"statsd","grp":"packets_received","tgt":"","act":"","val":"0","@timestamp":"1442790847000"}
{"index":{"_index":".measure-tsuru-2015.09.20","_type":"counter"}}
{"ns":"statsd","grp":"metrics_received","tgt":"","act":"","val":"0","@timestamp":"1442790847000"}
{"index":{"_index":".measure-tsuru-2015.09.20","_type":"gauge"}}
{"ns":"statsd","grp":"timestamp_lag","tgt":"","act":"","val":"0","@timestamp":"1442790847000"}

Both configurations result the same erros in dashboard

File "/home/application/current/metrics/backend.py", line 48, in process
for bucket in data["aggregations"]["range"]["buckets"][0]["date"]["buckets"]:
KeyError: 'aggregations'

**Comment by leandrosouza** [comment]
More logs from statsd

{"index":{"_index":".measure-tsuru-2015.09.20","_type":"gauge"}}
{"ns":"tsuru","grp":"dashboard","tgt":"cc6ebdbcf9a7cpu_max","act":"","val":"0","@timestamp":"1442791573000"}
{"index":{"_index":".measure-tsuru-2015.09.20","_type":"gauge"}}
{"ns":"tsuru","grp":"dashboard","tgt":"cc6ebdbcf9a7mem_max","act":"","val":"0","@timestamp":"1442791573000"}
{"index":{"_index":".measure-tsuru-2015.09.20","_type":"gauge"}}
{"ns":"tsuru","grp":"dashboard","tgt":"cc6ebdbcf9a7mem_pct_max","act":"","val":"0","@timestamp":"1442791573000"}

**Comment by andrewsmedina** [comment]
@leandrosouza  I update the docs about how to use metrics with tsuru: http://docs.tsuru.io/en/master/advanced_topics/metrics.html

We recommend to use Logstash + Elasticsearch in the docs has a example of Logstash config.

**Comment by leandrosouza** [comment]
Do you know if it works in tsuru version 0.11.x ?

**Comment by leandrosouza** [comment]
I'm trying to use logstash but when I send the metrics return this error. 

{:timestamp=>"2015-09-23T03:08:33.524000+0000", :message=>"Trouble parsing json", :source=>"message", :raw=>"tsuru.dashboard.1fc97a7412a0.net.connections:17|g", :exception=>#<LogStash::Json::ParserError: Unrecognized token 'tsuru': was expecting 'null', 'true', 'false' or NaN
 at [Source: [B@11d706d9; line: 1, column: 7]>, :level=>:warn}


My logstash conf:

input {
    udp {
        port => 1984
    }
}

filter {
    json {
        source => "message"
    }

    if "_jsonparsefailure" in [tags] {
        mutate {
            add_field => {
                client => "error"
                metric => "metric_error"
            }
        }
    }
}

output {
    elasticsearch {
        protocol => "http"
        host => "localhost"
        index => ".measure-%{client}-%{+YYYY.MM.dd}"
        index_type => "%{metric}"
    }
}

**Comment by andrewsmedina** [comment]
This doc is for tsurud 0.12+. How you are sending metrics to logstash?

**Comment by leandrosouza** [comment]
I am usging the environments in each unit
STATSD_HOST=myhost and STATSD_PORT=1984

**Comment by andrewsmedina** [comment]
You don't need StatsD to send metrics to Logstash. You just need Logstash and Elasticsearch. To enable it you should define these enviroment variables in your app: `LOGSTASH_HOST` and `LOGSTASH_PORT`.

ps: The metrics sent by units using Circus was removed from tsuru since 0.12.x.

**Comment by leandrosouza** [comment]
I put the variables but the metrics never send to logstash.
LOGSTASH_HOST and LOGSTASH_PORT

Looking the circus code I saw the options backend and the default backend is statsd. 
When I set the new variable like logstash  ( TSURU_METRICS_BACKEND=logstash ) the metrics was sent to logstash hosts.

Now the graphs still not renders, because the data is empty.

It's a result of get from dashboard to render the graphs
{"max": "4.60", "data": [], "min": "0.00"}

**Comment by andrewsmedina** [comment]
@leandrosouza what version of dashboard are you using? try to use the version from version.

**Comment by leandrosouza** [comment]
I am using the master version

**Comment by andrewsmedina** [comment]
The way that tsuru handle metrics has changed, tsuru 1.0 has no `StatsD` support.
