### ISSUE TITLE
database:logdb-url retention on capped collections

### ISSUE THREAD

**Issue by vmalaga** [tsuru/tsuru#1292]
Hello.

Our developers want to have more logs of their apps, but on apps with a lot of activity, the mongodb collections capped parameters defined on logCappedInfo of 5000 documents is not enough

https://github.com/tsuru/tsuru/blob/1f5310a7400c3991c1b8f68885a3bb5b35b5f680/db/storage.go#L161

now that we can configure an external database to allocate app logs,
is possible to modify this limit ? have you planned this ? or must I look for other soluttions

regards

**Comment by andrewsmedina** [comment]
+1 to make capped size configurable
