### ISSUE TITLE
run tsuru app with a specific docker options

### ISSUE THREAD

**Issue by dmitryck** [tsuru/tsuru#1294]
Hi
So, is it possible now in tsuru?
maybe from command line, maybe add some app starting hook.. anyway

in example, if i want start app with host volume mounting to it
like -v in docker

```
docker run  -v host/fs:/app/fs ...
```

or with any other docker parameters, that i want for current app?
thanx!

**Comment by andrewsmedina** [comment]
@dmitryck tsuru abstracts some docker options. By example, you can limit memory and cpu using plans and related with mount there is a conf to sharefs in units: https://github.com/tsuru/tsuru/pull/734

**Comment by dmitryck** [comment]
@andrewsmedina 
ok, thank you!!
that options are enough for me.. !
and any docker start options in future tsuru versions, would be?

ps. tsuru docs are contains not all possibilities for config file, i guest... because sharedfs - i didn't see that section

**Comment by dmitryck** [comment]
@andrewsmedina 
and i can mount only one volume?
in docker i can use several times -v

in tsuru sharedfs - only once?

**Comment by vmalaga** [comment]
on our tsuru installation we have solve this limitation with the bind mount, keeping in mind that is a cluster and need nfs or other cluster filesystem to share it with all node member on the cluster

if you have this config on tsuru.conf and /mnt/tsuru is a nfs volumen
```
sharedfs:
    hostdir: /mnt/tsuru
    mountpoint: /sharedvol
    app-isolation: true
```
inside your apps you will have on **/sharedvol** the contents of  **/mnt/tsuru/appname**
and if you want the contents of other nfs or filesystem for this app, could mount it with bind

*mount -o bind /mnt/vol1 /mnt/tsuru/appname/vol1* inside your app */sharedvol/vol1*
