### ISSUE TITLE
tsuru on ARM (Scaleway)

### ISSUE THREAD

**Issue by sfcgeorge** [tsuru/tsuru#1295]
[Scaleway](https://www.scaleway.com) offers dedicated ARM servers for just €2.99/month which is crazy cheap and pretty powerful with quad cores and 2GB RAM. It seems like an ideal platform to build a resilient cloud and Tsuru might be a good tool to use.

It looks like Tsuru doesn't currently run on ARM so this is my :+1: for that to hopefully become possible.

**Comment by fsouza** [comment]
@sfcgeorge thanks for opening this issue.

What exactly doesn't work? Have you tried it?

**Comment by sfcgeorge** [comment]
From the install docs "Ubuntu Server 14.04 LTS 64-bit machine. This is currently the supported environment for tsuru". Scaleway does support Ubuntu Server 14.04 but it's 32bit ARM, I think this causes several problems.

First I tried Tsuru Now:
`curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash`
The error I got was:
`E: Unable to locate package linux-image-extra-3.2.34-30`
I believe this is because Scaleway builds their own kernel. I used [their tool](https://community.scaleway.com/t/obtaining-headers/897) to obtain headers but apt isn't aware that the headers now exist so it still doesn't work.

Next I tried installing everything manually, starting with Gandalf as per the docs:
```
sudo apt-get update
sudo apt-get install curl python-software-properties
sudo apt-add-repository ppa:tsuru/ppa -y
sudo apt-get update
sudo apt-get install gandalf-server
```
Failed with error:
`E: Unable to locate package gandalf-server`

I'm not experienced with Linux but I guess when it says "unable to locate package" it means specifically an armhf package.

**Comment by hugobrilhante** [comment]
I had the same problem. 

I tried the following steps:

`sudo apt-get update`
`sudo apt-get install curl python-software-properties`
`sudo apt-add-repository ppa:tsuru/ppa -y`
`sudo apt-get update`

I get the stack:
``` bash
W: Failed to fetch http://ppa.launchpad.net/tsuru/ppa/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found                                                                                                

W: Failed to fetch http://ppa.launchpad.net/tsuru/ppa/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
I try to run:

`sudo apt-get install gandalf-server`

Failed with error:
```bash
E: Unable to locate package gandalf-server
````

**Comment by hugobrilhante** [comment]
I had the same problem. 

I tried the following steps:

`sudo apt-get update`
`sudo apt-get install curl python-software-properties`
`sudo apt-add-repository ppa:tsuru/ppa -y`
`sudo apt-get update`

I get the stack:
``` bash
W: Failed to fetch http://ppa.launchpad.net/tsuru/ppa/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found                                                                                                

W: Failed to fetch http://ppa.launchpad.net/tsuru/ppa/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
I try to run:

`sudo apt-get install gandalf-server`

Failed with error:
```bash
E: Unable to locate package gandalf-server
````

**Comment by wpjunior** [comment]
Some tsuru componentes are publishing in docker hub with amd64 and arm architectures, but
