### ISSUE TITLE
Avoid service instance name collision considering the service type internally

### ISSUE THREAD

**Issue by dfleury** [tsuru/tsuru#1299]
Sometimes you could need to create two different services which can has semantically the same name.
Suppose you have a mysql and mongodb services. In both, the database name will be the service instance name. Then you run something like this:
```
> tsuru service-add mysql umbrella_raccoon
> tsuru service-add mongodb umbrella_raccoon
Error: instance name already exists.
```

What I'm proposing is the ability to distinguish the service instances by the type. With this, we'll be able to create instances with more meaningful names without repetition of the obvious (like have a mysql database named umbrella_mysql_raccoon or similar).

Nowadays, we already have enough information through the `service-info` command to distinguish each service by type as we can see below:
```
Service instances: 2
+---------+--------------------------+
| Service | Instance                 |
+---------+--------------------------+
| mysql   | umbrella_mysql_raccoon   |
| mongodb | umbrella_mongodb_raccoon |
+---------+--------------------------+
```

**Comment by andrewsmedina** [comment]
This issue isn't easy. This issue isn't easy. This change will affect all service operations.
