### ISSUE TITLE
cmd/tsuru: app-info should display the unit id in the same size as the hostname

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1317]
Currently, we display 10 chars in the app-info output, but Docker cuts 12 chars in the hostname, which is used for identifying the unit in the log, for example.

This request comes from a user who is scripting tsuru client, using ``tsuru app-info`` output as input for ``tsuru app-log -u``.

Using 12 chars instead of 10 solves the problem.

**Comment by raulgbrmf** [comment]
Issue fixed by commit 7e7f368
