### ISSUE TITLE
tsuru local app development i.e. dec - prod parity?

### ISSUE THREAD

**Issue by devekko** [tsuru/tsuru#1321]
hi

is there any supported way of using tsuru for local app development?

somehow leveraging the platforms / buildpacks etc on a local dev machine, i.e. my laptop

I can't see how tsuru would do this, I guess I want a Vagrant version/option of/for Tsuru that uses the Vagrant sync folders feature to allow direct access to the code of an app 

allowing changes to code, that didn't require a git push

but with a buildpacks, slugs and containers workflow I cant see how that is possible

looking at Heroku, I see they have the Heroku Local and the Heroku Docker, but that's not quite it either

Heroku Local is a command-line tool to run Procfile-backed apps. It is installed automatically as part of the Heroku Toolbelt. Heroku Local reads configuration variables from a .env file. Heroku Local makes use of Forego to accomplish its tasks.

https://devcenter.heroku.com/articles/heroku-local

This article describes how to use the heroku-docker Toolbelt plugin and Docker to do local development of apps that you deploy to Heroku. The Toolbelt plugin makes it easy to set up and maintain development environments for different apps. By running your app in a Cedar-like container inside Docker on your local machine, you get good dev-prod parity.
Docker Compose also makes it very easy to run containers for add-ons used by your app so that you don’t have to install and maintain services on your development machine.
heroku-docker can also be used to deploy your code to apps on Heroku, by creating Heroku slugs from the container images created locally with Docker.

https://devcenter.heroku.com/articles/docker

**Comment by devekko** [comment]
looking into this further

Heroku is using Docker for local app development 

it has Heroku Docker 


Today, Heroku is releasing a beta version of heroku docker:release. This new CLI functionality leverages the increasing availability of Docker on the desktop, and combines the benefits of local container development with the proven Heroku Cedar container runtime. Using Docker and heroku docker:release, developers can run apps in containers similar to the Heroku runtime and get high fidelity dev/prod parity, whether they’re developing on OS X, Linux or Windows.
https://blog.heroku.com/archives/2015/5/5/introducing_heroku_docker_release_build_deploy_heroku_apps_with_docker

https://github.com/heroku/docker-ruby
https://github.com/heroku?utf8=%E2%9C%93&query=docker

**Comment by devekko** [comment]
hi

I came across Devstep, haven't tried a Devstep to Tsuru spike yet.. but, it might be easier/better, than Heroku Docker

http://fgrehm.viewdocs.io/devstep/
http://niccolox.org/devstep-for-local-docker-buildpack-development/

**Comment by cezarsa** [comment]
Thank you for sharing your thoughts on this. One of the new features we're currently working is allowing docker images to be deployed directly to tsuru. This is the first step towards having a similar workflow to heroku docker. You can track issue #1314 for updates.

After this step is done it'll theoretically be possible to deploy a Dockerfile generated by `heroku docker:init` to tsuru. We still have to test this further and see if any issues will arise but it would be great to achieve this level of compatibility with heroku.

**Comment by devekko** [comment]
cool

need to try to push from Devstep apps to Tsuru

my next experiment was to add the Buildpacks listed in Tsuru into Devstep 

personally, unsure if I want to be tied to Dockerfiles

I think LXC/LXD and other container strategies have advantages and even the mighty Docker doesnt do configuration management on machines, networking, databases etc... Ansible etc aren't going away

anyway, speculative for sure
