### ISSUE TITLE
php apps deploy hangs on remote: text and crashes dashboard

### ISSUE THREAD

**Issue by devekko** [tsuru/tsuru#1323]
depploying a php app crashes tsuru it seems

niccolox@trusty:~/Projects/tsuru-apps/wordpress|master
⇒  git push git@tsuru1.dev.io:blog.git master
Counting objects: 1412, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1388/1388), done.
Writing objects: 100% (1412/1412), 6.90 MiB | 3.19 MiB/s, done.
Total 1412 (delta 114), reused 0 (delta 0)
remote: text

hangs and the dashboard dies and I cant connect

devekko@tsuru1:~$ sudo service mongodb status 
mongodb stop/waiting

devekko@tsuru1:~$ sudo service mongodb start
mongodb start/running, process 29393

  tsuru app-info --app blog                                      
Error: Failed to connect to tsuru server (http://156.4.198.19:8080), it's probably down.

**Comment by andrewsmedina** [comment]
Can you look at the tsurud upstart log and paste de error here? the log should be in /var/log/upstart/tsuru-server-api.log

**Comment by devekko** [comment]
am wondering if its mongodb locale issues
http://stackoverflow.com/questions/19668570/mongodb-localefacet-s-create-c-locale-name-not-valid
devekko@tsuru1:~$ locale -a
C
C.UTF-8
POSIX
en_US.utf8



Done reading config file: /etc/tsuru/tsuru.conf

WARNING: Setting "docker:segregate" is not necessary anymore, this is the default behavior from now on.
WARNING: Using "redis-queue:*" is deprecated. Please change your tsuru.conf to use "pubsub:*" options. See http://docs.tsuru.io/en/latest/reference/config.html#pubsub for more details.
Using mongodb database "tsurudb" from the server "127.0.0.1:27017".
Registered router "hipache": hipache router "tsuru1.devekko.io" with redis at "127.0.0.1:6379".
Default router is "hipache".
Using "gandalf" repository manager.
Using "docker" provisioner.
could not create queue instance, please check queue:mongo-url and queue:mongo-database config entries. error: no reachable servers
Opening config file: /etc/tsuru/tsuru.conf
Done reading config file: /etc/tsuru/tsuru.conf
WARNING: Setting "docker:segregate" is not necessary anymore, this is the default behavior from now on.
WARNING: Using "redis-queue:*" is deprecated. Please change your tsuru.conf to use "pubsub:*" options. See http://docs.tsuru.io/en/latest/reference/config.html#pubsub for more details.
Using mongodb database "tsurudb" from the server "127.0.0.1:27017".
Registered router "hipache": hipache router "tsuru1.devekko.io" with redis at "127.0.0.1:6379".
Default router is "hipache".
Using "gandalf" repository manager.
Using "docker" provisioner.
could not create queue instance, please check queue:mongo-url and queue:mongo-database config entries. error: no reachable servers

listen: "0.0.0.0:8080"
host: http://142.4.198.19:8080
debug: true
admin-team: admin

database:
  url: 127.0.0.1:27017
  name: tsurudb

git:
  unit-repo: /home/application/current
  api-server: http://127.0.0.1:8000

auth:
  user-registration: true
  scheme: native
routers:
  hipache:
    type: hipache
    domain: tsuru1.devekko.io
    redis-server: 127.0.0.1:6379
repo-manager: gandalf
provisioner: docker
queue:
  mongo-url: 127.0.0.1:27017
  mongo-database: tsuru_queue
redis-queue:
  host: localhost
  port: 6379
docker:
  bs:
    image: tsuru/bs
    reporter-interval: 10
    socket: /var/run/docker.sock
  collection: docker_containers
  port-allocator: tsuru
  registry: 127.0.0.1:5000
  repository-namespace: tsuru
  router: hipache
  deploy-cmd: /var/lib/tsuru/deploy
  segregate: true
  cluster:
    storage: mongodb
    mongo-url: 127.0.0.1:27017
    mongo-database: dockercluster
  run-cmd:
    bin: /var/lib/tsuru/start
    port: "8888"
  ssh:
    add-key-cmd: /var/lib/tsuru/add-key
    user: ubuntu

**Comment by andrewsmedina** [comment]
Looks like that something is restarting the process. A possible reason can be that your machine is `out of memory`. Can you try again and see the syslog (/var/log/syslog) to check if is this problem?

**Comment by devekko** [comment]
logs are big

-rw-r-----  1 root root   2.6G Dec 10 18:31 tsuru-server-api.log
-rw-r-----  1 root root   1.5G Dec 10 10:13 tsuru-server-api.log.save

devekko@tsuru1:/var/log/upstart$ sudo grep -r 'memory'
docker.log:WARN[0002] Your kernel does not support swap memory limit. 
docker.log:WARN[0000] Your kernel does not support swap memory limit. 
docker.log:WARN[0006] Your kernel does not support swap memory limit. 
docker.log:WARN[0003] Your kernel does not support swap memory limit. 
docker.log:WARN[0001] Your kernel does not support swap memory limit. 
docker.log:WARN[0003] Your kernel does not support swap memory limit. 
docker.log:WARN[0001] Your kernel does not support swap memory limit. 
docker.log:WARN[0008] Your kernel does not support swap memory limit.

**Comment by devekko** [comment]
trying this

https://gist.github.com/steakknife/9094991
https://github.com/docker/docker/issues/4250

devekko@tsuru1:/var/log/upstart$ # enable swap resource limiting
devekko@tsuru1:/var/log/upstart$ sudo sed -i 's/\(GRUB_CMDLINE_LINUX_DEFAULT="\)"/\1cgroup_enable=memory swapaccount=1"/' /etc/default/grub 
devekko@tsuru1:/var/log/upstart$ sudo update-grub
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-3.19.0-39-generic
Found initrd image: /boot/initrd.img-3.19.0-39-generic
Found linux image: /boot/vmlinuz-3.19.0-25-generic
Found initrd image: /boot/initrd.img-3.19.0-25-generic
Found memtest86+ image: /memtest86+.elf
Found memtest86+ image: /memtest86+.bin
done
devekko@tsuru1:/var/log/upstart$ sudo reboot

changed swappiness to 10

no joy

going to rebuild and make sure I didnt mess up the client - server config somehow

**Comment by devekko** [comment]
is it this?
https://github.com/docker/docker/issues/847

the VM is 8gb ram

**Comment by devekko** [comment]
closing, not sure how I got the error

I did create the VM by cloning one with 512mb of RAM and maybe somehow it hadn't reset available RAM in Proxmox? not sure

but closed.. thanks
