### ISSUE TITLE
tsuru-admin 0.12.1 not working with platforms

### ISSUE THREAD

**Issue by vmalaga** [tsuru/tsuru#1329]
Hi

I just have update to tsuru-admin 0.12.1 and I can't manage any platform because always return the same error, 

```
root@tsurudev:~# tsuru-admin platform-add python_new -d https://github.com/tsuru/platforms/raw/master/python/Dockerfile
Error: Dockerfile is required.

root@tsurudev:~/platforms/python# tsuru-admin platform-update python -d /root/platforms/python/Dockerfile
Error: Dockerfile is required.
```
this happend with platform-add and platform-update and with local or remote Dockerfile

**Comment by vmalaga** [comment]
I'm sorry, but after the apt-get update tsurud not been restarted after doing now works

**Comment by fsouza** [comment]
Hi @vmalaga, I'm glad you figured it out.

Maybe we should improve docs on this subject :-( The Dockerfile's in the platforms repository are not supposed to be provided as a parameter to platform-add/platform-update, they're used for automatically building images at Docker Hub (maybe we should support the same workflow that ``docker build`` does).

So, if you want to use the Python platform, with no changes, you can grab the prebuilt image by simply running (if you're with tsurud 0.13.x _and_ tsuru-admin 0.12.x):

```
% tsuru-admin platform-add python
```

If you're using tsurud 0.12.x and tsuru-admin 0.11.x, you can run (notice that I'm still using basebuilder here):

```
% tsuru-admin platform-add python -d https://raw.githubusercontent.com/tsuru/basebuilder/master/python/Dockerfile
```

Now, if you're with tsuru-admin 0.12.x and tsurud 0.12.x, you won't be able to run platform-add nor platform-update. We kept the new API compatible with older tsuru-admin, but we didn't keep tsuru-admin compatible with older API.

Sorry about the mess.

**Comment by vmalaga** [comment]
@fsouza ok thanks
