### ISSUE TITLE
tsuru team-create returns "You don't have permission to do this action"

### ISSUE THREAD

**Issue by pritchardjonathan** [tsuru/tsuru#1330]
Hi,

Following the installation instructions and got so far as 

Page: http://docs.tsuru.io/en/latest/installing/api.html
Command: $ tsuru team-create admin

but get "You don't have permission to do this action" response.

This is using tsuru 0.13.0, tsuru-client 0.18.1, gandalf 0.7.3 on Ubuntu 14.04.3 LTS

tsuru.conf looks like this:
```
listen: "0.0.0.0:8080"
debug: true
host: http://localhost:8080 # This port must be the same as in the "listen" conf
admin-team: admin
auth:
    user-registration: true
    scheme: native
database:
    url: localhost:27017
    name: tsurudb
pubsub:
    redis-host: localhost
    redis-port: 6379
queue:
    mongo-url: localhost:27017
    mongo-database: queuedb
repo-manager: gandalf
git:
    api-server: http://localhost:8000
provisioner: docker
docker:
    router: hipache
    collection: docker_containers
    repository-namespace: tsuru
    deploy-cmd: /var/lib/tsuru/deploy
    cluster:
        storage: mongodb
        mongo-url: localhost:27017
        mongo-database: cluster
    run-cmd:
        bin: /var/lib/tsuru/start
        port: "8888"
    ssh:
        add-key-cmd: /var/lib/tsuru/add-key
        user: ubuntu
routers:
    hipache:
        type: hipache
        domain: 127.0.0.1.xip.io
        redis-server: localhost:6379
```
tsuru-server-api log looks like this:

Opening config file: /etc/tsuru/tsuru.conf
Done reading config file: /etc/tsuru/tsuru.conf
Using mongodb database "tsurudb" from the server "localhost:27017".
Registered router "hipache": hipache router "127.0.0.1.xip.io" with redis at "localhost:6379".
Default router is "hipache".
Using "gandalf" repository manager.
Using "docker" provisioner.
Docker provisioner reports the following nodes:
Using "native" auth scheme.
Checking components status:
    WARNING: "docker" is not working: fail - error - no nodes available for running containers
    Components checked.
tsuru HTTP server listening at 0.0.0.0:8080...
2015-12-19T21:38:28.57153086Z GET /auth/scheme 200 in 0.505466ms
2015-12-19T21:38:31.994527996Z POST /users/xxx@xxx.com/tokens 401 in 140.771553ms
2015-12-19T21:38:34.50635684Z GET /auth/scheme 200 in 0.274772ms
2015-12-19T21:38:37.862156967Z POST /users/xxx@xxx.com/tokens 200 in 141.977725ms
2015-12-19T21:38:49.823606179Z POST /teams 403 in 1.030705ms
2015-12-19T21:43:47.086191731Z GET /teams 204 in 1.218195ms
2015-12-19T21:44:01.780187208Z GET /users 200 in 1.423269ms
2015-12-19T21:44:14.668976253Z POST /teams 403 in 1.232845ms
2015-12-19T21:44:22.44287107Z GET /auth/scheme 200 in 0.233789ms
2015-12-19T21:44:25.771280697Z POST /users/xxx@xxx.com/tokens 200 in 141.018245ms
2015-12-19T21:44:28.366807507Z POST /teams 403 in 1.044028ms
2015-12-19T21:47:42.056761917Z GET /permissions 403 in 1.105300ms
2015-12-19T21:47:50.478613188Z GET /permissions 403 in 1.074695ms

git .bash_profile looks like this:

export ARCHIVE_SERVER_READ=http://127.0.0.1:3232 ARCHIVE_SERVER_WRITE=http://127.0.0.1:3131

This is my first time installing and it's all on a single machine. Apologies if the answer is really obvious.

**Comment by andrewsmedina** [comment]
Since 0.13.0 it is need to add a role with the `team.create` permission to a user can create teams. You can create a role with this permission and add it as default role:

```
tsuru role-default-add --user-create team-creator
```

You can see more about permissions and default role here: http://docs.tsuru.io/en/0.13.0/managing/users-and-permissions.html?highlight=permissions#default-roles

**Comment by flaviamissi** [comment]
@andrewsmedina should add a note in the docs in that case?

**Comment by andrewsmedina** [comment]
@flaviamissi in the documentation there are some mentions about it. You can see them in the user and permissions page [0] and in the release notes [1].

[0] - https://docs.tsuru.io/0.13/managing/users-and-permissions.html
[1] - https://docs.tsuru.io/0.13/releases/tsurud/0.13.0.html#backward-incompatible-changes-action-needed

**Comment by pritchardjonathan** [comment]
Thanks!
