### ISSUE TITLE
What is the difference between OpenShift origin and tsuru

### ISSUE THREAD

**Issue by joao-parana** [tsuru/tsuru#1332]
I have a basic question.

What is the difference between **OpenShift origin** and **tsuru**

* Both are PaaS solutions.
* Both are written in GO language.
* Both are Open Source

[https://github.com/openshift/origin](https://github.com/openshift/origin)

**Comment by andrewsmedina** [comment]
I'm not a OpenShift 3 user, so I will describe somethings that differs tsuru from the another PaaS's.

Two things makes tsuru different, your main objective and the fact that tsuru is more two years being used in production by Globo.com and another companies like Hotel Urbano, JusBrasil, QDQmedia.

The tsuru main objective is to be a tool to make the deploy simple and fast, shorting the time to a application takes to be production ready with scalability and high availability. 

Thinking in this objective tsuru has some features to make this objective possible:

* healthcheck that enables deploy with zero downtime
* application swap to enable blue/green deployment
* auto healing for tsuru nodes and application units
* auto scale (by service)
* administration tools
* powerfull role based access mechanism for managing users and permissions
