### ISSUE TITLE
unit-add should start stopped units

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru#1347]
When I stop an app and then add a unit to it, the old units stay stopped, while the new one is started. This lets the app in an inconsistent state (some requests hit the new unit, but others get HTTP 503 when trying to reach one of the stopped units).

Example:

```
$ tsuru app-info -a test
...
Units [web]: 1
+--------------+---------+-----------+-------+------------+
| Unit         | State   | Host      | Port  | IP         |
+--------------+---------+-----------+-------+------------+
| ad0c9727a7db | stopped | 127.0.0.1 | 32799 | 172.17.0.4 |
+--------------+---------+-----------+-------+------------+

$ tsuru unit-add 1 -a test

---- Starting 1 new unit [web: 1] ----
 ---> Started unit be4a3bb684 [web]

---- Binding and checking 1 new unit ----
 ---> Bound and checked unit be4a3bb684 [web]

---- Adding routes to new units ----
 ---> Added route to unit be4a3bb684 [web]

$ tsuru app-info -a test
...
Units [web]: 2
+--------------+----------+-----------+-------+------------+
| Unit         | State    | Host      | Port  | IP         |
+--------------+----------+-----------+-------+------------+
| ad0c9727a7db | stopped  | 127.0.0.1 | 32799 | 172.17.0.4 |
| be4a3bb68474 | starting | 127.0.0.1 | 32800 | 172.17.0.4 |
+--------------+----------+-----------+-------+------------+
```

**Comment by tarsisazevedo** [comment]
I think tsuru should disallow to add new units in stopped apps, what do you think?

**Comment by fsouza** [comment]
Or maybe add units in stopped state?

**Comment by ggarnier** [comment]
I see 3 possible solutions here:

1 - disallow to add new units when current units aren't started (stopped or asleep, for example)
2 - add new units with the same state of the old units
3 - start all units after adding

I think the third one makes more sense

**Comment by cezarsa** [comment]
Adding units without starting them would cause their healthcheck and startup hooks to never be executed. Possible errors would only show up later when the user tries to start the units. On a normal workflow these errors would happen during the unit-add command making the command abort and rollback the added units.

I'm voting for either 1 or 3. The most explicity solution seems to be 1 and if the user wants the behavior of 3 it's as simple as `tsuru app-start && tsuru unit-add`.

**Comment by tarsisazevedo** [comment]
I agree @cezarsa, but we can mix two options, 1 and 3, in one feature.
We can extend `unit-add` with a flag to start stopped units, what do you think?

**Comment by ggarnier** [comment]
I like the 1st option because it's the least surprising one - you don't do anything the user didn't ask for.
