### ISSUE TITLE
Update crane docs and command `crane template` to include `team` entry

### ISSUE THREAD

**Issue by wiliamsouza** [tsuru/tsuru#1357]
Trying to add `mysqlapi` service I get the following error:

```
crane create service.yaml
Error: You must provide a team responsible for this service in the manifest file.
```

If it is a required information to add services it would be good to have it added by default by `crane template` and service.yml on projects be updated to include it.

**Comment by tarsisazevedo** [comment]
@wiliamsouza you can [update your crane from source](https://tsuru-crane.readthedocs.org/en/latest/#build-from-source-linux-and-mac-os-x) now and it will works!
I'll release crane packages as soon as possible!
Thanks for reporting! \o/
