### ISSUE TITLE
Missing command in Using » Application Deployment

### ISSUE THREAD

**Issue by myhro** [tsuru/tsuru#1376]
Hi,

The [last line of `deployment.rst`][1] contains a `<insert command here>`, which looks like a note that someone left to be defined later and probably got forgotten. This missing command would refer to how one can show service environment variables from an application.

Regards,
Tiago.

[1]: https://github.com/tsuru/tsuru/blame/4fad8a10aa4ec9e179be7f8bf7f891d1b88e6ab6/docs/using/deployment.rst#L85

**Comment by andrewsmedina** [comment]
Hi @myhro, the `env-get` is the command missing here. Thank you for report.

**Comment by myhro** [comment]
Thank you, Andrews. I really didn't expected for it to be fixed so quickly. :-)
