### ISSUE TITLE
Tsuru failed when I execute git push

### ISSUE THREAD

**Issue by magichk** [tsuru/tsuru#1377]
Hi, 

I have installed tsuru and I have configured an application. When I execute tsuru app-info --app aplicacio1 the result is this:
```shell
root@tsuru:~/wordpress/wordpress# tsuru app-info --app aplicacio1
Application: aplicacio1
Repository: git@localhost:aplicacio1.git
Platform: php
Teams: test
Address: aplicacio1.localhost:80
Owner: admin@test.cat
Team owner: test
Deploys: 0
Pool: pool1
Quota: 0/4 units

App Plan:
+---------------+--------+------+-----------+--------+---------+
| Name          | Memory | Swap | Cpu Share | Router | Default |
+---------------+--------+------+-----------+--------+---------+
| autogenerated | 0      | 0    | 100       |        | false   |
+---------------+--------+------+-----------+--------+---------+
```
I have a remote repository like this:
```shell
> root@tsuru:~/wordpress/wordpress# git remote -v 
> tsuru git@localhost:aplicacio1.git (fetch)
> tsuru git@localhost:aplicacio1.git (push)
```
But when I try to push the code with git I have this problem....

> root@tsuru:~/wordpress/wordpress# git push tsuru master
> Counting objects: 1410, done.
> Compressing objects: 100% (1387/1387), done.
> Writing objects: 100% (1410/1410), 6.92 MiB | 2.95 MiB/s, done.
> Total 1410 (delta 114), reused 0 (delta 0)
> remote: HEAD se encuentra en f5ccae1... test
> remote: Traceback (most recent call last):
> remote:   File "<stdin>", line 2, in <module>
> remote:   File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
> remote:     return _default_decoder.decode(s)
> remote:   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
> remote:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> remote:   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
> remote:     raise ValueError("No JSON object could be decoded")
> remote: ValueError: No JSON object could be decoded
> To git@localhost:aplicacio1.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git@localhost:aplicacio1.git'

Any idea for this error ? :( 

Thanks.

Joan.

**Comment by fsouza** [comment]
Hi Joan, it sounds like a problem with the archive-server. Can you confirm that it's up and running, and on which host?

If you're running everything on the same machine, you should look for a process archive-server. And you should look for ``ARCHIVE_SERVER_*`` variables in ``~git/.profile``.

**Comment by magichk** [comment]
Hi,

Thanks for your reply. Yes, I'm running all the processes in the same host and here you have what the host is listening to:

> > root@tsuru:~# netstat -ntap | grep ESCUCHAR
> tcp        0      0 0.0.0.0:80              0.0.0.0:*               ESCUCHAR    886/node        
> tcp        0      0 84.88.12.53:4243        0.0.0.0:*               ESCUCHAR    771/docker      
> tcp        0      0 127.0.0.1:4243          0.0.0.0:*               ESCUCHAR    771/docker      
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               ESCUCHAR    926/sshd        
> tcp        0      0 127.0.0.1:3131          0.0.0.0:*               ESCUCHAR    888/archive-server
> tcp        0      0 127.0.0.1:11300         0.0.0.0:*               ESCUCHAR    980/beanstalkd  
> tcp        0      0 0.0.0.0:27017           0.0.0.0:*               ESCUCHAR    937/mongod      
> tcp        0      0 0.0.0.0:6379            0.0.0.0:*               ESCUCHAR    1203/redis-server *
> tcp6       0      0 ::1:80                  :::*                    ESCUCHAR    886/node        
> tcp6       0      0 :::8080                 :::*                    ESCUCHAR    1565/tsurud     
> tcp6       0      0 :::22                   :::*                    ESCUCHAR    926/sshd        
> tcp6       0      0 :::3232                 :::*                    ESCUCHAR    888/archive-server
> tcp6       0      0 :::8000                 :::*                    ESCUCHAR    893/gandalf-server
> tcp6       0      0 :::6379                 :::*                    ESCUCHAR    1203/redis-server *

At the bottom of the /home/git/.profile I put the following:

> export ARCHIVE_SERVER_READ=http://<my_public_ip>:3232 ARCHIVE_SERVER_WRITE=http://127.0.0.1:3131 TSURU_HOST=http://127.0.0.1:8080 TSURU_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

 In the official documentation, I read that variables are included at the end of the file /home/git/.bash_profile, so I did the same.

Do I have a wrong configuration?

Thanks for all,

Joan.

**Comment by fsouza** [comment]
It seems like it's properly configured. Can you check archive-server logs?

```
% cat /var/log/upstart/archive-server.log
```

And also the contents of the pre-receive hook (this path may differ, in case of doubt, check ``/etc/gandalf.conf`` to confirm where the bare-template is):

```
% cat /home/git/bare-template/hooks/pre-receive
```

**Comment by magichk** [comment]
When I went to check archive-server.log I saw that I didn't have this log. I have the logs until 26/2/16 but now the logs rotate and I have the compress files archive-server.log.1.gz  I unzip this file and this is the content :

>  root@tsuru:~/wordpress/wordpress# cat /var/log/upstart/archive-server.log.1
> 2016/02/26 08:25:12 [INFO] saving archive "1e555644a05928baa19cb968336298ca7bfe76ca9b5d025ace3a3760837f1f03cd621378ae72ccd121999792738c21f85af16bbb4e4c94c5d9d9d7520e1874d7"
> 2016/02/26 08:29:45 [INFO] saving archive "0f880b6b80ce8ab426ce7759b03ef4960f1a346c4b051eaf1de86d0af1166b41688003069180f60858336db276d4b3b86222c36b4b96e9176098f4efb61c1f3c"
> 2016/02/26 08:32:04 [INFO] saving archive "aa1884a233d635ac113a194098c10a24e24e44e00a8f768598fb159809e66736f0b4dec3e29c7a30c65feb6827701e256b3a79a0047a76eb47e5dc7600017d3e"
> 2016/02/26 08:33:50 [INFO] saving archive "f458304c88a7c12b9ba76f2735d75b6437691ecb63e83e92a847d1d4f7e10768dad3ca91746151591105310c5606b436a5d5e2aa7a9ff8d8ad30f7f486ee219b"
> 2016/02/26 08:52:46 [INFO] saving archive "3413bfd8247c24ea525376b0db26b9c28cc67e81d632acbf0734608f1f3ae88c6d24048f9ae629de256a1c56d61ce140c45bacefa7cacdbb7a0ec9d906de83b3"
> 2016/02/26 08:53:43 [INFO] saving archive "53d7b785206a49b95325266987a4d6d36a809723140eebb8d33e97a34c23eb93b1f46af730938f06ca1565adf10b4aca3ad6efc7e763e1a52ee616ce2d72e9cf"
> 2016/02/26 08:54:36 [INFO] saving archive "55e44859099d4549d89162190fdf5a8e836fdc0e9fc92dae5fe85d81902bda3c4980559b61cdc612a706fafab29fb31a4274beaaf7147c7f2bf0b6273b61e07f"
> 2016/02/26 08:56:21 [INFO] saving archive "818dff7dc8ea5035aab586357895f055493f6e3615e687ced401ef196e2acfd1e8de6ae3df98c3cca1f70308fe8d39788d75304b57dc0e638b2cd3590388c595"
> 2016/02/26 08:56:38 [INFO] saving archive "89bc1f7fba8c6b2b586b0038cd3e1322f2fda9f8c2de59c0507b6a188a7464ec54352f9c432f00920a80dcccf88f335e0ddf3f70416d8369f7d93f64de66caa3"
> 2016/02/26 08:57:08 [INFO] saving archive "58fb2a6ec2651bbd51a2c7193ee5e28f2bf5e9f4864d996584c3f31594cbbf1309f2fe3368a18a422fd19260938f2e4b1e4925e13b41af1862a5bbef56a1d8d9"
> 2016/02/26 08:57:28 [INFO] saving archive "4ca33516fcb20446f11a5fafd961bcd31c37d37e1e4d7f6a33c384e50cdfddd97839b7615783b3ac8c580cda050eabf35d4a4cbc361b1fc873f5c69f294365a2"
> 2016/02/26 09:22:52 [INFO] saving archive "eaebf2f179db87529d2d4d04cacde70beb97d924be2627bf20ad9269c6c98d343addc8ba69f48e75cb83ff120e6b103a81f56f0cc1fbf731fd131f9c00422060"

My config of gandalf is this:

> root@tsuru:~/wordpress/wordpress# cat /etc/gandalf.conf
> bin-path: /usr/bin/gandalf-ssh
> database:
>   url: 127.0.0.1:27017
>   name: gandalf
> git:
>   bare:
>     location: /var/lib/gandalf/repositories
>     template: /home/git/bare-template
> host: localhost
> bind: "0.0.0.0:8000"
> uid: git
> api:
>   request:
>     maxMemory: 2097152
> repository:
>   tempDir: /tmp

And the content of /home/git/bare-template/hooks/pre-receive are this:

> 
> while read oldrev newrev refname
> do
>         set +e
>         echo $refname | grep -v tags/master$ | grep -q /master$
>         status=$?
>         set -e
>         if [ $status = 0 ]
>         then
>                 COMMIT=${newrev}
>         fi
> done
> 
> if [ -z ${COMMIT} ]
> then
> 	echo "ERROR: please push to master"
> 	exit 3
> fi
> 
> wait_archive() {
>         url="${1}&keep=1"
>         content_type=`curl -sI $url | grep Content-Type | awk '{print $2}'`
>         while echo $content_type | grep -v application/x-gzip
>         do
>                 sleep 1
>                 content_type=`curl -sI $url | grep Content-Type | awk '{print $2}'`
>         done
> }
> 
> git_archive_all() {
>     REV=$1; FILE=$2
>     TMP_WORK_DIR=$(mktemp -d)
>     chmod 755 $TMP_WORK_DIR
>     unset GIT_DIR GIT_WORK_TREE
>     git clone -q $PWD $TMP_WORK_DIR &> /dev/null
>     pushd $TMP_WORK_DIR > /dev/null
>     git config advice.detachedHead false
>     git checkout $REV > /dev/null
>     git submodule update --init --recursive > /dev/null
>     find -name .git -prune -exec rm -rf {} \; > /dev/null
>     tar zcf /tmp/$FILE .
>     popd > /dev/null
>     rm -rf $TMP_WORK_DIR > /dev/null
> }
> 
> save_archive() {
>         url="${ARCHIVE_SERVER_WRITE}/"
>         result=`curl -sN -F archive=@/tmp/${1} $url`
>         python <<END
> import json
> print json.loads(u"""${result}""")["id"]
> END
> }
> 
> APP_DIR=${PWD##*/}
> APP_NAME=${APP_DIR/.git/}
> UUID=`python -c 'import uuid; print uuid.uuid4().hex'`
> ARCHIVE_FILE_NAME=${APP_NAME}_${COMMIT}_${UUID}.tar.gz
> git_archive_all $COMMIT $ARCHIVE_FILE_NAME
> archive_id=`save_archive $ARCHIVE_FILE_NAME`
> archive_url="${ARCHIVE_SERVER_READ}/?id=$archive_id"
> wait_archive $archive_url
> url="${TSURU_HOST}/apps/${APP_NAME}/deploy"
> curl -H "Authorization: bearer ${TSURU_TOKEN}" -d "archive-url=${archive_url}&commit=${COMMIT}&user=${TSURU_USER}" -s -N $url | tee /tmp/deploy-${APP_NAME}.log
> rm /tmp/${ARCHIVE_FILE_NAME}
> tail -1 /tmp/deploy-${APP_NAME}.log | grep -q "^OK$"

Thanks for all.

**Comment by fsouza** [comment]
@magichk is archive-server running?

```
$ status archive-server
```

**Comment by magichk** [comment]
hi !  Yes , I try this and the terminal return this:

> root@tsuru:~# status archive-server
> archive-server start/running, process 888
> root@tsuru:~# ps ax | grep archive-server
>   888 ?        Ssl    0:30 /usr/bin/archive-server -dir=/var/lib/archive-server/archives -read-http=0.0.0.0:3232 -write-http=127.0.0.1:3131 -mongodb=127.0.0.1:27017 -dbname=archives
> 18994 pts/2    S+     0:00 grep --color=auto archive-server
>

**Comment by fsouza** [comment]
What's the version of archive-server?

```
$ archive-server -version
```

Can you change the pre-receive for one of your apps (``/var/lib/gandalf/repositories/<app-name>.git/hooks/pre-receive``), change the ``-el`` in the first line to ``-elx`` and try pushing again? Here's how the pre-receive file should look like: https://gist.github.com/fsouza/4834151266b87f43411d.

You can update it with the following command (remember to replace **app-name** with the name of the app:

```
$ curl -Lo /var/lib/gandalf/repositories/<app-name>.git/hoos/pre-receive https://gist.githubusercontent.com/fsouza/4834151266b87f43411d/raw/fd6e3e65c73e526c52f6436ad3a877554585482d/pre-receive-archive-debug.bash
```

**Comment by magichk** [comment]
My version of archive-server is this : 

> root@tsuru:~/wordpress/wordpress# archive-server -version
> archive-server version 0.2.1

I download your pre-receive file with -elx at the final of the first line and execute the git push. When I try to execute git push the terminal returns this:

> root@tsuru:~/wordpress/wordpress# git push tsuru master
> Counting objects: 1410, done.
> Compressing objects: 100% (1387/1387), done.
> Writing objects: 100% (1410/1410), 6.92 MiB | 3.28 MiB/s, done.
> Total 1410 (delta 114), reused 0 (delta 0)
> remote: + '[' '' ']'
> remote: + '[' -d /etc/profile.d ']'
> remote: + for i in '/etc/profile.d/*.sh'
> remote: + '[' -r /etc/profile.d/bash_completion.sh ']'
> remote: + . /etc/profile.d/bash_completion.sh
> remote: ++ '[' -n '4.3.11(1)-release' -a -n '' -a -z '' ']'
> remote: + for i in '/etc/profile.d/*.sh'
> remote: + '[' -r /etc/profile.d/Z97-byobu.sh ']'
> remote: + . /etc/profile.d/Z97-byobu.sh
> remote: ++ '[' -n '' ']'
> remote: ++ '[' '' = byobu ']'
> remote: ++ '[' '' = byobu-screen ']'
> remote: ++ '[' '' = byobu-tmux ']'
> remote: + unset i
> remote: + read oldrev newrev refname
> remote: + set +e
> remote: + grep -v 'tags/master$'
> remote: + grep -q '/master$'
> remote: + echo refs/heads/master
> remote: + status=0
> remote: + set -e
> remote: + '[' 0 = 0 ']'
> remote: + COMMIT=f5ccae132631012ad80af518b1b93bcd0bee89d3
> remote: + read oldrev newrev refname
> remote: + '[' -z f5ccae132631012ad80af518b1b93bcd0bee89d3 ']'
> remote: + APP_DIR=aplicacio1.git
> remote: + APP_NAME=aplicacio1
> remote: ++ python -c 'import uuid; print uuid.uuid4().hex'
> remote: + UUID=9e8312e2952e47dba58917751aec24fd
> remote: + ARCHIVE_FILE_NAME=aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_9e8312e2952e47dba58917751aec24fd.tar.gz
> remote: + git_archive_all f5ccae132631012ad80af518b1b93bcd0bee89d3 aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_9e8312e2952e47dba58917751aec24fd.tar.gz
> remote: + REV=f5ccae132631012ad80af518b1b93bcd0bee89d3
> remote: + FILE=aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_9e8312e2952e47dba58917751aec24fd.tar.gz
> remote: ++ mktemp -d
> remote: + TMP_WORK_DIR=/tmp/tmp.YFqlLD73eu
> remote: + chmod 755 /tmp/tmp.YFqlLD73eu
> remote: + unset GIT_DIR GIT_WORK_TREE
> remote: + git clone -q /var/lib/gandalf/repositories/aplicacio1.git /tmp/tmp.YFqlLD73eu
> remote: + pushd /tmp/tmp.YFqlLD73eu
> remote: + git config advice.detachedHead false
> remote: + git checkout f5ccae132631012ad80af518b1b93bcd0bee89d3
> remote: HEAD se encuentra en f5ccae1... test
> remote: + git submodule update --init --recursive
> remote: + find -name .git -prune -exec rm -rf '{}' ';'
> remote: + tar zcf /tmp/aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_9e8312e2952e47dba58917751aec24fd.tar.gz .
> remote: + popd
> remote: + rm -rf /tmp/tmp.YFqlLD73eu
> remote: ++ save_archive aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_9e8312e2952e47dba58917751aec24fd.tar.gz
> remote: ++ url=/
> remote: +++ curl -sN -F archive=@/tmp/aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_9e8312e2952e47dba58917751aec24fd.tar.gz /
> remote: ++ result=
> remote: ++ python
> remote: Traceback (most recent call last):
> remote:   File "<stdin>", line 2, in <module>
> remote:   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
> remote:     return _default_decoder.decode(s)
> remote:   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
> remote:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> remote:   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
> remote:     raise ValueError("No JSON object could be decoded")
> remote: ValueError: No JSON object could be decoded
> remote: + archive_id=
> To git@localhost:aplicacio1.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git@localhost:aplicacio1.git'
>

**Comment by gwmoura** [comment]
This problem accour with another platform, like Python or Ruby?

**Comment by fsouza** [comment]
So, sounds like the script is not loading the required environment variables. You listed it in ``~git/.profile`` and ``~git/.bash_profile``, so we need to figure that out. Are you using the ``git`` user in your push? If you run ``git remote -v`` locally, does the output look like the one below?

```
$ git remote -v
origin	https://github.com/tsuru/tsuru-dashboard.git (fetch)
origin	https://github.com/tsuru/tsuru-dashboard.git (push)
tsuru	git@[my-tsuru-server]:[my-app].git (fetch)
tsuru	git@[my-tsuru-server]:[my-app].git (push)
```

Is the remote ``git@something:appname.git``? If so, what's the output of the command:

```
$ ls -ld ~git
```

That should expand the home of the git user (you can also find it in ``/etc/passwd``). Is it ``/home/git``?

Can you also check if you have a ``~git/.bashrc`` file and export environment variables there? As a last resort, can you try exporting the environment variables in ``/etc/profile``?

@gwmoura this error is happening at Gandalf machine, it's before using the platform, it's even before calling the Tsuru API.

**Comment by magichk** [comment]
Hi,

If I run git push command after including the enviroment variables at the end of /etc/default and /home/git/.bashrc the return is a different error.  I think that now the process is deploying the application into tsuru app but it doesn't connect to http://127.0.0.1:8080 yet.

When I execute the command git remote -v the result is the following: 

> root@tsuru:~/wordpress/wordpress# git remote -v 
> tsuru	git@localhost:aplicacio1.git (fetch)
> tsuru	git@localhost:aplicacio1.git (push)

And now when I run git push tsuru master the terminal show this: 

> root@tsuru:~/wordpress/wordpress# git push tsuru master
> Counting objects: 1410, done.
> Compressing objects: 100% (1387/1387), done.
> Writing objects: 100% (1410/1410), 6.92 MiB | 4.59 MiB/s, done.
> Total 1410 (delta 114), reused 0 (delta 0)
> remote: + '[' '' ']'
> remote: + '[' -d /etc/profile.d ']'
> remote: + for i in '/etc/profile.d/*.sh'
> remote: + '[' -r /etc/profile.d/bash_completion.sh ']'
> remote: + . /etc/profile.d/bash_completion.sh
> remote: ++ '[' -n '4.3.11(1)-release' -a -n '' -a -z '' ']'
> remote: + for i in '/etc/profile.d/*.sh'
> remote: + '[' -r /etc/profile.d/Z97-byobu.sh ']'
> remote: + . /etc/profile.d/Z97-byobu.sh
> remote: ++ '[' -n '' ']'
> remote: ++ '[' '' = byobu ']'
> remote: ++ '[' '' = byobu-screen ']'
> remote: ++ '[' '' = byobu-tmux ']'
> remote: + unset i
> remote: + export ARCHIVE_SERVER_READ=http://84.88.12.53:3232
> remote: + ARCHIVE_SERVER_READ=http://84.88.12.53:3232
> remote: + export ARCHIVE_SERVER_WRITE=http://127.0.0.1:3131
> remote: + ARCHIVE_SERVER_WRITE=http://127.0.0.1:3131
> remote: + export TSURU_HOST=http://127.0.0.1:8080
> remote: + TSURU_HOST=http://127.0.0.1:8080
> remote: + export TSURU_TOKEN=2387254bd9fa6abfc8087d04587aa29326ac7ee79eb8029794627890b7a10e00
> remote: + TSURU_TOKEN=2387254bd9fa6abfc8087d04587aa29326ac7ee79eb8029794627890b7a10e00
> remote: + read oldrev newrev refname
> remote: + set +e
> remote: + grep -q '/master$'
> remote: + grep -v 'tags/master$'
> remote: + echo refs/heads/master
> remote: + status=0
> remote: + set -e
> remote: + '[' 0 = 0 ']'
> remote: + COMMIT=f5ccae132631012ad80af518b1b93bcd0bee89d3
> remote: + read oldrev newrev refname
> remote: + '[' -z f5ccae132631012ad80af518b1b93bcd0bee89d3 ']'
> remote: + APP_DIR=aplicacio1.git
> remote: + APP_NAME=aplicacio1
> remote: ++ python -c 'import uuid; print uuid.uuid4().hex'
> remote: + UUID=fda3cd94f0c941f5b85d102e22d0672d
> remote: + ARCHIVE_FILE_NAME=aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_fda3cd94f0c941f5b85d102e22d0672d.tar.gz
> remote: + git_archive_all f5ccae132631012ad80af518b1b93bcd0bee89d3 aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_fda3cd94f0c941f5b85d102e22d0672d.tar.gz
> remote: + REV=f5ccae132631012ad80af518b1b93bcd0bee89d3
> remote: + FILE=aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_fda3cd94f0c941f5b85d102e22d0672d.tar.gz
> remote: ++ mktemp -d
> remote: + TMP_WORK_DIR=/tmp/tmp.dOJ1hAdoC0
> remote: + chmod 755 /tmp/tmp.dOJ1hAdoC0
> remote: + unset GIT_DIR GIT_WORK_TREE
> remote: + git clone -q /var/lib/gandalf/repositories/aplicacio1.git /tmp/tmp.dOJ1hAdoC0
> remote: + pushd /tmp/tmp.dOJ1hAdoC0
> remote: + git config advice.detachedHead false
> remote: + git checkout f5ccae132631012ad80af518b1b93bcd0bee89d3
> remote: HEAD se encuentra en f5ccae1... test
> remote: + git submodule update --init --recursive
> remote: + find -name .git -prune -exec rm -rf '{}' ';'
> remote: + tar zcf /tmp/aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_fda3cd94f0c941f5b85d102e22d0672d.tar.gz .
> remote: + popd
> remote: + rm -rf /tmp/tmp.dOJ1hAdoC0
> remote: ++ save_archive aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_fda3cd94f0c941f5b85d102e22d0672d.tar.gz
> remote: ++ url=http://127.0.0.1:3131/
> remote: +++ curl -sN -F archive=@/tmp/aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_fda3cd94f0c941f5b85d102e22d0672d.tar.gz http://127.0.0.1:3131/
> remote: ++ result='{"id":"189fc6374c6ca78036c63184c507d8a456c9e834d6c0dc88657950f0fc05854b5133b32ab0bc4e7591cd13313721c3436b309383557b2625c4d9f04915107a2e"}'
> remote: ++ python
> remote: + archive_id=189fc6374c6ca78036c63184c507d8a456c9e834d6c0dc88657950f0fc05854b5133b32ab0bc4e7591cd13313721c3436b309383557b2625c4d9f04915107a2e
> remote: + archive_url='http://84.88.12.53:3232/?id=189fc6374c6ca78036c63184c507d8a456c9e834d6c0dc88657950f0fc05854b5133b32ab0bc4e7591cd13313721c3436b309383557b2625c4d9f04915107a2e'
> remote: + wait_archive 'http://84.88.12.53:3232/?id=189fc6374c6ca78036c63184c507d8a456c9e834d6c0dc88657950f0fc05854b5133b32ab0bc4e7591cd13313721c3436b309383557b2625c4d9f04915107a2e'
> remote: + url='http://84.88.12.53:3232/?id=189fc6374c6ca78036c63184c507d8a456c9e834d6c0dc88657950f0fc05854b5133b32ab0bc4e7591cd13313721c3436b309383557b2625c4d9f04915107a2e&keep=1'
> remote: ++ awk '{print $2}'
> remote: ++ grep Content-Type
> remote: ++ curl -sI 'http://84.88.12.53:3232/?id=189fc6374c6ca78036c63184c507d8a456c9e834d6c0dc88657950f0fc05854b5133b32ab0bc4e7591cd13313721c3436b309383557b2625c4d9f04915107a2e&keep=1'
> remote: + content_type=$'application/x-gzip\r'
> remote: + grep -v application/x-gzip
> remote: + echo $'application/x-gzip\r'
> remote: + url=http://127.0.0.1:8080/apps/aplicacio1/deploy
> remote: + tee /tmp/deploy-aplicacio1.log
> remote: + curl -H 'Authorization: bearer 2387254bd9fa6abfc8087d04587aa29326ac7ee79eb8029794627890b7a10e00' -d 'archive-url=http://84.88.12.53:3232/?id=189fc6374c6ca78036c63184c507d8a456c9e834d6c0dc88657950f0fc05854b5133b32ab0bc4e7591cd13313721c3436b309383557b2625c4d9f04915107a2e&commit=f5ccae132631012ad80af518b1b93bcd0bee89d3&user=admin@csuc.cat' -s -N http://127.0.0.1:8080/apps/aplicacio1/deploy
> remote: stdin: is not a tty
> remote: 2016/03/03 09:06:33 Post http://0.0.0.0:8080/apps/aplicacio1/units/register: dial tcp 0.0.0.0:8080: getsockopt: connection refused
> remote: Exit status 1
> remote: + rm /tmp/aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_fda3cd94f0c941f5b85d102e22d0672d.tar.gz
> remote: + grep -q '^OK$'
> remote: + tail -1 /tmp/deploy-aplicacio1.log
> To git@localhost:aplicacio1.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git@localhost:aplicacio1.git'
>

I see that git has the enviroment variables but when they try to connect to TSURU_HOST they don't connect :( Do you know why?  If I execute cat /tmp/deploy-aplicacio1.log I see this:

> root@tsuru:~/wordpress/wordpress# cat /tmp/deploy-aplicacio1.log 
> stdin: is not a tty
> 2016/03/03 09:06:33 Post http://0.0.0.0:8080/apps/aplicacio1/units/register: dial tcp 0.0.0.0:8080: getsockopt: connection refused
> Exit status 1

I hope this helps to other users also so they can install tsuru without the same problems than me! Thanks!

**Comment by fsouza** [comment]
Interesting, can you try changing the value of TSURU_HOST to http://127.0.0.1:8080 instead?

This value comes from the tsuru.conf file (``/etc/tsuru/tsuru.conf``).

**Comment by magichk** [comment]
I change in /etc/tsuru/tsuru.conf 0.0.0.0:8080 like this: 

> listen: "0.0.0.0:8080"
> host: http://127.0.0.1:8080

I restart the tsuru-server-api and when I try to execute git push tsuru master the result are this: 

> remote: + curl -H 'Authorization: bearer 2387254bd9fa6abfc8087d04587aa29326ac7ee79eb8029794627890b7a10e00' -d 'archive-url=http://84.88.12.53:3232/?id=9cff253628180a6c8bfbd2790d6daf45d3575b8f0a4fdf845da2f0772b20c03313abe1913a72b56a9c6e93be7ac7ffe2bbf2052a254ab2e0833b844aa0d2ff12&commit=f5ccae132631012ad80af518b1b93bcd0bee89d3&user=admin@csuc.cat' -s -N http://127.0.0.1:8080/apps/aplicacio1/deploy
> remote: stdin: is not a tty
> remote: 2016/03/03 14:24:13 Post http://127.0.0.1:8080/apps/aplicacio1/units/register: dial tcp 127.0.0.1:8080: getsockopt: connection refused
> remote: Exit status 1
> remote: + rm /tmp/aplicacio1_f5ccae132631012ad80af518b1b93bcd0bee89d3_6aaca225f69e49c3a6285e3193911e12.tar.gz
> remote: + grep -q '^OK$'
> remote: + tail -1 /tmp/deploy-aplicacio1.log
> To git@localhost:aplicacio1.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git@localhost:aplicacio1.git'

I see in the error that it doesn't connect to 127.0.0.1 at port 8080 and I try to connect with telnet and I can connect to host on port 8080. 

> root@tsuru:~/wordpress/wordpress# telnet 127.0.0.1 8080
> Trying 127.0.0.1...
> Connected to 127.0.0.1.
> Escape character is '^]'.

But when I press return key the terminal return following:

> root@tsuru:~/wordpress/wordpress# telnet 127.0.0.1 8080
> Trying 127.0.0.1...
> Connected to 127.0.0.1.
> Escape character is '^]'.
> 
> HTTP/1.1 400 Bad Request
> 
> Connection closed by foreign host.

**Comment by fsouza** [comment]
Ahh, this command is running from within the container, so you need to set host to some IP that is accessible from the container. The valid private IP address of your host is probably going to work.

On [tsuru-bootstrap](https://github.com/tsuru/tsuru-bootstrap), we use 192.168.50.4, which is the IP address that we define in the [Vagrantfile](https://github.com/tsuru/tsuru-bootstrap/blob/master/Vagrantfile#L23).

**Comment by magichk** [comment]
Yes !!!!!!!!!!!

I change 127.0.0.1 to my private IP and now when I run git push tsuru master works!!! :-D :+1:  and when I execute netstat -ntap | grep LISTEN i view that the app works on port 32768 and it's accesible from Firefox.

Thanks for all =) !!!!

**Comment by fsouza** [comment]
Awesome! Did you setup all components manually? Do you see any points that we could improve in our documentation?

**Comment by magichk** [comment]
Hi, 

Yes, sure, I can document the process that I followed to run tsuru. I will re-install manually all the services and I will document it. I'll post it here when it's done!

Thanks.
