### ISSUE TITLE
Doing things with services

### ISSUE THREAD

**Issue by badri** [tsuru/tsuru#1378]
I'd like to do more than create/delete and bind/unbind service instances.

For example, I want to use a Hadoop cluster from my web app, which would most likely be a service. This service app will expose all the env vars of the Hadoop cluster.

I might want to resize the cluster by adding more nodes to it, like how I do in https://aws.amazon.com/elasticmapreduce/.

The current service interface has no such endpoints to "mutate" the service state. I can either create a new instance, destroy it, and (un)bind it.

Would it make sense to add a `PUT /change` to the service interface?

**Comment by andrewsmedina** [comment]
Hi @badri, 

currently we do things like it using the tsuru plugin system: https://docs.tsuru.io/stable/using/cli/plugins.html?highlight=plugin#creating-your-own-plugin.

You can add custom routes in your service api and call them using a plugin. tsuru api has a route to be a proxy to custom service api routes.

A good example is the healthcheck service api, that has a command to add urls in zabbix: https://github.com/tsuru/healthcheck-as-a-service/blob/master/healthcheck/api.py#L49 and the plugin: https://github.com/tsuru/healthcheck-as-a-service/blob/master/healthcheck/plugin.py#L53
