### ISSUE TITLE
Improve help of app-list command

### ISSUE THREAD

**Issue by dfleury** [tsuru/tsuru#1380]
I noticed that app-list have an `-s` option which can filter apps by status.
However, the help of this command  doesn't specify the possible values that I can filter by.

I believe that states described in [this comment](https://github.com/tsuru/tsuru/blob/master/provision/provision.go#L69) are the values I'm looking for. (I'd filtered by 'started' and it'd worked, however I haven't other apps with different states to guarantee that the others are working too)
That information should be in the help of app-list command.

Can someone ensure that is right? If it is, I can add it by myself.

**Comment by ggarnier** [comment]
@dfleury that's right, those are the possible status values. You can also pass more than one value: `tsuru app-list -s stopped,asleep`

**Comment by dfleury** [comment]
@ggarnier thank you
