### ISSUE TITLE
DoS protection?

### ISSUE THREAD

**Issue by blacksector** [tsuru/tsuru#1384]
Hello Everyone!

I was wondering for the signup api, does tsuru actually have a DoS protection? No more than a certain amount of signups per IP? Etc?

Unsure if thats implementable either. I have disabled signup but I will use my admin account to create the accounts manually for now.

Thanks!

**Comment by andrewsmedina** [comment]
@blacksector tsuru does not have a DoS protection. You can disable the user registration and to use an oauth service provider to handle user accounts.

**Comment by blacksector** [comment]
@andrewsmedina Great, thank you! I'll keep user registration disabled and separately create apps for users. Thanks! :)
