### ISSUE TITLE
Tsuru and Google Cloud?

### ISSUE THREAD

**Issue by blacksector** [tsuru/tsuru#1386]
Hello everyone. 

I was wondering if Tsuru is capable of autoscaling in Google Cloud. If so, how would that be done?

Thanks!

**Comment by cezarsa** [comment]
Hi, using Google Cloud as an IaaS is not yet supported. We're working on integrating tsuru with docker machines and this would enable tsuru to use any IaaS provider supported by docker machines. However, there's no deadline for this at the moment.

**Comment by blacksector** [comment]
Oh man I was looking for Docker support! But great thank you! I'll see if I can manually do that myself with Google Cloud.

A quick question, how do I add a new node? to the cluster? Tsuru generated the "theonepool" and the "autogenerated" plan but I dont know how to add a new machine to the cluster. Any ideas? Sorry, completely new to the PaaS environment and Tsuru itself, just learning how to get used to it. :)

**Comment by cezarsa** [comment]
The documentation for adding new nodes is here https://docs.tsuru.io/stable/installing/adding-nodes.html and here https://tsuru-admin.readthedocs.org/en/latest/reference.html#add-a-new-docker-node

If you're using GCE you'll have to add it as an "unmanaged node" using the command `tsuru-admin docker-node-add address=http://<machineip>:<dockerport> pool=theonepool`

**Comment by blacksector** [comment]
Great thanks a lot @cezarsa ! :) Will try that out right now

**Comment by cezarsa** [comment]
There was a `--register` parameter missing from the example command I showed you. I've just edited it.

**Comment by blacksector** [comment]
Would this need to be executed on the first node or the node you want to add?

And no worries thanks, I am just setting up the main VM first :)

**Comment by blacksector** [comment]
Hi, another question.

Do you know how to deploy to Google Cloud? After I installed it, Tsuru doesnt want to connect. I went into the Tsuru config file in /etc/tsuru/tsuru.conf and the issue is it is using Google's internal IP address, after changing it and opening firewall rules to port 8080 it connects and registers users. But unfortunately git push doesnt work because it is listening to 127.0.0.1. Can the git port be changed to the external ip address of the server?

**Comment by cezarsa** [comment]
git push connects to the server using ssh, it's not necessary to expose the gandalf server to the world if it's on the same machine as tsuru api (even though you can do it by editing /etc/gandalf.conf). If ssh port 22 is open on your firewall git push should work as expected. Are you trying to push to `git@<externalip>:<appname>.git`?

**Comment by blacksector** [comment]
Yes I tried. And ok good news, it worked, but then the domains didnt work. 

So instead I opened all my firewall ports from 1-65000 on google cloud tcp :) I hope thats secure?

**Comment by blacksector** [comment]
Thanks a ton by the way @cezarsa ! I'll close this now? :)

**Comment by blacksector** [comment]
@cezarsa What should the docker port be? I came down to this: 2375. I am trying to link two completely separate systems. After I use the --register and the full command it shows "ready" on tsuru-admin docker-node-list
But are they linked? When I try to log in from node 1 through node 2 it doesnt work. Do you have maybe a detailed guide on how to? I cannot seem to find anything on the docs. Sorry!

**Comment by gwmoura** [comment]
@blacksector in your node 2, the mongodb is the same of node 1? The user data are saved in mongodb, if your node 2 is configured to use one mongodb and your node 1 have another mongodb, the login will fail because the user not exists in database

**Comment by cezarsa** [comment]
If the nodes are visible in `tsuru-admin docker-node-list` as ready and they have the same pool metadata you're ready to use them. Try creating a new app with `tsuru app-create`, deploying it and adding an extra unit with `tsuru unit-add 1 -a <appname>`. After this you should have 2 units for this app with 1 in each node. You can verify this by running `tsuru app-info -a <appname>` after the units are added.

The nodes are not `linked`. They don't need to directly access each other. It's only necessary for the tsuru api server (tsurud) to be able to reach them. For now, tsuru does not support docker networking which would allow containers in different hosts to be linked (as in `docker run --link`).

**Comment by blacksector** [comment]
@gwmoura Thanks for that! Well do you know how I can link the two?

@cezarsa The nodes show each other as "ready" but when logging in the databases are separated, now the question is, is there no security feature? Like requiring a special token to work? Or is it that both nodes have the command docker-node-add executed in order to be "ready"? In that case I'll just keep one node as the front end node and the rest even though they have their own registration and separate database will just be linked to the first node in the background?

**Comment by gwmoura** [comment]
@blacksector you can update section `database:` in your tsuru.conf

**Comment by blacksector** [comment]
@gwmoura I see and just simply change it to the database ip and port of the first node right? Thanks :)

**Comment by cezarsa** [comment]
@blacksector So I think we're mixing things up. Let's take a step back. How did you install tsuru? Was it using the tsuru/now or tsuru-bootstrap scripts?

If that was the case these scripts are for development and evaluation purpose, if you run them on two different machines they will install two independent full installations of tsuru with all its components duplicated. This may be the source of confusion.

If you simply want to add another node to an existing tsuru installation you can either install **only** docker yourself on the machine or run tsuru/now with `--template dockerfarm` and `--host-ip <ip where tsurud is running>`. This way there won't be a second database and tsurud won't be installed on this second machine.

For a simple installation you should have a single machine running `tsurud`. If you want to configure tsuru server with HA them you can have multiple machines running `tsurud` but they should be behind a load balancer and should all use the same `tsuru.conf` file pointing to a single MongoDB database.

It's also possible to configure MongoDB with HA and you can find more information about this on MongoDB docs.

**Comment by blacksector** [comment]
@cezarsa Oh I see aahh makes more sense, the tsuru/now is what was causing the confusion, that and my obliviousness. So instead of using tsuru/now or the bootstrap scripts or any other install I should simply create them separately with a load balancer, and all the configuration manually. Makes sense :)

Really sorry about all the confusion  thank you though! Really helpful

**Comment by blacksector** [comment]
@cezarsa The command `curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash -s -- --template dockerfarm --host-ip <ip where tsurud is running>`
Throws this error at me when I try t login with admin from any computer or the admin panel:
`Password: Error: unauthorized`
