### ISSUE TITLE
tsuru plugin command with an error in TSURU_TARGET 

### ISSUE THREAD

**Issue by magnotorres** [tsuru/tsuru#1388]
When invoking an plugin, tsuru client injects a TSURU_TARGET env and adds /1.0/ to the end of the uri, what makes an execution of tsuru client inside the plugin to fail with: "Error: 404 page not found"

Ps: A workaround when using bash is: unset TSURU_TARGET, before call the tsuru client inside the plugin

**Comment by andrewsmedina** [comment]
fixed https://github.com/tsuru/tsuru-client/commit/4c5e438dde583c6a5f26867d8bc5f7dc28d82907
