### ISSUE TITLE
Phalcon example. Modify platform. Add-repository, install packages, compile, change files

### ISSUE THREAD

**Issue by dmitryck** [tsuru/tsuru#1391]
Hello!
I have a question. Is there a possibility in tsuru to modify existing platform, without install platform from my own specific dockerfile?

In example, a want to use Phalcon - a very fast php framework written in c and installed as a php extension "so"
It is easy to install, but in tsuru architecture - how can i do it?
Is the a "tsuru way" to do all this install instructions with existing platform (from tsuru base builder):
[https://www.phalconphp.com/en/download](url)
summary:
- Add dependencies (enable in tsuru - requirements.apt)
- Add-repository
- Install new packages
- Compile some code
- Add changes to some file

So, is there a tsuru way do all this with platforms?
Ok, thanx!

**Comment by andrewsmedina** [comment]
There are two ways to install a platform. With a Dockerfile ou based on a Docker image. Why you don't want to create your own Dockerfile?
