### ISSUE TITLE
tsuru-client: app-deploy using app name "guess" should require confirmation

### ISSUE THREAD

**Issue by morpheu** [tsuru/tsuru#1404]
When using app-deploy without app name arg, tsuru-client tries to guess app name using current directory. Tsuru should requires confirmation to avoid wrong app name as deploy target.

**Comment by fsouza** [comment]
If there's a risk of doing something wrong, we should remove guessing altogether, as we did in ``app-remove``. Otherwise users will replace ``tsuru app-deploy`` with ``tsuru app-deploy -y``.

**Comment by cezarsa** [comment]
I think guessing based on git remote name is relatively safer than directory name. I'm in favor of removing guessing based on directory name altogether.

**Comment by andrewsmedina** [comment]
+1 for removing guessing name based on directory name.

**Comment by morpheu** [comment]
+1 for remove it

**Comment by gwmoura** [comment]
:+1: for remove

**Comment by tarsisazevedo** [comment]
👍 for remove

**Comment by magnotorres** [comment]
👍  for remove

**Comment by andrestc** [comment]
:+1:
