### ISSUE TITLE
Issue on convertToken

### ISSUE THREAD

**Issue by smartwang** [tsuru/tsuru#1408]
I'm trying to use oauth login, but I met an error while getting access token.

Here's the response content:
   **You must provide code to login**

I read the source code and found convertToken() in tsuru/tsuru/cmd/oauth.go do an http.post with Content-Type: application/json, but in tsuru/tsuru/api/auth.go, the login func treat  it as  a form and failed to get the 'code' field.

I just use the raw body, and it seems work:

```
raw_body, _ := ioutil.ReadAll(r.Body)
err = json.Unmarshal(raw_body, &params)
```

**Comment by andrewsmedina** [comment]
I believe that this issue was fixed by https://github.com/tsuru/tsuru/commit/943486736ee5ce0c623f67bfd057181c2cfb8eab
