### ISSUE TITLE
xenial tsuru client errors  

### ISSUE THREAD

**Issue by niccolox** [tsuru/tsuru#1411]
installed tsuru client tools on xenial host and have vmware vm guest running trusty tsuru server installed from script

on tsuru vmware guest vm, can tsuru login and create users etc

but on xenial host, with tsuru client tools built from source am getting 

tsuru login
Email: niccolo.roberts@gmail.com
Password: Error: Invalid JSON

tsuru app-create blog ruby
Error: you're not authenticated or your session has expired.
Calling the "login" command...
Email: niccolo.roberts@gmail.com
Password: Error: Invalid JSON

but on tsuru vm
devekko@tsuru:~$ tsuru login
Email: niccolo.roberts@gmail.com
Password: 
Successfully logged in!

**Comment by andrewsmedina** [comment]
the version between tsuru from vm and the other host are incompatible.

you can check the version with `tsuru version` and `tsurud version`

**Comment by andrewsmedina** [comment]
With tsurud 1.0 and tsuru 1.0.1 is released I believe that this problem was fixed. @niccolox can we close this issue?
