### ISSUE TITLE
Allow use of CName with the router when the prefix contains a dot

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1412]
Currently, we block users from defining a cname using the router domain, to prevent app name conflicts. So, assuming that the router is configured for the domain ``apps.mycompany.com``, this is how we behave:

```
% tsuru cname-add -a myapp myothername.apps.mycompany.com
Error: CName as router subdomain not allowed
```

But the way we check this right now is not ideal:

```
% tsuru cname-add -a myapp myapp.dev.app.mycompany.com
Error: CName as router subdomain not allowed
```

We could allow this cname, as we don't allow dots in the name of the application. I propose changing the cname validation to check if the provided cname matches ``[app-name-regexp].[router-domain]``, instead of just checking if the cname ends with ``[router-domain]``.

**Comment by cezarsa** [comment]
We already considered in the past allowing an application to have multiple processes listening for http traffic. One way of allowing this would be registering subdomains for the application name in the router. A `test` application with `web1` and `web2` processes would have routes added for: 
```
web1.test.apps.mycompany.com
web2.test.apps.mycompany.com
```
This does not exist yet but it is something we probably want to think about.

In your example, allowing `myapp.dev.apps.mycompany.com` would complicate things if a new app named `dev` with a process named `myapp` was created.
