### ISSUE TITLE
[Feature] Remove old deploy

### ISSUE THREAD

**Issue by johnsudaar** [tsuru/tsuru#1414]
When deploying an app, old deploys are keeped for application rollback.

But sometimes these deploys even if they've passed the build process do not work. Can we add a `tsuru app-deploy-remove` command to remove old deploys. This can help to not rollback on a bugged version and can help optimize hdd space on servers.

**Comment by ArxdSilva** [comment]
@johnsudaar we've decided to keep the image and just disable It on the structure, so If you ever decide on reverting your disable, you'll be able to. It'll also be required to give and see a reason on why It's rollback was disabled.
