### ISSUE TITLE
Django redirects are not working properly / Router changes the HTTP_HOST

### ISSUE THREAD

**Issue by ervilis** [tsuru/tsuru#1417]
When I deploy a Django app the django redirects are not working properly.

Django expects that the request META `HTTP_HOST` be the CNAME of the app. When request is coming thru tsuru router the `HTTP_HOST` is changed to the AWS EC2 public DNS of the Docker host and the app CNAME is set in `HTTP_X_HOST`. 

Django has the `USE_X_FORWARDED_HOST` setting but it works only with META `HTTP_X_FORWARDED_HOST` as we can see in the following docs:
https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-USE_X_FORWARDED_HOST

The question is how can I fix this problem in the right way, without change the Django behaviour?

BTW, thanks for this awesome project that makes my life too more easy :heart:

**Comment by andrewsmedina** [comment]
@guilhermef has sent today a PR to planb (tsuru router) that fix this problem: https://github.com/tsuru/planb/pull/11

**Comment by ervilis** [comment]
Very thank you @guilhermef . Problem solved. Issue solved.
