### ISSUE TITLE
Deploy docker images?

### ISSUE THREAD

**Issue by fnzv** [tsuru/tsuru#1425]
Hi,
Is is possible to deploy docker images with tsuru?

**Comment by tarsisazevedo** [comment]
Hi @fnzv, yes you have to use `tsuru app-deploy -i <docker image>`

**Comment by fnzv** [comment]
tsuru app-deploy -i ubuntu-core 
flag provided but not defined: -i
Usage:
-a, --app (= "")
    The name of the app.
-h, --help  (= false)
    Display help and exit
?

I have installed tsuru with curl -sL https://raw.githubusercontent.com/tsuru/now/master/run.bash | bash

**Comment by andrestc** [comment]
Hi @fnzv, 
You should install tsuru from source (using the ```--tsuru-from-source``` option when running ```now```) or using our nightly builds (using the ```--tsuru-pkg-nightly``` option), since the stable version (which is installed by default from ```now```) does not support deplying images yet. This feature is in our RC for the 1.0 release.

**Comment by fnzv** [comment]
i installed run.bash with --tsuru-from-source but i still get the same error, do i need to compile from source also the tsuru client? (i have installed it from ppa)

**Comment by andrewsmedina** [comment]
@fnzv yes, you should install tsuru client from source too.

**Comment by tarsisazevedo** [comment]
@fnzv there is a release candidate ppa for tsuru packages, `ppa:tsuru/rc`. You can use it to install these packages.

**Comment by fnzv** [comment]
@tarsisazevedo  I used tsuru/rc ppa and now this is what happens.
```
root@tsuru-rc:/home/application/current# tsuru-admin platform-add ubuntu -i ubuntu
Step 1 : FROM ubuntu
Pulling from library/ubuntu
Digest: sha256:f1b592e2de671105255a0c0b7b2f71a92b829403e8fc845e3482667ecc301780
Status: Image is up to date for ubuntu:latest
 ---> 12543ced0f6f
Successfully built 12543ced0f6f
Platform successfully added!
```

----------------------------------------------------------------------

```
root@tsuru-rc:/home/application/current# tsuru app-create ubuntutest ubuntu -t admin
App "ubuntutest" has been created!
Use app-info to check the status of the app and its units.
Your repository for "ubuntutest" project is "git@10.0.0.18.nip.io:ubuntutest.git"
```
---------------------------------------------------------
```
 tsuru app-deploy -i ubuntu --app ubuntutest
Deploying image... ok
---- Pulling image to tsuru ----
Pulling from library/ubuntu
Digest: sha256:f1b592e2de671105255a0c0b7b2f71a92b829403e8fc845e3482667ecc301780
Status: Image is up to date for ubuntu:latest
---- Getting process from image ----
  ---> Procfile not found, trying to get entrypoint
You should provide a entrypoint in image or a Procfile in the following locations: /home/application/current or /app/user or /.
```

**Comment by tarsisazevedo** [comment]
@fnzv tsuru need a way to run your image. So you have to provide an image with an entrypoint or a Procfile in one of the following paths: ` /home/application/current or /app/user or /`

**Comment by fnzv** [comment]
I copied this ubuntu Dockerfile ( https://github.com/dockerfile/ubuntu/blob/master/Dockerfile) in all the paths but same error.
I added also ENTRYPOINT ["/bin/bash"] on the Dockerfile but still same warning, the app is created but not deployed(i can see it on tsuru app-list).
I don't know what kind of Procfile is needed if i want only to deploy a ubuntu with no applications on it

**Comment by gwmoura** [comment]
I belive deploy a os whitout apps is not a role of the tsuru. Tsuru is a paas he was made to deploy apps.
