### ISSUE TITLE
Support application keys

### ISSUE THREAD

**Issue by scorphus** [tsuru/tsuru#1433]
Whenever Alice, the user, needs to grant a third party application (say a CI like Jenkins or a build bot) access to the one of her apps (a tsuru app) to make deploys, set env vars, or whatever, she might just create a new application key (that would work like a token) and assign roles to it.

**Comment by cezarsa** [comment]
To address this issue we initially thought about creating the concept of app tokens and @ggarnier started working on this in #1935. However, we soon realized that this would not solve all of the use cases we had for tokens and the proposal changed to creating team tokens but I think it will also be not enough to address all possible uses of tokens.

I'd like to propose a new concept here, the creation of tsuru tokens, tsuru tokens would still be attached to a team initially as a way to make it easier to find them, but these tokens will also possibly have any role of any context assigned to them, and assigning roles will change who can view the tokens.

Here is some example on how I imagine these tokens working:

Who can create the token: users with token.create on (team myteam)

```
$ tsuru token-create --team myteam --description "token x"
```

Who can list the token: users with token.read on (team myteam)

```
$ tsuru token-list
+----------+--------+-------------+-------+
| Token ID | Team   | Description | Roles |
+----------+--------+-------------+-------+
| xxxxxxxx | myteam | token x     |       |
+----------+--------+-------------+-------+
```

Who can assign the token: users with token.update on (team myteam) AND with team-member role on (team myteam)

```
$ tsuru role-assign team-member <token id> myteam
```

Who can list the token: users with token.read on (team myteam) AND with team-member role on (team myteam)
```

$ tsuru token-list
+----------+--------+-------------+--------------------------+
| Token ID | Team   | Description | Roles                    |
+----------+--------+-------------+--------------------------+
| xxxxxxxx | myteam | token x     | team-member(team myteam) |
+----------+--------+-------------+--------------------------+
```

Who can assign the token: users with token.update on (team myteam) AND with pool-manager role on (pool mypool)

```
$ tsuru role-assign pool-manager <token id> mypool
```

Who can list the token: users with token.read on (team myteam) AND with team-member role on (team myteam) AND with pool-manager role on (pool mypool)

```
$ tsuru token-list
+----------+--------+-------------+---------------------------+
| Token ID | Team   | Description | Roles                     |
+----------+--------+-------------+---------------------------+
| xxxxxxxx | myteam | token x     | team-member(team myteam)  |
|          |        |             | pool-manager(pool mypool) |
+----------+--------+-------------+---------------------------+
```
