### ISSUE TITLE
Can't install any new language platform on tsuru-bootstrap

### ISSUE THREAD

**Issue by resilva87** [tsuru/tsuru#1438]
Hi

I'm testing tsuru with tsuru-bootstrap image, just found that I can't install any language platform.

Steps to reproduce:

1. Clone/download tsuru-bootstrap (https://github.com/tsuru/tsuru-bootstrap)
2. `vagrant up && vagrant ssh` 
3.  Run `tsuru-admin platform-add go --dockerfile https://raw.githubusercontent.com/tsuru/platforms/master/go/Dockerfile` (any platform from https://github.com/tsuru/platforms)

Expected: Successfull platform installation

Actual (for instance trying to install golang):

```
   vagrant@vagrant-ubuntu-trusty-64:~$ tsuru-admin platform-add go --dockerfile  https://raw.githubusercontent.com/tsuru/platforms/master/go/Dockerfile
   Step 1 : FROM tsuru/base-platform
   Pulling from tsuru/base-platform
   Digest: sha256:1c33c2dd114bf4f02fead54ed32b31d35a1cd3cc6e35b1ed24a0c337b81cd135
   Status: Image is up to date for tsuru/base-platform:latest
   ---> 7b03d141c53c
   Step 2 : ADD . /var/lib/tsuru/go
   ---> b9c7230679d1
   Removing intermediate container 144b21119f11
   Step 3 : RUN cp /var/lib/tsuru/go/deploy /var/lib/tsuru
    ---> Running in fb3cf62dd410
   cp: cannot stat ‘/var/lib/tsuru/go/deploy’: No such file or directory
   Error: error in docker node "http://127.0.0.1:2375": The command '/bin/sh -c cp /var/lib/tsuru/go/deploy /var/lib/tsuru' returned a non-zero code: 1
```

**Comment by cezarsa** [comment]
Hi @resilva87, you don't need to add the `--dockerfile` parameter anymore. All platforms on the tsuru/platforms are automatically built by docker hub itself.

To add a new platform simply run:
```
tsuru-admin platform-add go
```

It will automatically download the `tsuru/go` platform from docker hub.

Alternatively you can call add the `--image` parameter with the full name of an image in any registry.

**Comment by resilva87** [comment]
Hi @cezarsa, that did the trick, thanks.

I know you guys have several things to deal with but I think it would be great if that information could be updated in https://docs.tsuru.io/stable/managing/add-platform.html

**Comment by cezarsa** [comment]
No problem. Thanks for letting us know, I'll update the documentation to reflect the new default way of adding platforms.
However, the way described in the documentation would also work. Because it's using the `tsuru/basebuilder` (not the `tsuru/platforms`) repository. The Dockerfile in `tsuru/basebuilder` has a single line `FROM tsuru/<platform>` which would also cause tsuru to use the pre-built image. This was done for backwards compatibility but I can see how it can be confusing to new users since there's now a tsuru/platforms repository and intuitively it should be the one used.

**Comment by andrewsmedina** [comment]
@resilva87 Install plataforms from image is a best pratice but the -d/--dockerfile still works. To work you should get the Dockerfiles from `basebuilder` repository: https://github.com/tsuru/basebuilder.

**Comment by resilva87** [comment]
Thanks @andrewsmedina and @cezarsa. I've successfully installed a new platform with basebuilder repo.
This can be closed :+1:
