### ISSUE TITLE
unbind units should retry after failure on remote service

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#1440]
Currently during the deploy pipeline, if a failure happens during calls to `/unbind-unit` on a remote service, the error will be silently ignored.
This may be problematic for services that must keep track of exactly which units are present in each application. One possible solution is using monsterqueue to keep retrying the `unbind-unit` request.

A possible complementary solution is having a new endpoint on services that will be called with a list of all existing units. This request would allow tsuru to tell the service to only consider these new units and ignore all previously binded ones.

**Comment by andrestc** [comment]
This is handled by the BindSyncer, added on https://github.com/tsuru/tsuru/pull/1645
