### ISSUE TITLE
cmd/tsuru: email validation for token-show, user-create and user-remove don't match

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1442]
I tried to create a user for application access (through token). I created the use successfully, but when trying to generate the token, I got an invalid email error:

```
% tsuru user-create test+testing@example.com
Password:
Confirm:
User "test+testing@example.com" successfully created!
% tsuru token-show -u test+testing@example.com
Error: invalid email
```

So I decided to remove the user and create again in some other format. Surprise, surprise:

```
% tsuru user-remove test+testing@example.com
Are you sure you want to remove the user "test+testing@example.com" from tsuru? (y/n) y
Error: invalid email
```

**Comment by guilhermebruzzi** [comment]
The problem was a issue on tsuru-client, this PR should fix it: https://github.com/tsuru/tsuru-client/pull/19
