### ISSUE TITLE
Persistent storage for components

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1462]
Currently, tsuru installer bind mounts a host directory for each of its core components. This data will be host dependent, which means it will be lost if the node goes down or if the service tasks is rescheduled to a different node. Some components can't have this behavior: mongo and registry, primarily.

Currently, swarm does not provide a way to solve this issue, meaning we need to rely on 3rd party tools, like [flocker](https://github.com/ClusterHQ/flocker), [REX-ray](https://github.com/emccode/rexray), and others. We should investigate this tools and integrate the installer with the one that fits the best(support for backends on most of docker-driver supported iaas is desired).

**Comment by andrestc** [comment]
One way to support this would be to mount volumes on the swarm services to store each component's data and enable sharing this data across each node using services like EBS on AWS.

We would need to implement the storage's creation on each cloud provider. The default could be as is: mounting a volume without backing it up on a storage provider.

**Comment by afranioce** [comment]
The dokku (mini-heroku) has this [feature](http://dokku.viewdocs.io/dokku/advanced-usage/persistent-storage/), it is also open-source if it can help.
I look forward to version 1.3
