### ISSUE TITLE
Installation sharing

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1464]
Currently, tsuru installer relies on docker-machine filestore, to store information about the installation: machines provisioned, certificates and more, are all stored on the local machine.

These informations should be synced to an external storage (mongodb, for instance), instead of kept only on the machine that ran `tsuru install`, so others can access information about the installation.

**Comment by guestisp** [comment]
You could use etcd if you need a shared key/value store between servers

**Comment by andrestc** [comment]
We are actually trying to share data that is stored by the tsuru client, on your local machine, once you run `tsuru install`, not between the servers. To do that, we are making the API aware of the installation done by the client and it will be responsible for storing all information regarding it. Once that is done, anyone with a tsuru client pointing to that target (and having the right privileges) will be able to manage the installation: add new hosts for the components, scale the components and etc.
