### ISSUE TITLE
Cloud bursting

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#1467]
A very usefull feature, using tsuru integrated with a IaaS would be cloud bursting.
By configuring 2 or more IaaS in tsuru, tsuru would use the "local" IaaS as default when creating new docker nodes but when local resources are full (not enough ram/cpu/space/hosts .... to spawn a new docker node), tsuru could try to spawn nodes on the second IaaS that could be AWS, DigitalOcean or anything else.

Obviously, when scaling down the node removal must start from the "external" IaaS

This allow for a potentially unlimited cloud expansion

**Comment by guestisp** [comment]
Any update about this ?

**Comment by magnotorres** [comment]
Hi @guestisp we are planning to do that next year, maybe in the second quarter

**Comment by guestisp** [comment]
Thank you
