### ISSUE TITLE
installer: wait for required components before checking the API

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1472]
When running `tsuru install`, we rely on docker swarm to pull and start our services from docker images. Sometimes pulling the images take too long (because of slow internet or docker hub rate limits) and the API is not able to start because it's required components are running ([as reported here](https://github.com/tsuru/tsuru/issues/1470#issuecomment-251207643)).

We should add some checks before [this](https://github.com/tsuru/tsuru-client/blob/master/tsuru/installer/components.go#L368) to verify if the required components are stuck having their images being pulled (`preparing` state in swam), inform the user every x seconds which components are still in that state and wait until they are done before proceding.

**Comment by IngCr3at1on** [comment]
@andrestc just glanced at the code after finding the issue from the hacktoberfest tag...

Could this not be resolved by completely the healthcheck function and calling it before any other calls?

**Comment by andrestc** [comment]
@IngCr3at1on that seems to do it, but has the draw back that we will request swarm to pull their images one by one. I think we could address that by:

1. removing the [api](https://github.com/tsuru/tsuru-client/blob/master/tsuru/installer/components.go#L36) from the slice of tsuru components, and renaming it to something like `TsuruDependencies`.
2. after looping thru the dependencies (installing them), loop thru them again [here](https://github.com/tsuru/tsuru-client/blob/master/tsuru/installer/install.go#L160) waiting for their healthchecks to pass.
3. after all dependencies healthchecks pass, call the API installation directly.

Another approach would be to start goroutines for each component installation and wait for their healthcheck to pass (but i think configuring timeouts can be a little trickier for this case)

I think I´m fine with both solutions, what do you think @IngCr3at1on?

**Comment by IngCr3at1on** [comment]
@andrestc only problem with no timeouts is that if any _one_ service never passes health checks you'll get stuck in the install loop instead of returning an error.

**Comment by andrestc** [comment]
@IngCr3at1on I agree with you, we should have timeouts of both cases. I just said it would be trickier to have them configured if we decided to do the healthchecks inside the goroutines because of the dependencies between the services(some of them will require a longer timeout). If we do the checking on the main goroutine, its essentially the same for both of my suggestions.

Maybe we can go with a 'not so long timeout' as default and expose it as some configuration for users with slow connection for e.g.

**Comment by IngCr3at1on** [comment]
@andrestc my mistake; I'd probably go the route of waiting on the main goroutine as you said. The configurable timeout is a good idea as well I think.
