### ISSUE TITLE
Mesos provisioner

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#1474]
Now that tsuru supports more than one provisioner, we can add a provisioner based on Mesos.

Mesos is a production ready cluster manager used to orchestrate a wide range of applications and services, such as web api's and even Hadoop and Cassandra.

**Comment by cezarsa** [comment]
So, we decided not to pursue this right now. The way Mesos works makes it the most challenging orchestrator to adapt to the tsuru workflow.

Using Mesos directly would involve a huge amount of work so we also considered integrating with DC/OS and Marathon APIs, however even this proved challenging. I'll try to enumerate some problems we faced, please note that there are probably some workarounds for some issues I write here, we only judged the development cost would be too high to overcome them.

1. It's only possible to authenticate to DC/OS API either interactively or through short-lived (5 days) tokens. This would make it impossible for tsuru to rely on tokens. We would have to disable authentication and rely on network ACLs to control access to the API.

2. A big part of tsuru workflow is the ability to build application images using our platforms, it's also possible to deploy pre-built images directly but that's not the main use-case for tsuru. To ensure our main use-case works we need to be able to run API calls similar to `docker commit` and `docker push`.
Neither Mesos, DC/OS nor Marathon provides a similar API. The approach used in the `kubernetes` provisioner of having a sidecar container mounting the docker socket and using it locally to commit/push could be used, but it would require using the Docker containerizer which doesn't support Pods (required for sidecar containers).

3. Being stuck with the Docker containerizer had further drawbacks, as it also doesn't support exec in a running container, which would be required for `tsuru app-run/app-shell` commands that are essential for tsuru most users.

For these reasons I'm closing this issue as we don't have any plans on continue working on Mesos integration. This may change in the future with new versions of the mentioned components being released. New issues/feature-requests can be opened then.
