### ISSUE TITLE
Kubernetes provisioner

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#1475]
Now that tsuru supports more than one provisioner, we can add a provisioner based on Kubernetes.

Kubernetes is a production ready container orchestration used by a lot of companies: http://kubernetes.io/case-studies/

**Comment by heynemann** [comment]
AWE-SO-ME!

**Comment by bgrant0607** [comment]
Let us know how we can help.

**Comment by andrewsmedina** [comment]
Hi @bgrant0607 do you want help with code?

**Comment by bgrant0607** [comment]
@andrewsmedina I was more thinking about answering questions, giving you pointers to code/docs, helping you understand the K8s roadmap if there's something you need that doesn't exist yet, etc.
