### ISSUE TITLE
IaaS: automatic VM vertical scaling 

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#1481]
Let's assume a Tsuru infrastructure built on a public IaaS like AWS or Google.
Tsuru should be able to automatically scale up/down the docker node based on the container requirements.

In example, tsuru spin up a new docker node build with 1CPU and 2GB ram.
Each app as 512MB assigned. Tsuru will then start up to 2 apps on this node (1GB total used RAM, 1GB free for the OS). When a third app is needed, tsuru should automatically scale the docker node to a bigger plan. When the third app is removed, the docker node should be scaled down.

**Comment by andrestc** [comment]
Currently tsuru already supports [memory based scaling](https://github.com/tsuru/tsuru/blob/94799c7caae966648fbaf84cd59d4b0eb06c9d51/docs/advanced_topics/node_scaling.rst#memory-based-scaling), I believe this would cover your use case.

**Comment by guestisp** [comment]
Non exactly. In this way, you create new docker nodes. I'm talking about scaling the existing node, not adding a new one.

On some IaaS (AWS or Google), add ram to an existing docker node is cheaper than spin up a new node.

You could add an hard-limit, something like 64GB. If the current docker node as < 64GB set, you add more ram to the existing node. When you reach the 64GB, you can create a new node.

64GB is just an example. You could evaluate multiple data like memory, total containers running and so on.

**Comment by andrestc** [comment]
Oh, I see. Sorry for the confusion.

I don´t think this can be done to a running instance , e.g on [AWS](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-resize.html) you must stop the instance before being able to change its instance type (and increasing ram). I think this adds some complexity and corner cases that we need to address if we would add this feature, for example: tsuru needs to move the containers out of the machine before stopping it(to prevent apps from being unavailable), what to do if this is the only node?

Maybe the way to do it is to have the auto scale being able to create a new node with a different plan, moving the containers and removing the older node. Would that have different costs than resizing an already provisioned node?

**Comment by guestisp** [comment]
Sorry for the delay
Adding new nodes with increased capacity, migrate all containers on it and removing the older one could be ok.
