### ISSUE TITLE
"platform" should not be mandatory in app-create

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#1491]
In apps that uses  Docker image deployment, the `plataform` information should not be mandatory in app-create.

tsuru should:

* Allow app-create without plataform info 
* Support to change and add platforms using `app-update`
* To track what image/platform is used in a deploy, tsuru should add app platform info in the deploy event data.

**Comment by gwmoura** [comment]
maybe, tsuru can work like heroku - https://github.com/heroku/docker-go#appjson, for the first step, tsuru can require a `tsuru.yaml` with informations about the platform.

ex:

`tsuru app-create appname python` this command will create a tsuru.yaml with:

```
# tsuru.yaml
image: tsuru/python
```

`tsuru app-create appname` this command will create a empty tsuru.yaml with:
```
# tsuru.yaml
image:
```

on git push, tsuru read the `tsuru.yaml` to know the platform and on `tsuru app-deploy` if `-i` option not passed tsuru read from `tsuru.yaml`

This is only one option, to broke this task in little tasks without lost the user behavior
