### ISSUE TITLE
router should be configured by app

### ISSUE THREAD

**Issue by andrewsmedina** [tsuru/tsuru#1492]
Currently a router is configured indirectly in the app with the plans. It is not so good because it's necessary to have a number of plans * number of routers to offers N routers to the users.

I believe that a better way is to add a relation between app and router, making possible change the router without changing the plan.

**Comment by andrestc** [comment]
On tsuru 1.3 routers will be independent of plans and will have to be set directly at the app.

This was added by several commits, from 5803b947e to e71e16adfdc and the required migration was added in 02a3806ac59.
