### ISSUE TITLE
Slow buildpack deploys

### ISSUE THREAD

**Issue by mbajur** [tsuru/tsuru#1494]
Hello!

I'm testing few paas solutions right now. I've been using dokku for few years now but my requirements changed and i'm looking for something capable of handling multi-node setup. I tried flynn so far and was (almost) pretty happy with it. Now, i'm playing with tsuru and it seems to have everything i need but there is one thing that bothers me - speed.

One of the reasons i dropped dokku was a speed of building my multi-buildpack application which uses node and ruby buildpacks. Each time, it was taking literally **50 minutes** to make a deploy of a pretty simple application. Each step of deploy was slow but the slowest one was caching a node_modules dir. Basically i had an impression that mostly node (and a size and complexity of node_modules folder) is slowing the whole thing down. When trying flynn - my multi-buildpack deploy was taking about **4 minutes (!!)** so i was super excited about that.

Right now, when playing around with tsuru, the problem came back - my multi-buildpack app (first) deploy is taking, say, 60 minutes so far and still counting. This makes me think that both dokku and tsuru are using the same or similar tool (docker?) for buildpack deployments and if that's nothing we can do anything about - i'm fine with that, it's not a moaning.

However, if that's something that can be tweaked in any way - do you guys know any [well known] facts about buildpack deployments that makes it all slow and are keen to share your thoughts on that topic? I don't even know where nor what to look for in google to even start thinking about fixing this by myself somehow. Is that normal behaviour? Is there anything i can do?

Thanks in advance!

**Comment by cezarsa** [comment]
Hey there. Do you have an example application with this multi-buildpack setup that you could share? I'd love to try reproducing it and finding where the bottleneck is. Taking more than one hour to deploy an app is certainly not expected for most cases and should be considered a bug.

That said, our buildpack platform is not the most optimized way to deploy applications on tsuru. Our focus is mostly on the specific platforms available in https://github.com/tsuru/platforms. Our `ruby` platform contains some basic support for nodejs (`node` and `npm` commands are available and you can use them on build hooks), have you tried it?

**Comment by mbajur** [comment]
Sorry, i'm affraid i'm not able to share that app with you. It's my company's commercial app :(

Oh yes, i just tried ruby platform and it took like a minute to finish. So that's impressive :) It's still a pitty that im not able to use docker/buildpack in cause of it's slowliness but i can live with that for now. Thanks!

If you need anything to let you debug that, please just let me know.
