### ISSUE TITLE
Proposal: Allow rebuilding app images with updated platform

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#1498]
This can be useful mainly in case of security vulnerabilities found on the base platform. The idea would be allowing rebuilding the application image and redeploying it without end-user intervention.

To allow this we would have to add a new build step where we would save the raw application archive. My suggestion is using the internal docker registry to save this archive building an image similar to:
```
FROM scratch
ADD apparchive.tgz /apparchive.tgz
```
And pushing it to something like `registry.tsuru/tsuru/raw-app-myapp:v1`.

The next build step would retrieve the archive from within this 'raw' image and send it to the platform image.

**Comment by guestisp** [comment]
I've asked for this some hours ago in gitter without knowing the existance of this issue 

It's a very useful feature, if not mandatory, for security reasons. Currently would be impossible to update Apache or nginx (as example) without forcing all users to push the app again.
