### ISSUE TITLE
Proposal: Add support for multiple endpoints for a single app

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#1499]
It should be possible for every process of an application to be routable. One way of implementing this is creating router backend entries for each process:

A HTTP router could return addresses in the format `<process>.<app>.<router address>.com` for each service. The same rules used currently to select which process is routable would continue existing to set the default process that would respond in `<app>.<router address>.com`.

**Comment by andrestc** [comment]
I think we could use naming conventions for this, e.g, every routable process should have it´s name prefixed with `web-`, e.g, the process `web-abc` would be adressable as  `abc.<app>.<router address>.com`.
