### ISSUE TITLE
Proposal: Inter-app binding

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#1501]
It should be possible to allow an app to bind to another app in a similar way to how apps bind to services.

Binding to another app would minimally inject the address of the binded app as an environment variable. As an example:
```
$ tsuru app-bind -a myapp otherapp
$ tsuru env-get -a myapp
TSURU_APP_otherapp_ADDRESS=otherapp.<router.address>.com
```

To further extend which variables would be binded one possibility is to also extend `tsuru.yaml` to allow setting a HTTP path on the application that would be called on bind, similar to the [bind-app route on current services](https://docs.tsuru.io/stable/services/build.html#binding-instances-to-apps) model.

Yet another consequence of binding two apps on provisioners that support networking would be creating a new network that would them be added to both apps, this way, units from both apps would have direct connectivity with DNS discovery.

**Comment by wpjunior** [comment]
Hi @cezarsa, I was reading a little bit about Network Policies (https://kubernetes.io/docs/concepts/services-networking/network-policies/), what do you think about implementing it using this concept?
