### ISSUE TITLE
Error git

### ISSUE THREAD

**Issue by framsouza** [tsuru/tsuru#1509]
Morning guys,

follow error with git push in tsuru-api
```shell
git push git@xxxxxxxx.git master
fatal: 'xxxxx.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by framsouza** [comment]
tsuru app-info

Application: fram
Description:
Repository: git@10.50.1.51:fram.git
Platform: php
Teams: rivendel
Address: fram.52.90.71.140.xip.io
Owner: fram.souza14@gmail.com
Team owner: rivendel
Deploys: 0
Pool: rivendelpool
Quota: 0/-1 units

App Plan:
+---------------+--------+------+-----------+--------+---------+
| Name          | Memory | Swap | Cpu Share | Router | Default |
+---------------+--------+------+-----------+--------+---------+
| autogenerated | 0      | 0    | 100       |        | false   |
+---------------+--------+------+-----------+--------+---------+

**Comment by andrewsmedina** [comment]
@framsouza have you added your ssh public key with `tsuru key-add`?

**Comment by framsouza** [comment]
yes, i add manually in authorized_keys ... follow file gandalf.conf

bin-path: /usr/bin/gandalf-ssh
database:
  url: 10.50.1.235:27017
  name: gandalf
git:
  bare:
    location: /var/lib/gandalf/repositories
    template: /home/git/bare-template
host: localhost
bind: 54.237.232.220:8000
uid: git
api:
  request:
    maxMemory: 2097152
repository:
  tempDir: /tmp



tsuru.conf

listen: "0.0.0.0:8080"
debug: true
host: http://0.0.0.0:8080 
git:
    api-server: http://54.237.232.220:8000
auth:
    user-registration: true
    scheme: native
database:
    url: 0.0.0.0:27017
    name: tsurudb
pubsub:
    redis-host: 0.0.0.0
    redis-port: 6379
queue:
    mongo-url: 0.0.0.0:27017
    mongo-database: queuedb
provisioner: docker
docker:
    router: hipache
    collection: docker_containers
    repository-namespace: tsuru
    deploy-cmd: /var/lib/tsuru/deploy
    bs:
        image: tsuru/bs:v1
        reporter-interval: 10
        socket: /var/run/docker.sock
    cluster:
        storage: mongodb
        mongo-url: 0.0.0.0:27017
        mongo-database: cluster
    run-cmd:
        bin: /var/lib/tsuru/start
        port: "8888"
    ssh:
        add-key-cmd: /var/lib/tsuru/add-key
        user: ubuntu
routers:
    hipache:
        type: hipache
        domain: 54.157.55.191
        redis-server: 0.0.0.0:6379
iaas:
  default: ec2
  node-protocol: http
  node-port: 2375
  ec2:
    key-id: xxxx
    secret-key: xxxxxx

**Comment by andrewsmedina** [comment]
@framsouza you should add the key using tsuru client. add it manually should not works

**Comment by accbel** [comment]
Hey @framsouza 

Did you install Gandalf **after** creating cluster's root user? I had this same issue on my Tsuru setup (API installation, root-user creation and tsuru-dashboard deploy) and I got it solved after executing "tsurud gandalf-sync" just after Gandalf installation. I think it's worth trying

**Comment by ArxdSilva** [comment]
@framsouza due to inactivity and lack of answer we'll close It, feel free to comment about this and we'll be glad to help you solving It.
