### ISSUE TITLE
installer: port tcp/8080 not opened on Google Cloud

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#1510]
In Google Cloud, all ports are closed by default.

docker-machine automatically open the needed ports for itself, but Tsuru doesn't the same for its own ports (like 8080 needed by Tsuru API)

This break the install at `Waiting for Tsuru API to become responsive...` phase.

If Tsuru should automatically open the needed ports, a fix must be made. Otherwise, some docs must be wrote telling users to manually open ports in Google Cloud configuration.

I think would be better to let users manually opening ports. I don't like the idea to have a security configuration like the firewall customized by a software without users control.

**Comment by andrestc** [comment]
Thanks for reporting @guestisp. Tsuru relies on the docker-machine driver to be able to open those ports, supplying the `--<driver-name>-open-port` to the driver and opening the needed doors.

To be able to automatically open this port (as done on the azure and ec2 drivers), we should add support to this flag on the google driver (in the docker/machine repo) as tracked by [this issue](https://github.com/docker/machine/issues/3642).

A note about manually opening the ports, when drivers do not support the flag, should probably be added to this [docs section](https://docs.tsuru.io/stable/experimental/installer.html#security).

**Comment by andrestc** [comment]
[Docker machine PR waiting for approval](https://github.com/docker/machine/pull/3928).

**Comment by andrestc** [comment]
As of [fe13182a2](https://github.com/tsuru/tsuru-client/commit/fe13182a299eb9d2617a4f06fda7f3e977e6964c) `tsuru install` will automatically open the `8080` port on google cloud.
