### ISSUE TITLE
tsuru-client: add support to ignore files in app-deploy

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru#1512]
If you run `tsuru app-deploy .`, it tries to deploy the whole directory, including `.git`, which may be huge and probably unwanted.

It would be nice if `tsuru app-deploy` command supported a `.gitignore`-style file (maybe `.tsuruignore`?). Besides `.git`, it could list test files, documentation and local environment setup files, making the app image smaller.

**Comment by andrewsmedina** [comment]
I'm +1 for this issue. But, we should decide how it will be configured. We have some options:

* use .gitignore
* create a new ignore file '.tsuruignore'
* add this config in tsuru.yml
* all of the above. We can have a config 'ignorefile' in tsuru.yml. By default we can use .tsuruignore. But this conf can be defined as .gitignore.

**Comment by gwmoura** [comment]
I think better use tsuru.yml for this config. How we use to deploy app, the .gitignore can ignore paths or files used in production. Normally config files and vendor paths are added on .gitignore

**Comment by andrestc** [comment]
Im +1 for the `.tsuruignore` file without any configuration in tsuru.yml as first approach

**Comment by guestisp** [comment]
Why not packing the app via `git-archive` ? This will skip the `.git/` directory and any other ignored files.

You can also add additional files to be ignored in the export by "tagging" them via git attribute `export-ignore` https://git-scm.com/docs/gitattributes
