### ISSUE TITLE
Fail to deploy via Gandalf

### ISSUE THREAD

**Issue by accbel** [tsuru/tsuru#1515]
Hey guys,

I'm trying to deploy an app via Gandalf and i'm stuck on a pre-receive hook issue. I'm getting the following error.

vagrant@vagrant-ubuntu-trusty-64:~/tsuru-django-sample$ git push tsuru master 
Counting objects: 169, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (81/81), done.
Writing objects: 100% (169/169), 22.94 KiB | 0 bytes/s, done.
Total 169 (delta 73), reused 169 (delta 73)
remote: + '[' '' ']'
remote: + '[' -d /etc/profile.d ']'
remote: + for i in '/etc/profile.d/*.sh'
remote: + '[' -r /etc/profile.d/bash_completion.sh ']'
remote: + . /etc/profile.d/bash_completion.sh
remote: ++ '[' -n '4.3.11(1)-release' -a -n '' -a -z '' ']'
remote: + for i in '/etc/profile.d/*.sh'
remote: + '[' -r /etc/profile.d/Z97-byobu.sh ']'
remote: + . /etc/profile.d/Z97-byobu.sh
remote: ++ '[' -n '' ']'
remote: ++ '[' '' = byobu ']'
remote: ++ '[' '' = byobu-screen ']'
remote: ++ '[' '' = byobu-tmux ']'
remote: + for i in '/etc/profile.d/*.sh'
remote: + '[' -r /etc/profile.d/Z99-cloud-locale-test.sh ']'
remote: + . /etc/profile.d/Z99-cloud-locale-test.sh
remote: ++ '[' -f /home/git/.cloud-locale-test.skip -o -f /var/lib/cloud/instance/locale-check.skip ']'
remote: ++ locale
remote: ++ locale_warn
remote: ++ local bad_names= bad_lcs= key= val= var= vars=
remote: ++ local w1 w2 w3 w4 remain
remote: ++ '[' '' = zsh ']'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ bad_names=' LC_ALL'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LANG
remote: ++ val=en_US.UTF-8
remote: ++ val=en_US.UTF-8
remote: ++ val=en_US.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LANGUAGE
remote: ++ val=
remote: ++ val=
remote: ++ val=
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE='
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_CTYPE
remote: ++ val='"en_US.UTF-8"'
remote: ++ val='en_US.UTF-8"'
remote: ++ val=en_US.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_NUMERIC
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_TIME
remote: ++ val='"en_US.UTF-8"'
remote: ++ val='en_US.UTF-8"'
remote: ++ val=en_US.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_COLLATE
remote: ++ val='"en_US.UTF-8"'
remote: ++ val='en_US.UTF-8"'
remote: ++ val=en_US.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_MONETARY
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=pt_BR.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_MESSAGES
remote: ++ val='"en_US.UTF-8"'
remote: ++ val='en_US.UTF-8"'
remote: ++ val=en_US.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=pt_BR.UTF-8 LC_MESSAGES=en_US.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_PAPER
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=pt_BR.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_PAPER=pt_BR.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_NAME
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=pt_BR.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_PAPER=pt_BR.UTF-8 LC_NAME=pt_BR.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_ADDRESS
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=pt_BR.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_PAPER=pt_BR.UTF-8 LC_NAME=pt_BR.UTF-8 LC_ADDRESS=pt_BR.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_TELEPHONE
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=pt_BR.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_PAPER=pt_BR.UTF-8 LC_NAME=pt_BR.UTF-8 LC_ADDRESS=pt_BR.UTF-8 LC_TELEPHONE=pt_BR.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_MEASUREMENT
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=pt_BR.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_PAPER=pt_BR.UTF-8 LC_NAME=pt_BR.UTF-8 LC_ADDRESS=pt_BR.UTF-8 LC_TELEPHONE=pt_BR.UTF-8 LC_MEASUREMENT=pt_BR.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_IDENTIFICATION
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ val=pt_BR.UTF-8
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=pt_BR.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_PAPER=pt_BR.UTF-8 LC_NAME=pt_BR.UTF-8 LC_ADDRESS=pt_BR.UTF-8 LC_TELEPHONE=pt_BR.UTF-8 LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=pt_BR.UTF-8'
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ case "$w1" in
remote: ++ key=LC_ALL
remote: ++ val=
remote: ++ val=
remote: ++ val=
remote: ++ vars=' LANG=en_US.UTF-8 LANGUAGE= LC_CTYPE=en_US.UTF-8 LC_NUMERIC=pt_BR.UTF-8 LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_MONETARY=pt_BR.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_PAPER=pt_BR.UTF-8 LC_NAME=pt_BR.UTF-8 LC_ADDRESS=pt_BR.UTF-8 LC_TELEPHONE=pt_BR.UTF-8 LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=pt_BR.UTF-8 LC_ALL='
remote: ++ read -r w1 w2 w3 w4 remain
remote: ++ for bad in '$bad_names'
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LANG ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LANGUAGE ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_CTYPE ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_NUMERIC ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_TIME ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_COLLATE ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_MONETARY ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_MESSAGES ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_PAPER ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_NAME ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_ADDRESS ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_TELEPHONE ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_MEASUREMENT ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_IDENTIFICATION ']'
remote: ++ continue
remote: ++ for var in '${vars}'
remote: ++ '[' LC_ALL = LC_ALL ']'
remote: ++ val=
remote: ++ '[' '' = '' ']'
remote: ++ bad_lcs=' '
remote: ++ break
remote: ++ bad_lcs=
remote: ++ '[' -n '' ']'
remote: ++ return 0
remote: ++ unset locale_warn
remote: + unset i
remote: + export ARCHIVE_SERVER_READ=http://192.168.56.105:3232 ARCHIVE_SERVER_WRITE=http://127.0.0.1:3131
remote: + ARCHIVE_SERVER_READ=http://192.168.56.105:3232
remote: + ARCHIVE_SERVER_WRITE=http://127.0.0.1:3131
remote: + export TSURU_HOST=http://192.168.56.105:8080
remote: + TSURU_HOST=http://192.168.56.105:8080
remote: + export TSURU_TOKEN=f25c1a5c163cb115d59b12139102ca0b6070d330
remote: + TSURU_TOKEN=f25c1a5c163cb115d59b12139102ca0b6070d330
remote: + read oldrev newrev refname
remote: + set +e
remote: + echo refs/heads/master
remote: + grep -v 'tags/master$'
remote: + grep -q '/master$'
remote: + status=0
remote: + set -e
remote: + '[' 0 = 0 ']'
remote: + COMMIT=06cbe2fdf4fe516aaa07aab4bfdae937c887627a
remote: + read oldrev newrev refname
remote: + '[' -z 06cbe2fdf4fe516aaa07aab4bfdae937c887627a ']'
remote: + APP_DIR=blog.git
remote: + APP_NAME=blog
remote: ++ python -c 'import uuid; print uuid.uuid4().hex'
remote: + UUID=4b40dbfbca1549de8fdd0848a7f1f51c
remote: + ARCHIVE_FILE_NAME=blog_06cbe2fdf4fe516aaa07aab4bfdae937c887627a_4b40dbfbca1549de8fdd0848a7f1f51c.tar.gz
remote: + git_archive_all 06cbe2fdf4fe516aaa07aab4bfdae937c887627a blog_06cbe2fdf4fe516aaa07aab4bfdae937c887627a_4b40dbfbca1549de8fdd0848a7f1f51c.tar.gz
remote: + REV=06cbe2fdf4fe516aaa07aab4bfdae937c887627a
remote: + FILE=blog_06cbe2fdf4fe516aaa07aab4bfdae937c887627a_4b40dbfbca1549de8fdd0848a7f1f51c.tar.gz
remote: ++ mktemp -d
remote: + TMP_WORK_DIR=/tmp/tmp.xi04OvPTGb
remote: + chmod 755 /tmp/tmp.xi04OvPTGb
remote: + unset GIT_DIR GIT_WORK_TREE
remote: + git clone -q /var/lib/gandalf/repositories/blog.git /tmp/tmp.xi04OvPTGb
remote: + pushd /tmp/tmp.xi04OvPTGb
remote: + git config advice.detachedHead false
remote: + git checkout 06cbe2fdf4fe516aaa07aab4bfdae937c887627a
remote: HEAD is now at 06cbe2f... Merge pull request #1 from jroqueweb/master
remote: + git submodule update --init --recursive
remote: perl: warning: Setting locale failed.
remote: perl: warning: Please check that your locale settings:
remote:         LANGUAGE = (unset),
remote:         LC_ALL = (unset),
remote:         LC_MONETARY = "pt_BR.UTF-8",
remote:         LC_ADDRESS = "pt_BR.UTF-8",
remote:         LC_TELEPHONE = "pt_BR.UTF-8",
remote:         LC_NAME = "pt_BR.UTF-8",
remote:         LC_MEASUREMENT = "pt_BR.UTF-8",
remote:         LC_IDENTIFICATION = "pt_BR.UTF-8",
remote:         LC_NUMERIC = "pt_BR.UTF-8",
remote:         LC_PAPER = "pt_BR.UTF-8",
remote:         LANG = "en_US.UTF-8"
remote:     are supported and installed on your system.
remote: perl: warning: Falling back to the standard locale ("C").
remote: perl: warning: Setting locale failed.
remote: perl: warning: Please check that your locale settings:
remote:         LANGUAGE = (unset),
remote:         LC_ALL = (unset),
remote:         LC_MONETARY = "pt_BR.UTF-8",
remote:         LC_ADDRESS = "pt_BR.UTF-8",
remote:         LC_TELEPHONE = "pt_BR.UTF-8",
remote:         LC_NAME = "pt_BR.UTF-8",
remote:         LC_MEASUREMENT = "pt_BR.UTF-8",
remote:         LC_IDENTIFICATION = "pt_BR.UTF-8",
remote:         LC_NUMERIC = "pt_BR.UTF-8",
remote:         LC_PAPER = "pt_BR.UTF-8",
remote:         LANG = "en_US.UTF-8"
remote:     are supported and installed on your system.
remote: perl: warning: Falling back to the standard locale ("C").
remote: + find -name .git -prune -exec rm -rf '{}' ';'
remote: + tar zcf /tmp/blog_06cbe2fdf4fe516aaa07aab4bfdae937c887627a_4b40dbfbca1549de8fdd0848a7f1f51c.tar.gz .
remote: + popd
remote: + rm -rf /tmp/tmp.xi04OvPTGb
remote: ++ save_archive blog_06cbe2fdf4fe516aaa07aab4bfdae937c887627a_4b40dbfbca1549de8fdd0848a7f1f51c.tar.gz
remote: ++ url=http://127.0.0.1:3131/
remote: +++ curl -sN -F archive=@/tmp/blog_06cbe2fdf4fe516aaa07aab4bfdae937c887627a_4b40dbfbca1549de8fdd0848a7f1f51c.tar.gz http://127.0.0.1:3131/
remote: ++ result='no reachable servers'
remote: ++ python
remote: Traceback (most recent call last):
remote:   File "<stdin>", line 2, in <module>
remote:   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
remote:     return _default_decoder.decode(s)
remote:   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
remote:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
remote:   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
remote:     raise ValueError("No JSON object could be decoded")
remote: ValueError: No JSON object could be decoded
remote: + archive_id=
To git@192.168.56.105:blog.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@192.168.56.105:blog.git'

I've found and followed #1377 steps with no success. Can you help me?

**Comment by gwmoura** [comment]
the problem can be here:

> remote: +++ curl -sN -F archive=@/tmp/blog_06cbe2fdf4fe516aaa07aab4bfdae937c887627a_4b40dbfbca1549de8fdd0848a7f1f51c.tar.gz http://127.0.0.1:3131/
remote: ++ result='no reachable servers'
remote: ValueError: No JSON object could be decoded

Check if your archive-server is up and listening on port 3131

**Comment by accbel** [comment]
Hi @gwmoura. Thanks for replying

Yes, all components were properly started but after some digging i've found the root cause. The message 'no reachable servers' means that archive-server cannot reach MongoDB instance.

When following the [Gandalf installation docs](https://docs.tsuru.io/stable/installing/gandalf.html) there is no mention about how to configure archive-server in a proper way when you have a distributed setup (mongodb isn't available at localhost) and a default arquive-server config file is placed at /etc/default/archive-server that points to a local MongoDB instance.

I think it's worth to append a few lines in the docs about archive-server configuration details. What you think?

Thanks for your help!

**Comment by gwmoura** [comment]
@accbel, sorry for delay, On your `tsuru.conf` file is configured to point  to your remote mongodb?
You can configure the mongodb host for archive-server passing a paramenter `-mongodb=`. 
look this link: https://github.com/tsuru/archive-server/blob/03201ff6981dbc6d5c8da02b561c70a65c4138f8/Dockerfile#L9

**Comment by accbel** [comment]
@gwmoura yeah, my `tsuru.conf` was properly configured but I didn't touch any of archive-server scripts/files except `/etc/default/archive-server` just to make it work. I've expected archive-server to work smoothly just by following the docs. Anyway, it is working now.

**Comment by gwmoura** [comment]
Great, you can close this issue now :smile:
