### ISSUE TITLE
team-create command results in Error: You don't have permission to do this action

### ISSUE THREAD

**Issue by acobster** [tsuru/tsuru#1520]
Running Tsusu 1.1.1 (within Vagrant, per [tsuru-bootstrap](https://github.com/tsuru/tsuru-bootstrap) instructions), I get the following:

```
$ git clone git@github.com:tsuru/tsuru-bootstrap.git
$ vagrant up
$ tsuru target-add dev http://192.168.50.4:8080 -s
$ tsuru user-create ctamayo@sitecrafting.com
$ tsuru login # enter creds here
$ tsuru team-create sitecrafting
Error: You don't have permission to do this action
```

I'm on macOS Sierra. Let me know if there's any other info I can provide.

Thanks!

**Comment by ArxdSilva** [comment]
@acobster Can you update your Tsuru version and try again? I did the same steps and could not get into the same output.

**Comment by acobster** [comment]
Yep, working now! Darn gremlins.
