### ISSUE TITLE
Add subcommands to tsuru-client

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1527]
Commands from `tsuru-admin` and `crane` are being merged into `tsuru-client` on version 1.2. Currently, when running `tsuru`, the user has around 140 commands to choose from. I think this can pollute the user experience.

I think we could try to split our commands into subcommands.

One possible way of grouping would be to add the `manage` subcommand to aggregate all commands that originated from `tsuru-admin` and `crane` and are mostly used by tsuru admins and service admins. This would already bring the command count (when issuing `tsuru help`) to around 80 possible commands. To run a `tsuru node-add` cmd, one would run `tsuru manage node-add`.

Another possible approach would be to group commands by targets (app, service, node, event... etc), e.g, `tsuru app list/create/remove/deploy`, `tsuru event list/info/cancel`. I think this is a more natural grouping and seems to be an approach commonly adopted by other clients, e.g, `docker service create/rm/ls...`.

Regardless of the approach adopted, we should support both ways (current and the next one) with a deprecation warning and remove on the following version.

**Comment by guilhermebr** [comment]
I agree with both changes.

separated commands are more natural and intuitive, and will decrease considerably the number of commands to list.

and group both service and admin commands into `manage` subcommand will prevent mistakes.

**Comment by cezarsa** [comment]
I like the idea of grouping by target, once upon a time I even tinkered with this idea and I can bring this code back. It had the added benefit of maintaining backwards compatibility with the current dash separated commands.

One thing to consider is that our current CLI API already has the concept of topics (try `tsuru help target`). This idea could be expanded with the creation of a topic for each target and adding documentation for each new topic as we go.

**Comment by andrestc** [comment]
We could bring that code back (I would like to maintain the compatibility for at least one version, I don't think we need to keep this forever).

I like the idea of having a help topic for each target (adding their related subcommands etc).
