### ISSUE TITLE
Routers: Support for limiting routers to specific pools

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1528]
There should be a way to control the availability of each router, e.g, 'routerA' is only available for applications in pool 'X' or 'routerB' is available for applications in all pools expect for pool 'Y'. This is useful for tsuru installations that use pools as a way to segregate environments (development and production envs, for example) and use the same separation for routers. 

This will prevent devs from making mistakes when creating their apps and is also useful when this pool segregation is used for accounting/resource segregation.

This requires #1492 to be done.

**Comment by cezarsa** [comment]
One thing we have to consider is how we're going to make this relationship happen. Currently pools already have a list of teams which are allowed to use them, I think that adding another list with possible routers would get messy.

Adding a list of possible pools to each router entry would also get messy, we'd only be moving the mess elsewhere. Imagine having a pool where a single router can be used and such router can only be used on this same pool. Every other router entry would have to include a list of all possible pools excluding this one.

Another solution would be combining a white list and black list approach. Where we would be able set the more appropriate list in each situation.

**Comment by andrestc** [comment]
> Another solution would be combining a white list and black list approach. Where we would be able set the more appropriate list in each situation.

I like the idea of being able to provide a white list or a black list. With this approach, I think it is better to keep relationship only on the router. The number of pools is probably way bigger them the number of routers and thus checking/updating this kind of information in each pool can give some maintenance burden.

Imagine having 3 different pools: `dev`, `productionA`, `productionB` and two routers `production`, `development`, we could:

- provide a whitelist to `development`, enabling it on `dev` pool
- provide a blacklist to `production`, enabling it on every pool except for the `dev` one

This way, when adding new production pools, router `production` would be automatically available. The UI would be something like this:

```
+--------------+---------+----------------+
| Name         | Type    | Availability   |
+--------------+---------+----------------+
| production   | galeb   | Excluding: dev |
+--------------+---------+----------------+
| development  | galeb   | Including: dev |
+--------------+---------+----------------+
```

A new `cmd` would need to be added to the `cli` to be able to set those lists.

**Comment by cezarsa** [comment]
Yep, great. I also think this is the way to go.

**Comment by ArxdSilva** [comment]
Wouldnt It be simpler just to `enable` on a certain environment? It'll only have access If It's enabled, this way we can avoid people getting confused.
