### ISSUE TITLE
api: should /apps include the pool name?

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#1529]
I have a use-case where we need the pool name in the list of apps, doing a ``GET /apps/<appname>`` for each app in the list is too slow, so would you consider adding the pool name to ``/apps``? Or maybe make it possible to customize the fields included in the listing?

**Comment by cezarsa** [comment]
I'd rather simply add the pool field to the list result than supporting customization of the returned fields. Customization could lead to the added complexity of either creating a pattern for allowing this or using something as convoluted as GraphQL.
