### ISSUE TITLE
Assign roles to teams

### ISSUE THREAD

**Issue by renatosis** [tsuru/tsuru#1537]
When assigning roles, theres no option to assign to teams

```
Usage: tsuru role-assign role-name user-email [context-value]

Assign an existing role to a user with some context value.

Minimum # of arguments: 2
```

**Comment by ArxdSilva** [comment]
By associating roles to teams, we should instead of just updating all users, make a bind between user-team, so whenever a user gets added to a team, It'll get It's roles and If he/she ever gets disassociated to that team, the roles will be lost.
