### ISSUE TITLE
Associate team with user

### ISSUE THREAD

**Issue by caiolenthus** [tsuru/tsuru#1545]
Hello.
I searched a lot in the documentation, Google, etc., but found no solution...
Is there a way to associate a user with a team, so that team can update the N app?

Example:

Team_Heaven: User1, User2, User3
App-Banana: Can be changed (deploy,update, etc.) only by Team_Heaven

Team_Hell: User4, User5, User6
App-Avocado: can only be changed (deploy,update, etc.) by Team_Hell

**Comment by caiolenthus** [comment]
So...
I found the solution in one of several tests I did.
Thanks anyway and, if possible, put some direct reference to this functionality in the documentation.

`tsuru role-assign team-member myuser@mydomain.com mygroup`

**Comment by ArxdSilva** [comment]
@caiolenthus thanks for the feedback! I've just added some docs about this
