### ISSUE TITLE
tsuruio: Content related page/section

### ISSUE THREAD

**Issue by ArxdSilva** [tsuru/tsuru#1562]
It would be nice for the community some part of our website dedicated to our video lectures on events (contributors talks are welcome too), so they can get more info about us without the need of searching for It out of the docs.

Some lectures:
- [Tsuru, o PaaS OpenSource](https://www.infoq.com/br/presentations/tsuru-o-paas-open-source)
- [Microservicos con Tsuru](https://www.youtube.com/watch?v=ZLHptOpWw2I)
- [Docker and Tsuru](https://www.youtube.com/watch?v=oPjnIn8MguA)
- [Deploy Demo using Tsuru](https://www.youtube.com/watch?v=uq1xCENEjPghttps://www.youtube.com/watch?v=uq1xCENEjPg)
- [Docker Node autoscale on Tsuru](https://www.youtube.com/watch?v=l6FOOnxLLiQ)
- [Tsuru - Deploys de forma fácil](https://www.youtube.com/watch?v=JxSmaiUka-I) [SLIDES](https://speakerdeck.com/rafaelhenrique/deploys-de-forma-facil-com-tsuru)
- [Rohit Nair - Tsuru: Serve it yourself](https://www.youtube.com/watch?v=jBRjb6-DIsA)
- [Tsuru pra quem sabe](https://www.youtube.com/watch?v=JX-5ehCMcT4)
- [Tsuru Live Code](https://www.youtube.com/watch?v=dC79RpifEQI)
- [Growing Up With Docker: How Docker and Tsuru Have Evolved](https://www.youtube.com/watch?v=s7pgpX3koCQ)
- [Infracoders London March 2017 Meetup](https://youtu.be/HkP_tI3D0lE?t=43m21s)
- [TSURU - FAZENDO DEPLOYS DE FORMA SIMPLES E DIVERTIDA](https://www.pycursos.com/tsuru-fazendo-deploys-de-forma-divertida/)

Articles that we were cited:
- [Looking at open source PaaS technologies](https://gdstechnology.blog.gov.uk/2015/10/27/looking-at-open-source-paas-technologies/)
- [Choosing Cloud Foundry for the Government Platform as a Service](https://governmentasaplatform.blog.gov.uk/2015/12/17/choosing-cloudfoundry/)
- [Tsuru, transformando el departamento de sistemas en un proveedor de servicios](https://tecnologia.qdqmedia.com/tsuru-transformando-el-departamento-de-sistemas-en-un-proveedor-de-servicios.html)
- [5 Open Source Cloud Platforms for the Enterprise](https://solutionsreview.com/cloud-platforms/open-source-cloud-platforms-enterprise/)
- [A EVOLUÇÃO DE UMA ARQUITETURA DISTRIBUÍDA: DO GLOBO.TV AO GLOBOSAT PLAY](https://blog.guilhermegarnier.com/evolucao-arquitetura/#/)
- [Docker na Globo.com: Usando o tsuru para escalar milhares de containers em centenas de maquinas](http://brasilia.devopsdays.com.br/program/cezar-sa/)
- [4 anos de tsuru](https://medium.com/@andrewsmedina/4-anos-de-tsuru-69e1e8bc1f22)
- [How to scale Docker containers in production](http://stackoverflow.com/questions/18285212/how-to-scale-docker-containers-in-production)
- [Cloud Computing Encyclopedia - Page 144](https://books.google.com.br/books?id=bCu9BgAAQBAJ&printsec=frontcover&hl=pt-BR#v=onepage&q&f=false)
- [PaaS or micro-PaaS for Microservices? – a simple technology review](https://holisticsecurity.io/2016/03/10/paas-for-microservices-simple-review/)
- [Tsuru on Ares - ensiie.fr](https://wiki.ares-ensiie.eu/index.php?title=Paas)
- [Google’s Go Appears on Brazilian Cloud](https://www.wired.com/2013/03/tsuru/)
- [Top Docker Tools: 51 Useful Docker Tools for Every Stage of the Development Pipeline](
https://stackify.com/top-docker-tools/)
- []()

related to: #1043, #630

**Comment by afranioce** [comment]
Its is cool! Add more vídeos on your channel youtube

**Comment by ggarnier** [comment]
I just updated the media page with a couple of links listed here.

**Comment by ArxdSilva** [comment]
As an update, this is now live: https://tsuru.io/media/
