### ISSUE TITLE
pubsub confusion

### ISSUE THREAD

**Issue by JaSei** [tsuru/tsuru#1565]
Hi I have problem with `pubsub` configuration
I see in documentation https://docs.tsuru.io/stable/reference/config.html#pubsub

I set pubsub to my redis cluster:
```
pubsub:
  redis-cluster-addrs: nod1:6379,node2:6379,node3:6379
```

but after run I see

```
WARNING: Config entry "pubsub:redis-host" is not set, default "localhost" will be used. Running "tsuru app-log -f" might not work.
```

in code I see https://github.com/tsuru/tsuru/blob/master/cmd/tsurud/checker.go#L54 only `pubsub:redis-host` check - why don't support [redis common configuration](https://docs.tsuru.io/stable/reference/config.html#config-common-redis)?

or this check only prints warning and use redis cluster?

thanks

**Comment by cezarsa** [comment]
Only the check is wrong, this warning shouldn't be printed in this case. Setting `pubsub:redis-cluster-addrs` will work as expected and the cluster will be used. Marking as bug as we need to fix redis connection settings validation in the checker.

**Comment by ArxdSilva** [comment]
@JaSei, as @cezarsa  said, It'll be loaded and It should not appear, just to add [here](https://github.com/tsuru/tsuru/blob/456a675a3aba0163195d66c14688f9a59c2c7b6c/redis/redis.go#L215) is where your config is loaded in tsuru's code.
