### ISSUE TITLE
Google Cloud

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#1570]
Last time i've checked, it was impossible to install Tsuru on Google Cloud via docker-machine.

Any progress on this ? I had issue authenticating to Google from docker-machine, even by following the official docs.

**Comment by guilhermebr** [comment]
@guestisp you can set the default application auth with:
`gcloud auth application-default login`

**Comment by ArxdSilva** [comment]
Hi @guestisp, don't know If you remember, but you recently placed here an issue similar on GCE but about adding nodes, so taking a look here might help (since you stopped answering there) solving some problems: https://github.com/tsuru/tsuru/issues/1511

**Comment by guestisp** [comment]
I'm sorry but i've missed your update. I've replied on the other issue.

**Comment by ggarnier** [comment]
@guestisp you can also check our blog for more info about deploying Tsuru to Google Cloud: https://blog.tsuru.io/tsuru-paas-on-google-cloud-platform-21640abb4386
