### ISSUE TITLE
Proposal: First class container autoscale support

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1573]
Currently, to be able to use container auto scaling on tsuru one needs to setup:

1. Setup elasticsearch or prometheus infra and 
2. bs to send metrics to ES or use cadvisor to expose metrics
3. the autoscale api (https://github.com/tsuru/tsuru-autoscale)
4. configure the datasources and etc
5. setup the autoscale inside the dashboard (https://github.com/tsuru/tsuru-autoscale-dashboard)

The autoscale API provides a generic and highly customizable way to setup `alarms` for different types of `actions`, I think it serves greatly for some specialized uses.

I propose we add some basic support for autoscaling units on tsuru core.  `bs` would send some metrics(which metrics to send would be customizable) on nodes and containers. The api would store the last value for each metric for each node/unit and also expose an api for app developers to setup the autoscale configuration. Sending the `max_memory` on each node would also be useful so to drop the `memory` metadata from nodes.

**Comment by wpjunior** [comment]
Closed due a official use of HPA, thanks
