### ISSUE TITLE
Add an option to disable terminal colors

### ISSUE THREAD

**Issue by scorphus** [tsuru/tsuru#1582]
Just like `grep`'s `--color`. Such as in:

`tsuru event-list -k app.update.swap -t app -v my-awesome-app --color=never`

**Comment by andrestc** [comment]
We already have a env that is used mostly on the tests: `TSURU_DISABLE_COLORS`, maybe we should just document it somewhere. I'm not sure we need a flag for that

**Comment by scorphus** [comment]
I wasn't aware of that env var, thanks!

About the flag itself, IMHO it's nice having it. We're already used to it, as so many cli utilities use it. It's kinda default flag.

**Comment by rafaeelaudibert** [comment]
Hello, I know it is an old issue, but maybe could I do this as part of Hacktoberfest? I think it'd be a great introduction to the codebase :D
