### ISSUE TITLE
team-info

### ISSUE THREAD

**Issue by arxdsilva** [tsuru/tsuru#1610]
Now If you need to get the users of a team, It's needed to get some infos first, such as: roles in that team and team name. The only way of doing this is by doing to each role the following:
```shell
➜ ~ tsuru user-list -r <role> -c <team>
+-----------------------------+---------------------+
| User                        | Roles               |
+-----------------------------+---------------------+
| garen@corp.globo.com        | demacia(global)     |
|                             | team-member(global) |
+-----------------------------+---------------------+
```

It would be nice to have some command that outputs the same info and much more about that team, such as: users, pools, services, apps, quota. It would be something like:
```shell
➜ ~ tsuru team-info <team>
```

**Comment by guiferpa** [comment]
I will see it, this case. Exists any issue as task for Tsuru API to serve this datas?

**Comment by ArxdSilva** [comment]
Hi @guiferpa, not all at once, there's two ways of doing this, either by making various requests to the API and normalizing It so you can model and generate a output or making a new call that will handle all this in the API.

I like the second more and It might be much easier, let me know If you need any help.

Thanks!

**Comment by guiferpa** [comment]
tsuru/tsuru-client#48
