### ISSUE TITLE
Team names should be case insensitive

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru#1613]
Currently it's possible to create multiple teams with similar names, only changing upcase and downcase chars:

```
~$tsuru team-create aaa
Team "aaa" successfully created!
~$tsuru team-create aaa
Error: team already exists
~$tsuru team-create aaA
Team "aaA" successfully created!
~$tsuru team-create AaA
Team "AaA" successfully created!
```

**Comment by andrestc** [comment]
This also happens for pools:

$ tsuru pool add test
Pool successfully registered.
$ tsuru pool add Test
Pool successfully registered.
