### ISSUE TITLE
app-run --isolated should have the same environment of regular app-run

### ISSUE THREAD

**Issue by magnotorres** [tsuru/tsuru#1615]
When you execute app-run --isolated, the application variables aren't present and even the platform variables aren't too. The user is the same in both (ubuntu)

E.g: platform-python

$ diff <(tsuru app-run -i env -o -a local-deploy|sort ) <(sleep 10;tsuru app-run  env -o -a local-deploy|sort )
0a1
> CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
3c4
< HOSTNAME=db7e3a1066fb
---
> HOSTNAME=c3fbd5acef44
8c9,10
< PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
---
> PATH=/var/lib/pyenv/shims:/var/lib/pyenv/shims:/var/lib/pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> PORT=8888
9a12,13
> PYENV_ROOT=/var/lib/pyenv
> PYENV_SHELL=bash
11a16,20
> SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt
> TEXTO=Olá Mundo! 😁
> TSURU_APPDIR=/home/application/current
> TSURU_APPNAME=local-deploy
> TSURU_APP_TOKEN=7d37b94433be64791629b32a80b9f747d12dad17
12a22
> TSURU_PROCESSNAME=worker
13a24
> port=8888

**Comment by andrestc** [comment]
This works on the swarm provisioner, so may be exclusive to the docker provisioner
