### ISSUE TITLE
client: adjust app quota commands parameters

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru#1624]
`app-quota-view` and `app-quota-change` commands should expect the app name as `-a` flag, instead of an argument.

**Comment by ArxdSilva** [comment]
Would this extend to `app-quota-change`'s `<new limit>`?

**Comment by ggarnier** [comment]
I think the syntax should be `tsuru app-quota-change <new limit> -a <app>` - although this would break the command current contract.
