### ISSUE TITLE
ppa:tsuru/ppa is not being maintained?

### ISSUE THREAD

**Issue by afranioce** [tsuru/tsuru#1652]
tsuru-client version 1.1.1
tsuru-server version 1.1.2

**Comment by morpheu** [comment]
No, ppa:tsuru/ppa is currently deprecated. Tsuru packages are now hosted by packagecloud.io - including support for Red Hat distributions. Here is the [link to tsuru doc](https://docs.tsuru.io/stable/installing/api.html) about package cloud packages installation.

**Comment by afranioce** [comment]
The [tsuru client install](https://tsuru-client.readthedocs.io/en/latest/installing.html) doc needs to be updated
