### ISSUE TITLE
Enable app deploy verbosity

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru#1666]
`app-deploy` command could support a `--verbose` flag, to show the deploy script commands being run and their output. This would help debugging errors in deploys.

**Comment by jrwren** [comment]
I'd love to tackle this. Can you give me some pointers on where to start? I spent 5 minutes looking for where `app-deploy` is at and it was not obvious.

I just realized that this is from over a year ago, maybe it is no longer applicable?

**Comment by ggarnier** [comment]
@jrwren our base platform already supports a `TSURU_PLATFORM_DEBUG` env var to show debugging info during deploys: https://github.com/tsuru/base-platform/blob/master/deploy#L7-L9. 

Maybe you could add a `-v` flag to the deploy endpoint, and when it's set, `TSURU_PLATFORM_DEBUG` env var could be set in the build container.
