### ISSUE TITLE
Support kubernetes ingress as a router

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1670]
The idea of this proposal is to add a new router type to tsuru: `ingress`. This router type will be only available to applications running on pools provisioned by kubernetes. 

Application using this router will have its routing defered to an [ingress controller](https://kubernetes.io/docs/concepts/services-networking/ingress/) in kubernetes.

Add/RemoveBackend would create/remove the ingress from the kubernetes cluster.
Add/RemoveRoutes would be noop, as the ingress controller updates its automatically.

Some examples of ingress controllers can be found [here](https://github.com/kubernetes/ingress/tree/master/controllers).
Documentation on ingress controllers can be read [here](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-controllers).
Different types of `ingress` will be registered using tsuru config.

**Comment by VitorFalcao** [comment]
Hi @andrestc I would like to work on this issue. Could you please give me some pointers, since I am new to the project?

**Comment by andrestc** [comment]
Hi @VitorFalcao, thanks for reaching out. We have decided to implement this as a standalone project: https://github.com/tsuru/kubernetes-router that implements tsuru Router API. So this issue won't be implemented as is.

I'll open some issues to kubernetes-router in a few days so others can contribute.
