### ISSUE TITLE
docs: add plugin area

### ISSUE THREAD

**Issue by arxdsilva** [tsuru/tsuru#1679]
It would be nice if we had a plugin area in the docs so the community can index it's most popular plugins and give evidence to the ones already used today. 

plugins:
- https://raw.githubusercontent.com/tsuru/admtools/master/admtools
- https://github.com/scorphus/tsuru-plugins

**Comment by rafaelfragosom** [comment]
Can I get this one? It's really simple.

**Comment by ArxdSilva** [comment]
@rafaelfragosom sure, go for it :D
