### ISSUE TITLE
Cluster pool validation

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru#1696]
`cluster-add` command doesn't validate if the pool exists

**Comment by VitorFalcao** [comment]
@ggarnier I would like to fix this bug. Do you have any tips or preference on how it should be fixed?

**Comment by ggarnier** [comment]
@VitorFalcao I think the easiest way is checking how we validate input data in other routes, like team creation:
https://github.com/tsuru/tsuru/blob/afc0745897538d611768016338c393118af2bd72/auth/team.go#L54

Please let me now if you need some help

**Comment by VitorFalcao** [comment]
Thank you. If the pool does not exist, should the function return an "errors.New()"? If so, what should be the message?

**Comment by ggarnier** [comment]
You can do something like this:

https://github.com/tsuru/tsuru/blob/f9d62e093a53bb10e3e82b96de5553fc8535f7e9/api/pool.go#L183-L186

**Comment by VitorFalcao** [comment]
Should I write a new test?

**Comment by ggarnier** [comment]
I think the best option is the third one. You can check if each pool exists before saving the cluster, and only save if all pools exist.
