### ISSUE TITLE
Cronjob as a service

### ISSUE THREAD

**Issue by kasra73** [tsuru/tsuru#1697]
tsuru support running one-off scripts with the following command:
`tsuru app-run <command> [commandarg1] [commandarg2] ... [commandargn] [-a/--app appname] [-o/--once]`
it'll be very useful if there is support for job scheduling and cronjob support. There could be following functionalities:
1. run a command at a specific time in future on one unit or a separately created container
2. run a command at a specific time in future on every app units
3. run a command every week, day, ... (maybe something like crontab) on one unit or a separately created container
4. run a command every week, day, ... (maybe something like crontab) on every units of the app

**Comment by guestisp** [comment]
+100 for this

**Comment by gfleury** [comment]
I'm looking for something similar, Kubernetes already has a cronjob resource controller. Which could be used for tsuru kubernetes provisioners. However for pure docker/tsuru this is something to discuss.
And even using kubernetes cronjob it will only match the items 1 and 3. In my case item 3 would be enough.

**Comment by gfleury** [comment]
Having a Procfile with one extra line like 

(crontab -l 2>/dev/null; echo "*/5 * * * * echo Hello > /proc/1/fd/1 2> /proc/1/fd/2") | crontab - && sudo cron -f

Also works for Ubuntu based images/platforms.... But a bit hacky, it seems not related to the original topic of the issue (having it into the command line), but I'm trying to discuss the ways of having a task scheduler within Tsuru...

**Comment by ggarnier** [comment]
It would be great to support Kubernetes CronJobs, but we would have to think how to handle these definitions for other provisioners (Docker and Swarm)

**Comment by gfleury** [comment]
For docker seems that the controller will need to be in tsuru it self, maybe with github.com/robfig/cron. Or maybe extending gc.go to support more options in scheduling. 
For docker swarm seems a bit confusing as they have a few feature requests around it but I couldn't find anything solid on that topic. 
For Kubernetes we already know.
