### ISSUE TITLE
Ubuntu 14.04 install error

### ISSUE THREAD

**Issue by mouradsm** [tsuru/tsuru#1718]
Hi, I'm trying to install tsuru-server but getting : 
> sed: can't read /etc/default/tsuru-server: No such file or directory 

command executed:
> sudo sed -i -e 's/=no/=yes/' /etc/default/tsuru-server

**Comment by yusef-ho** [comment]
I have the same issue...

**Comment by ggarnier** [comment]
@mouradsm @yusef-ho how are you running the installation?

**Comment by rof20004** [comment]
The problem is the documentation. tsuru-server do not exists anymore, the name has changed to tsurud.

/etc/default/tsurud
