### ISSUE TITLE
client: unhelpful error message for app update

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1721]
Whenever the request for an app update fails, with a bad request, we show to the user: 
`Error: You must set a flag. Use the 'app-update --help' command for more information.`

But an update can fail with a bad request for a variety of reasons, e.g, the router choosen is not available for that pool.

**Comment by guilhermebr** [comment]
fixed returning the error directly. 
commit: https://github.com/tsuru/tsuru-client/commit/4992c50f9408d3acd33b34bbc792885bbb8e792d
