### ISSUE TITLE
Tsuru do not support Procfile with end-line CRLF

### ISSUE THREAD

**Issue by guiferpa** [tsuru/tsuru#1764]
I wrote a Procfile on windows and I did the deploy. I noticed that Tsuru does not support CRLF and does not tell the reason for the error

**Comment by cezarsa** [comment]
The bug is probably on the deploy-agent project, somewhere around https://github.com/tsuru/deploy-agent/blob/master/tasks.go#L144.

**Comment by guiferpa** [comment]
I'll start working on that.

**Comment by guiferpa** [comment]
I am work it
