### ISSUE TITLE
client: cluster-remove doesn't ask for confirmation

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru#1777]
`cluster-remove` command has a `-y/--assume-yes` flag, but even if it's omitted, the command doesn't ask for confirmation before removing the cluster.

**Comment by anchepiece** [comment]
Looks like the documentation is missing as well:
http://tsuru-client.readthedocs.io/en/master/reference.html#cluster-management

I'll take a quick poke around.

**Comment by ggarnier** [comment]
@anchepiece great! Let us know if you need some help

**Comment by anchepiece** [comment]
Created a pull request here:
https://github.com/tsuru/tsuru-client/pull/65

I'll check through the command listing for similar missing checks.
Hope that helps!

**Comment by anchepiece** [comment]
@ggarnier Just a heads up, the documentation was updated and correctly reflects the client arguments (I like to follow through with any commits)
