### ISSUE TITLE
Add filters to node list

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru#1820]
Currently, node list command doesn't support filters - filtering is done only in the client

**Comment by heitorsilva** [comment]
Hello guys!

What do you mean by filtering? What should be filtered here?

I'm completely out of context / blind, but I wanna help with this issue...

**Comment by ggarnier** [comment]
Hi @heitorsilva, tsuru client has a command `tsuru node list` that lists all registered nodes. It supports a `-f` flag to filter nodes by metadata, like pool (`tsuru node list -f pool=dev`). But when you call this command, it's actually calling `/node` from tsuru api (which returns all nodes) and applying the filter in the results.

The idea is to add support to filter by metadata in the api. Take a look at the handler for this api here: https://github.com/tsuru/tsuru/blob/34ef467ab4d7e5f93dca7fcd22eb6d7e289b92d8/api/node.go#L235-L242

An example of api that supports filters is the events list: https://github.com/tsuru/tsuru/blob/34ef467ab4d7e5f93dca7fcd22eb6d7e289b92d8/api/event.go#L28

**Comment by heitorsilva** [comment]
Thank you @ggarnier! If I have more doubts, I'll ask again...

**Comment by heitorsilva** [comment]
@ggarnier sorry to bother, but I want to ask some things... I've seen that on the `eventList`, it's being used a form decoder, and it's being applied some "rules" to it, like:  
- IgnoreUnknownKeys
- IgnoreCase

1. are these rules the default for every form decoding?
2. should I use the same method to pass the filter for ListNodes? we'll receive a `filter` param and will pass it to the ListNodes?

Am I missing something, or is it really simple as that?

**Comment by ggarnier** [comment]
1. yes, we set `IgnoreUnknownKeys` and `IgnoreCase` by default in all routes
2. `ListNodes` already accepts a list of addresses. You can change the api to accept a `address` parameter and pass this value to `ListNodes` (and even accept multiple `address` parameters). But to accept other filters, we would have to change the `ListNodes` signature, and change all 3 implementations (docker, kubernetes and swarm). You can leave this part to a second PR
