### ISSUE TITLE
app-deploy fails when finds a symbolic link

### ISSUE THREAD

**Issue by acabrerisso** [tsuru/tsuru#1830]
Steps to reproduce this issue:

1 - Create a link in a folder that should be deployed
2 - Try the command ```tsuru app-deploy ...```
3 - The deploy fails

**Comment by biancarosa** [comment]
What's the expected behavior? Ignore the folder or deploy it?

**Comment by ggarnier** [comment]
I think we should include the linked contents by default. If you want to ignore it, you can add it to the [`.tsuruignore` file](https://docs.tsuru.io/latest/using/app-deploy.html#ignoring-files-and-directories).

@biancarosa do you want to take a shot at this? :)
