### ISSUE TITLE
Deploys on kubernetes/swarm do not set router healthcheck

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1893]
Deploying an app with `"healthcheck:use_in_router"` on a kubernetes pool does not register the custom healthcheck on the router (only calls to `router.SetHealthcheck` happen in `docker/actions.go`)

**Comment by andrestc** [comment]
We should probably delegate this action to the `RebuildRoutes` func, done after deploying to the provisioner. As a bonus, we should store the healthcheck data on mongo to be able to restore it when `routes rebuild` is called from the cli.

**Comment by cezarsa** [comment]
I agree that rebuild routes should be able to fix this, but I think the health check data is already in Mongo. We save it as part of the image custom data read from tsuru.yaml and sent to tsuru by the deploy-agent.
