### ISSUE TITLE
Document TSURU_TOKEN

### ISSUE THREAD

**Issue by magnotorres** [tsuru/tsuru#1901]
The environment TSURU_TOKEN allows to use tsuru cli without authentication via terminal and isn't well document

**Comment by RafaelGomides** [comment]
It is important to define in the documentation what this TOKEN is and how to achieve it?

**Comment by vinicioslc** [comment]
Sorry reviving this thread, but this documentation still necessary ??

**Comment by amandhawb** [comment]
Hi guys!
Can I take this issue? :)

**Comment by tacoelho** [comment]
hi there, just did it.
