### ISSUE TITLE
add year to app-deploy-list result

### ISSUE THREAD

**Issue by guilhermebr** [tsuru/tsuru#1952]
tsuru app-deploy-list returns the list of deploys without the year in the date.

 `tsuru app-deploy-list -a myapp`
+------------------+------------+-----------------------------+-------------------------+-------+
| Image (Rollback) | Origin     | User                        | Date (Duration)         | Error |
+------------------+------------+-----------------------------+-------------------------+-------+
| v1 (*)           | app-deploy .   | jamesATbond.gov    | **May  9 19:25:19 (01:54)** |       |
+------------------+------------+-----------------------------+-------------------------+-------+

**Comment by ggarnier** [comment]
This was fixed in tsuru/tsuru-client#79 :

```
tsuru app-deploy-list -a myapp
+------------------+------------+-----------------+-----------------------------+-------+
| Image (Rollback) | Origin     | User            | Date (Duration)             | Error |
+------------------+------------+-----------------+-----------------------------+-------+
| v1 (*)           | app-deploy | jamesATbond.gov | 09 May 18 19:25 -03 (01:54) |       |
+------------------+------------+-----------------+-----------------------------+-------+
```
