### ISSUE TITLE
Support for triggering integration tests of PRs

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1989]
Currently we trigger daily integration tests for the `master` branch, whenever there is a new commit on a `release-*` branch and for new tags. We should introduce a way to trigger integration tests for a particular PR.

We can start by always building an API docker image in a different hub repository and building a bot that could be called by someone on `tsuru` org to trigger the test using that image. The result should be posted as a comment on the PR.

**Comment by auyer** [comment]
I am under the impression that this is configured in the Travis Web UI, not in the file.
