### ISSUE TITLE
Swagger spec for tsuru API endpoints

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#1992]
We should provide a swagger 2.0 spec for the tsuru API. This spec can be used to generate clients for different languages.

A preliminary spec is in: https://github.com/tsuru/tsuru/blob/master/docs/reference/api.yaml

I'll add a list with the pending endpoints in the future, so we can track the progress.

Endpoints missing from spec:

- [ ] GET: /
- [ ] GET: /app/{}/routers
- [ ] POST: /app/{}/routers
- [ ] DELETE: /app/{}/routers/{}
- [ ] PUT: /app/{}/routers/{}
- [x] DELETE: /apps/{}
- [ ] GET: /apps/{}
- [ ] PUT: /apps/{}
- [ ] POST: /apps/{}/build
- [ ] DELETE: /apps/{}/certificate
- [ ] GET: /apps/{}/certificate
- [ ] PUT: /apps/{}/certificate
- [ ] DELETE: /apps/{}/cname
- [ ] POST: /apps/{}/cname
- [ ] POST: /apps/{}/deploy
- [ ] POST: /apps/{}/deploy/rebuild
- [ ] POST: /apps/{}/deploy/rollback
- [ ] PUT: /apps/{}/deploy/rollback/update
- [ ] POST: /apps/{}/diff
- [ ] DELETE: /apps/{}/env
- [ ] GET: /apps/{}/env
- [ ] DELETE: /apps/{}/lock
- [ ] GET: /apps/{}/log
- [ ] POST: /apps/{}/log
- [ ] GET: /apps/{}/metric/envs
- [x] GET: /apps/{}/quota
- [x] PUT: /apps/{}/quota
- [x] POST: /apps/{}/restart
- [ ] POST: /apps/{}/routes
- [ ] POST: /apps/{}/run
- [ ] GET: /apps/{}/shell
- [ ] POST: /apps/{}/sleep
- [ ] POST: /apps/{}/start
- [ ] POST: /apps/{}/stop
- [ ] DELETE: /apps/{}/teams/{}
- [ ] PUT: /apps/{}/teams/{}
- [ ] DELETE: /apps/{}/units
- [ ] PUT: /apps/{}/units
- [ ] POST: /apps/{}/units/register
- [ ] POST: /apps/{}/units/{}
- [ ] POST: /auth/login
- [ ] GET: /auth/saml
- [ ] POST: /auth/saml
- [ ] GET: /auth/scheme
- [ ] GET: /autoscale
- [ ] GET: /autoscale/config
- [ ] GET: /autoscale/rules
- [ ] POST: /autoscale/rules
- [ ] DELETE: /autoscale/rules/{}
- [ ] POST: /autoscale/run
- [ ] GET: /constraints
- [ ] PUT: /constraints
- [ ] GET: /debug/goroutines
- [ ] GET: /debug/pprof
- [ ] GET: /debug/pprof/cmdline
- [ ] GET: /debug/pprof/profile
- [ ] GET: /debug/pprof/symbol
- [ ] GET: /debug/pprof/trace
- [ ] GET: /deploys
- [ ] GET: /deploys/{}
- [ ] POST: /docker/container/{}/move
- [ ] POST: /docker/containers/move
- [ ] GET: /docker/healing
- [ ] GET: /docker/logs
- [ ] POST: /docker/logs
- [ ] GET: /docker/node/apps/{}/containers
- [ ] GET: /docker/nodecontainers
- [ ] POST: /docker/nodecontainers
- [ ] DELETE: /docker/nodecontainers/{}
- [ ] GET: /docker/nodecontainers/{}
- [ ] POST: /docker/nodecontainers/{}
- [ ] POST: /docker/nodecontainers/{}/upgrade
- [ ] GET: /events
- [ ] GET: /events/blocks
- [ ] POST: /events/blocks
- [ ] DELETE: /events/blocks/{}
- [ ] GET: /events/kinds
- [ ] GET: /events/{}
- [x] POST: /events/{}/cancel
- [ ] DELETE: /healing/node
- [ ] GET: /healing/node
- [ ] POST: /healing/node
- [ ] GET: /healthcheck
- [ ] GET: /iaas/machines
- [ ] DELETE: /iaas/machines/{}
- [ ] GET: /iaas/templates
- [ ] POST: /iaas/templates
- [ ] DELETE: /iaas/templates/{}
- [ ] PUT: /iaas/templates/{}
- [ ] GET: /info
- [ ] GET: /install/hosts
- [ ] POST: /install/hosts
- [ ] GET: /install/hosts/{}
- [x] POST: /node
- [ ] POST: /node/rebalance
- [ ] POST: /node/status
- [x] GET: /node/{}
- [ ] GET: /permissions
- [ ] GET: /plans
- [ ] POST: /plans
- [ ] DELETE: /plans/{}
- [x] GET: /platforms
- [x] POST: /platforms
- [x] DELETE: /platforms/{}
- [x] PUT: /platforms/{}
- [x] GET: /pools
- [x] POST: /pools
- [x] DELETE: /pools/{}
- [x] PUT: /pools/{}
- [ ] DELETE: /pools/{}/team
- [ ] POST: /pools/{}/team
- [x] GET: /provisioner/clusters
- [x] POST: /provisioner/clusters
- [x] GET: /provisioner/clusters/{}
- [x] POST: /provisioner/clusters/{}
- [ ] DELETE: /role/default
- [ ] GET: /role/default
- [ ] POST: /role/default
- [ ] GET: /roles
- [ ] POST: /roles
- [ ] PUT: /roles
- [ ] DELETE: /roles/{}
- [ ] GET: /roles/{}
- [ ] POST: /roles/{}/permissions
- [ ] DELETE: /roles/{}/permissions/{}
- [ ] POST: /roles/{}/user
- [ ] DELETE: /roles/{}/user/{}
- [ ] GET: /routers
- [ ] GET: /services
- [ ] POST: /services
- [x] GET: /services/instances
- [ ] *: /services/proxy/service/{}
- [ ] DELETE: /services/{}
- [ ] GET: /services/{}
- [ ] PUT: /services/{}
- [ ] GET: /services/{}/doc
- [ ] PUT: /services/{}/doc
- [ ] POST: /services/{}/instances
- [ ] DELETE: /services/{}/instances/permission/{}/{}
- [ ] PUT: /services/{}/instances/permission/{}/{}
- [x] DELETE: /services/{}/instances/{}
- [x] GET: /services/{}/instances/{}
- [x] PUT: /services/{}/instances/{}
- [ ] GET: /services/{}/instances/{}/status
- [ ] DELETE: /services/{}/instances/{}/{}
- [ ] PUT: /services/{}/instances/{}/{}
- [ ] GET: /services/{}/plans
- [ ] *: /services/{}/proxy/{}
- [ ] DELETE: /services/{}/team/{}
- [ ] PUT: /services/{}/team/{}
- [ ] POST: /swap
- [x] GET: /teams
- [x] POST: /teams
- [x] DELETE: /teams/{}
- [x] GET: /teams/{}
- [x] POST: /teams/{}
- [x] DELETE: /users
- [x] GET: /users
- [x] POST: /users
- [x] GET: /users/api-key
- [x] POST: /users/api-key
- [x] GET: /users/info
- [x] GET: /users/keys
- [x] POST: /users/keys
- [x] DELETE: /users/keys/{}
- [x] PUT: /users/password
- [x] DELETE: /users/tokens
- [x] POST: /users/{}/password
- [x] GET: /users/{}/quota
- [x] PUT: /users/{}/quota
- [x] POST: /volumes
- [x] GET: /{}/node
- [x] PUT: /{}/node
- [x] DELETE: /{}/node/{}
- [ ] GET: /{}/node/{}/containers

List generated with: 
`comm -23 <(tsuru-api-docs | yq '.' | jq -r '.handlers[] | .method + ": " + .path' | sed 's/{[^}]*}/{}/g' | sort) <(cat docs/reference/api.yaml | yq . | jq -r '.paths | keys[] as $k | "\(.[$k] | . | keys[] | ascii_upcase): \($k)"' | grep -iv parameters | sed 's/{[^}]*}/{}/g' | sed 's/[[:alnum:]]\.[[:alnum:]]//' | sed 's|//|/|' | sort) | sort -k2`

**Comment by gfleury** [comment]
I've done some swagger mapping to generate https://github.com/gfleury/tsuru-client-java
but now IDK where is it.. hahaha I will look into my personal laptop...

**Comment by askalik** [comment]
Is the list of help wanted up to date?  I can take a handful
