### ISSUE TITLE
Consider alternatives to docker/machine

### ISSUE THREAD

**Issue by andrestc** [tsuru/tsuru#2125]
Docker-machine is now officially in maintenance mode: https://github.com/docker/machine/issues/4537.

We should consider using one of its alternatives, such as https://github.com/machine-drivers/machine (https://github.com/machine-drivers/machine/issues/4) or maybe move to a different approach such as using linuxkit (https://github.com/linuxkit/linuxkit).

**Comment by ernani** [comment]
How is this being perceived? Do we have something already in the roadmap? What would be the main challenges going forward with each of these?

**Comment by andrestc** [comment]
We haven't been able to experiment with any of the alternatives. I think the main challenge is to find a library that is able to abstract away many cloud providers behind a common interface.

If docker/machine still receives bug fixes, I guess it's okay to keep it until an obviously better solution is created by the community.
