### ISSUE TITLE
tsuru.yaml location for image deploys

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#2133]
Currently tsuru searchs for a `tsuru.yaml` file in `/home/application/current` (and some variations) in image deploys. However, we search for `Procfile` in many other additional locations, including `/`.

We should standardize a set of locations to look for both `Procfile` and `tsuru.yaml` files inside an image.

**Comment by guilhermebr** [comment]
We can also accept a env with the path to Procfile and tsuru.yaml, like in Honcho: https://honcho.readthedocs.io/en/latest/using_procfiles.html
