### ISSUE TITLE
Storing app's sensitive info in database

### ISSUE THREAD

**Issue by nettoclaudio** [tsuru/tsuru#2151]
We are storing some sensitive infos about apps in our database in plain-text. This is a security bad smell. I would like to contribute to change that approach, below I am describing my core idea.

### Idea
For now, I'm focusing on private environment vars (e.g., passed by `tsuru env-set -p` command).

At Tsuru API config file should exist a secret data ("secret"), only API must know that data. That will be used for encrypting the sensitive data before store it in MongoDB. On the other hand, the Tsuru will decrypt the data before "sending" it to docker-cluster, e.g. Does make sense?

### Questions
Before diving into the code, I've some questions about how to implement it on Tsuru workflow.

* How could we maintain the compatibility with older versions?
* What is the best shuffle strategy when a secret compromise occurs?
* Does any component rely on Tsuru events data to get this private data?

**Comment by morpheu** [comment]
Probably also could be a good idea when running `app run/shell` lookup for private vars and obfuscate them to final user - `docker exec` has such mechanism to overlap vars but unfortunately `kubectl exec` has lack of it :(
