### ISSUE TITLE
client: app info doesn't show binded volumes

### ISSUE THREAD

**Issue by ggarnier** [tsuru/tsuru#2168]
`app info` command could show information about the volumes that are binded to that app. Currently the only way to check this is running `volume list` command and searching for the app name.

**Comment by theag3nt** [comment]
I'll have a look at this if you don't mind.

**Comment by ayr-ton** [comment]
@theag3nt Any findings on this one?

**Comment by theag3nt** [comment]
@ayr-ton Not much yet. I had some trouble setting up a full build and test environment with `tsuru-bootstrap`. I've read it's deprecated, but as it's still included in the documentation I expected it to mostly work. Did some small fixes, but still stuck at the dashboard install. But I think I'll let it go, and I either try the `docker-compose` method, or set up a VM with the installer.

Nonetheless, I still want to implement a fix, I was just a bit delayed. 🙂

**Comment by ayr-ton** [comment]
@theag3nt Hmmm... maybe there's an opportunity to updated the README.md providing new getting started instructions. \o/

**Comment by theag3nt** [comment]
@ayr-ton The README is probably fine, I've just jumped straight to the Contribution chapter of the documentation where Vagrant with tsuru-bootstrap is still listed as an option. Maybe that part of the documentation could be improved.

**Comment by ggarnier** [comment]
@theag3nt probably the easiest way to run a development environment is using docker compose: https://docs.tsuru.io/stable/contributing/compose.html

You could also try tsuru installer: https://docs.tsuru.io/stable/installing/using-tsuru-installer.html

If you find something is missing, confusing or outdated in our docs, feel free to contribute to it also, we would really appreciate!

**Comment by theag3nt** [comment]
@ggarnier Thanks, I've managed to setup an environment with `docker-compose` and `minikube`. It wasn't easy but now I have an application with a bound volume, so I can at least reproduce the current situation.

I had a look in the source code for the client's `app-info` and `volume-list` commands and the server's `/apps/<app>` and `/volumes` endpoints. As I see there is currently no direct way of filtering the volume list before it's returned by the API. At a first glance, I think there are two possibilities:

1. Extend the `/volume` endpoint with an `app` parameter (like some other endpoints) so it can return only the volumes currently bound to the specified app. I will look into this and propose a more detailed solution if this is preferred.
2. Filter the list of all volumes from `/volume` endpoint on the client side. This is much easier I think.

Either way, the `app-info` command will have to be extended by adding one more API call to the server (`/volumes` endpoint), and adding the results to the printed output. Mostly affecting `AppInfo.Run()`, `AppInfo.Show()`, `app` and `app.String()`.

What do you think?

**Comment by ggarnier** [comment]
I think listing all volumes and filtering on the client may not be a good option, as the number of volumes could be really large.

I vote for changing the volumes api to support filtering by binded app, and adding this call to the client.

**Comment by andrestc** [comment]
I agree on filtering on the API, but we might need to also filter on the client just to make sure that a newer client doesn't show all existent volumes if the user is running older version of the API (one that does not support the filter).

**Comment by 123bless** [comment]
Change
