### ISSUE TITLE
Error on tsuru installer

### ISSUE THREAD

**Issue by vitormcruz** [tsuru/tsuru#2204]
As described by https://docs.tsuru.io/stable/installing/using-tsuru-installer.html, I installed tsuru client and then tried ```tsuru install-create```, but then I got 

> tsuru: "install-create" is not a tsuru command. See "tsuru help".

Error or documentation is wrong?

**Comment by ggarnier** [comment]
The command is correct. Which version of tsuru-client are you using? You can check with `tsuru version`.

**Comment by guilhermebr** [comment]
@vitormcruz Have you tried with the last version of tsuru-client?

**Comment by vitormcruz** [comment]
I am sorry for the delay, yes, I was just following the getting started
instructions with a new created VM.
