### ISSUE TITLE
Error: error installing Tsuru API: failed to connect to http://192.168.99.101:8080

### ISSUE THREAD

**Issue by alizowghi** [tsuru/tsuru#2217]
Hi
tsuru install says : 

`Error: error installing Tsuru API: failed to connect to http://192.168.99.101:8080: Maximum number of retries (60) exceeded`

tsuru version 1.1.1.

**Comment by ggarnier** [comment]
How did you do the installation? Could you try with newer tsuru version? Version 1.1.1 is really old.

**Comment by ggarnier** [comment]
This is probably the same as #2221 . Please try this workaround: https://github.com/tsuru/tsuru/issues/2221#issuecomment-440746601
