### ISSUE TITLE
Problem install.

### ISSUE THREAD

**Issue by yehudimikhael** [tsuru/tsuru#2218]
[](url)
I am having trouble to do the installation on macbook. The installation is no more than "failed to connect ....".
Entering inside the machine in virtualbox I noticed that the tsuru / api container does not start the same error.

Tsuru Version 1.6.0 

![screen shot 2018-11-08 at 17 38 16](https://user-images.githubusercontent.com/8180127/48223005-2b334e80-e37d-11e8-9bdb-6c5dd3cfdab4.png)
![screen shot 2018-11-08 at 17 38 34](https://user-images.githubusercontent.com/8180127/48223006-2b334e80-e37d-11e8-935c-61f0ec3f20ef.png)

Trying to do a docker-compose straight from the clone I get this error:

![screen shot 2018-11-09 at 10 40 37](https://user-images.githubusercontent.com/8180127/48264174-bf4df600-e40f-11e8-87fd-dafa82b87b42.png)

**Comment by yehudimikhael** [comment]
Trying to do a docker-compose straight from the clone I get this error:

![screen shot 2018-11-09 at 10 40 37](https://user-images.githubusercontent.com/8180127/48263086-0d60fa80-e40c-11e8-8529-c859b0509fb1.png)

**Comment by guilhermebr** [comment]
@yehudimikhael I will check about the `install-create` error.

about docker-compose, you can follow the steps covered in the docs: https://docs.tsuru.io/master/contributing/compose.html

**Comment by yehudimikhael** [comment]
Thank @guilhermebr.

**Comment by yehudimikhael** [comment]
@guilhermebr But this link is for installation in linux environment. Are there any for Mac? Why am I getting error with / pkg / linux_amd64 using OS X.

![screen shot 2018-11-09 at 11 27 37](https://user-images.githubusercontent.com/8180127/48265291-49e42480-e413-11e8-90fe-cc2752b7c1a4.png)

**Comment by guilhermebr** [comment]
@yehudimikhael what macos version?

**Comment by yehudimikhael** [comment]
@guilhermebr  High Sierra

**Comment by ggarnier** [comment]
@yehudimikhael we just made a small fix in the build script (#2219). Can you checkout the master branch and try again?

**Comment by yehudimikhael** [comment]
@ggarnier it's working.

But if you can change port 22 of tsuru_gandalf_1 then I had to disable the remote service on my mac to work.

![screen shot 2018-11-09 at 12 11 02](https://user-images.githubusercontent.com/8180127/48267103-90884d80-e418-11e8-8b4c-68ad47809511.png)



After you disable the os x remote service. It worked

![screen shot 2018-11-09 at 12 12 59](https://user-images.githubusercontent.com/8180127/48267190-d513e900-e418-11e8-813b-905337db6bcd.png)

**Comment by yehudimikhael** [comment]
@guilhermebr 
I noticed that the api container does not start. He runs and leaves.

![screen shot 2018-11-09 at 12 21 01](https://user-images.githubusercontent.com/8180127/48267623-f3c6af80-e419-11e8-9c44-d70d2c87088c.png)
