### ISSUE TITLE
Service Binding: Invalid Response

### ISSUE THREAD

**Issue by diaopk** [tsuru/tsuru#2233]
Hi! I am pretty new to this platform. I am trying to bind a mongoDB service to my node.js app but I am getting error saying that I sent an invalid response. The following is what I have done:

I added a service using this command:
`tsuru service-create manifest.yaml`

with these values:
```
id: mongodb
username: admin@example.com
password: admin123
team: admin
endpoint:
  production: http://node.192.168.99.100.nip.io
```

then I add a service instance:
`tsuru service-instance-add mongodb mongodb_instance -t admin`

and bind the service to my app:
`tsuru service-instance-bind mongodb mondodb_instance -a myapp`

However, the error said:
```
---- Setting 4 new environment variables ----


---- Starting 1 new unit [web: 1] ----
 ---> Started unit 3b1806ed25 [web]

---- Binding and checking 1 new unit ----

**** ROLLING BACK AFTER FAILURE ****
 ---> Failed to bind the instance "mongodb/mongodb_instance" to the unit "192.168.99.100": invalid response:  (code: 503) <---

---- Destroying 1 created unit ----
 ---> Destroyed unit 3b1806ed25 [web]
Error: Failed to bind the instance "mongodb/mongodb_instance" to the unit "192.168.99.100": invalid response:  (code: 503) ("mongodb_instance" is not implemented for t
his service)
```

This is how I handled the request in node.js:
```
app.post(`/resources/mongodb_instance/bind-app`, (req, res) => {
  res.status(201).set({
    "Content-Type": "application/json",
    "charset": "UTF-8"
  }).json({
    "MONGODB_URI": "127.0.0.1:27017",
    "MONGODB_PUBLIC_URI": "127.0.0.1:27017",
    "MONGOAPI_DBNAME": "mongodb_api"
  }).end();
});
```

The json values is known from here https://github.com/tsuru/mongoapi.
I am not sure if I was doing right and I also don't see many similar issues.
Any helps and ideas would be grateful! Thanks!

**Comment by guilhermebr** [comment]
@diaopk you need an endpoint to bind-unit (even if returns nil), like here:

https://github.com/tsuru/mongoapi/blob/master/main.go#L32
https://github.com/tsuru/mongoapi/blob/master/handler.go#L41

**Comment by diaopk** [comment]
I still got the same error. I actually have 4 endpoints `/resources`, `/resources/mongo_instance/bind`, `/resources/mongo_instance/bind-app` and `/resources/mongo_instance/bind-unit` to handle post requests. The one for `/resources/mongo_instance/bind-app` responds the json object like I show above and the other three don't have data response. I just send back status code 201. Not sure if I am doing the right way.

**Comment by guilhermebr** [comment]
@diaopk can you post your entire service in a gist? also the tsuru api log at the moment of bind?

**Comment by diaopk** [comment]
@guilhermebr Sorry for the late reply. Due to the busy work and study, I am finally back here. The service has been successfully bound to the application. However, the app doesn't seem to be able to connect the mongodb service. I still have no ideas how to connect to the service. Can you give me any guidances for doing so? 

Basically what I have done is  a `node.js` server trying to connect to `mongodb` service and `mogoapi` from https://github.com/tsuru/mongoapi. Both have been deployed. 

For the service, I modified the file https://github.com/tsuru/mongoapi/blob/master/service.yaml to:
```
id: mongodb
endpoint:
  production: node-mongoapi.192.168.99.100.nip.io
```
The endpoint is my service url. Other things remain the original.

For the node.js app, the manifest file I used to bind the service is like this:
```
id: mongodb
username: admin@example.com
password: admin123
team: admin
endpoint:
  production: http://node.192.168.99.100.nip.io
```
The db url I try to connect is the default value, which is `mongodb://127.0.0.1:27017`.
Then when I tried to call the connection method in node.js app to the mongodb service, I got the connection errors from mongodb:
`2018-12-17T16:28:05Z [ web ][ 36408482d786 ]: - testconnect() err: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]`
Am I missing something? Thanks!!

**Comment by guilhermebr** [comment]
@diaopk when service was bound to app, it injects the MongoDB envs inside app, you can check with `tsuru env-get -a myapp`.

So inside your app, you need to get the mongodb address by the env.

You are trying to connect to MongoDB using the localhost address 127.0.0.1, so the app is trying to connect inside the unit. You need to use a public address for mongodb that unit can reach.

unit=running app container

**Comment by diaopk** [comment]
@guilhermebr I ran `tsuru env-get -a myapp` and I can see the there are some mongoapi related env variables. But values are invisible. How can I actually see them?
