### ISSUE TITLE
PHP Sample

### ISSUE THREAD

**Issue by davidkroell** [tsuru/tsuru#2250]
I've been using Tsuru for some time and I noticed, that there is no PHP sample application available.
I created an sample app with PHP and I would like to share my knowledge with the community.

Therefore I’d like to publish my code as a sample repository under the tsuru organization on GitHub.
Please let me know if this is even possible and tell me how.
The documentation [Deploying PHP applications](https://docs.tsuru.io/master/using/php.html) will also be improved.

Best regards

**Comment by ggarnier** [comment]
@davidkroell the example applications are in https://github.com/tsuru/platforms repo. You can find a sample PHP application here: https://github.com/tsuru/platforms/tree/master/examples/php.

Feel free to make pull requests to contribute both to the sample app and documentation.
