### ISSUE TITLE
hung on install

### ISSUE THREAD

**Issue by htbase** [tsuru/tsuru#2261]
Hi folks

When installing tsuru, the install gets hung on this and keeps repeating the same thing

 ---> 2e8706599be4
Successfully built 2e8706599be4
Successfully tagged 172.31.42.166:5000/tsuru/python:v1
Step 1/1 : FROM tsuru/python
latest: Pulling from tsuru/python
Digest: sha256:c13c0e855e02334e45b3e510414268b842c727e52038073a50e471c348dea289
Status: Image is up to date for tsuru/python:latest
 ---> 2e8706599be4
Successfully built 2e8706599be4
Successfully tagged 172.31.42.166:5000/tsuru/python:v1
Step 1/1 : FROM tsuru/python
latest: Pulling from tsuru/python
Digest: sha256:c13c0e855e02334e45b3e510414268b842c727e52038073a50e471c348dea289
Status: Image is up to date for tsuru/python:latest

Here is the content of my config.yml

driver:
    name: amazonec2
    options:
        amazonec2-access-key: XXXXXXXXXXXXX
        amazonec2-secret-key: XXXXXXXx
        amazonec2-vpc-id: vpc-xxxxxx
        amazonec2-region: us-west-2
        amazonec2-zone: a

any ideas why this get stuck in this part and just repeating the same thing over and over?

Thanks

**Comment by guilhermebr** [comment]
@htbase are you using virtualbox 6.0.0? If possible try with version 5.2.0 as reported in this issue: https://github.com/tsuru/tsuru/issues/2243

I will take a look at this issue today.

**Comment by htbase** [comment]
@guilhermebr 

Just to add, I tested on existing VMs running ubuntu and the same happens

**Comment by htbase** [comment]
Hi @guilhermebr 

Any luck with this issue?

**Comment by guilhermebr** [comment]
@htbase what version of tsuru-client are you using?

**Comment by brunoa19** [comment]
Using 1.6 client and trying to spin up both core and app servers in ec2

**Comment by guilhermebr** [comment]
We are close to release tsuru 1.7.0 which will fix this. 
In the meantime, you can get tsuru client code and build from the master.

https://github.com/tsuru/tsuru-client

**Comment by rafaeleyng** [comment]
I've tried with tsuru-client `1.7.0-rc1` (with VirtualBox `6.0.0`) and got:

```
$ tsuru install-create
Running pre-install checks...
Running pre-create checks...
Creating machine...
(tsuru-1) Copying /Users/rafael.eyng/.tsuru/installs/tsuru/cache/boot2docker.iso to /Users/rafael.eyng/.tsuru/installs/tsuru/machines/tsuru-1/boot2docker.iso...
(tsuru-1) Creating VirtualBox VM...
(tsuru-1) Creating SSH key...
Error: failed to provision components machines: failed to provision machines: error creating machine failed to create host: Error creating machine: Error in driver during machine creation: write |1: broken pipe
```

**Comment by rafaeleyng** [comment]
My error above was unrelated. That problem was that the disk image for the machine I was trying to create (`tsuru-1`) already existed.
