### ISSUE TITLE
Pending nodes

### ISSUE THREAD

**Issue by htbase** [tsuru/tsuru#2269]
Hi folks

I'm trying to add nodes on ec2 but all of them only shows pending

I've opened the security group in ec2 to accept all connections on all ports, which would solve the port 2375 issue.

I have this on my iaas (.conf file):

iaas:
  dockermachine:
    ca-path: /certs
    insecure-registry: $REGISTRY_ADDR:$REGISTRY_PORT
    docker-flags: experimental
  ec2:
    key-id: XXXXXXXX
    secret-key: xxxXXXxcxcXXXXXx

any ideas?

**Comment by htbase** [comment]
Any ideas folks?

**Comment by ggarnier** [comment]
Can you share the logs?

**Comment by htbase** [comment]
Hi  @ggarnier 

I checked the OS logs but there is nothing there that points to this issue

This is what I get:

+------------------------------------------------------+---------------------+---------+----------------------------------+
| Address                                              | IaaS ID             | Status  | Metadata                         |
+------------------------------------------------------+---------------------+---------+----------------------------------+
| http://ec2-xxx.amazon.com:2375 | i-0e1a530f409ecbf18 | pending | iaas-id=i-0e1a530f409ecbf18      |
|                                                      |                     |         | iaas=ec2                         |
|                                                      |                     |         | image=ami-0565af6e282977273      |
|                                                      |                     |         | instancetype=m1.small            |
|                                                      |                     |         | keyName=KEY                   |
|                                                      |                     |         | pool=theonepool                  |
|                                                      |                     |         | securityGroup=docker-machine 


It never gets out of pending state and when I log into the machine itself,  there is no tsuru installed in it

**Comment by htbase** [comment]
Any ideas? I tried a fresh install but it still the same
