### ISSUE TITLE
`tsuru install create`  fails in 1.7.0-rc1 (NixOS)

### ISSUE THREAD

**Issue by WhittlesJr** [tsuru/tsuru#2279]
I'm packaging tsuru for NixOS and I found that the 1.7.0-rc1 installer chokes here:

```
Deploying compose file in cluster manager....
```

The error is the same as this one: https://stackoverflow.com/questions/46550348/docker-stack-deploy-error-about-top-level-object-mappings

(I cleared my terminal but I can copy in the exact error for you in a bit)

I tried patching with a few of the suggested answers (using single quotes in `version: "3"`, putting compose.yaml in the same directory rather than in /tmp/), but nothing fixed it.

1.6.0 worked flawlessly, though!

**Comment by cezarsa** [comment]
That's weird. Are you passing the `--config` flag to `tsuru install-create`? If so, could you share it?

**Comment by WhittlesJr** [comment]
Nope, just `tsuru install create` in both versions

**Comment by cezarsa** [comment]
Thanks, I was able to reproduce the problem, a fix is on its way.

**Comment by WhittlesJr** [comment]
Excellent, thank you!
