### ISSUE TITLE
HTTP Routing not working after dockerd restarts

### ISSUE THREAD

**Issue by davidkroell** [tsuru/tsuru#2291]
**Description**
The HTTP Routing process (this could be a [tsuru/planb](https://github.com/tsuru/planb) issue too) fails after der Docker daemon restarts. On app deployment, the Docker daemon allocates a random port on the host machine and sets this in the Redis configuration for the planb reverse proxy. When the daemon restarts, the ports are randomly reallocated in a **different order**. Therefore, the domain does not match the port and the routing breaks after dockerd restarts.

**Steps to reproduce**
Deploy already created application
```bash
tsuru app-deploy --app php-sample .
```

View ports in Redis config
```bash
127.0.0.1:6379> lrange frontend:php-sample.hostname.com 0 100
1) "php-sample"
2) "http://hostname:32769"
```

View ports in Docker
```bash
docker ps
0d35cf2080c9        hostname:5000/tsuru/app-php-sample:v1       "/bin/sh -lc '[ -d /…"   2 months ago        Up 15 hours         0.0.0.0:32769->8888/tcp   php-sample-eec748f8ebd8c
```
As of now, the ports do match and therefore, the HTTP routing works

Restart the Docker daemon (or the machine) and notice, that the Docker port is now different, but the port in Redis is unchanged.
Docker
```bash
docker ps
0d35cf2080c9        hostname:5000/tsuru/app-php-sample:v1       "/bin/sh -lc '[ -d /…"   2 months ago        Up 15 hours         0.0.0.0:32772->8888/tcp   php-sample-eec748f8ebd8c
```

Redis
```bash
127.0.0.1:6379> lrange frontend:php-sample.hostname.com 0 100
1) "php-sample"
2) "http://hostname:32769"
```

**Expected result**
Either the ports in Redis *should change*, or the port allocation from the Docker daemon should *not change*. 

**Environment information**

* Operating System: Ubuntu 16.04
* Tsuru installation method: `tsuru install-create`
* Tsuru API version: 1.7.0
* Tsuru client version: 1.6.0

**Cluster information**

* Node provider: unmanaged
* Machine type: VM
* Machine specs: 4 vCPUs, 16GB RAM
* Provisioner: default
* Docker version: 18.09-ce

**Comment by guilhermebr** [comment]
@davidkroell We will take a look at this, in the meantime, you can run `tsuru app-routes-rebuild -a php-sample` to rebuild the route.

**Comment by aschbacd** [comment]
Have the same problem...

When rebooting the system, the container ports get assigned randomly and the redis database still has the old entries. This command (`tsuru app-routes-rebuild -a php-sample`) doesn't change anything. The port mapping by the redis database is still wrong.

**Comment by cezarsa** [comment]
@aschbacd We rely on the `big-sibling` container running on each node to notify the tsuru API about port changes in restarted containers. If running `app-routes-rebuild` did not fix the redis database it probably means that either big-sibling isn't running or it's having some issue talking to the tsuru API.
Could you please run on the node containing the restarted docker daemon:
```
docker ps -a | grep big-sibling
docker logs big-sibling
```
