### ISSUE TITLE
Proposal: show related kubernetes-services in app-info

### ISSUE THREAD

**Issue by wpjunior** [tsuru/tsuru#2295]
The internal kubernetes addresses are so hidden by a new user, the user needs to read the documentation and discover the addresses.

I think that the user can figure out theses address via app-info command.

For example:
$ tsuru app-info -a myapp

```
Application: myblog
Platform: gunicorn
Repository: git@githost.com:myblog.git
Teams: team1, team2
Units:
+----------+---------+
| Unit     | State   |
+----------+---------+
| myblog/0 | started |
| myblog/1 | started |


Kubernetes internal addresses:
+----------------------------------------+----------+-------+
| domain                                 | protocol | port  |
+----------------------------------------+----------+-------+
| myblog-web.tsuru-my-pool.cluster.local | tcp      | 8888  |
| myblog-web.tsuru-my-pool.cluster.local | udp      | 12201 |
```

**Comment by cezarsa** [comment]
I agree with this proposal, also I think it would be safe and not too complicated to add this new information to the return of the `GET /apps/:app` API request.
