### ISSUE TITLE
Adding AWS as a service broker

### ISSUE THREAD

**Issue by htbase** [tsuru/tsuru#2308]
Hi folks

I am trying to add AWS as a service broker but havent got any luck yet

Here is what I am trying:

tsuru service-broker-add aws https://awsservicebroker.s3.amazonaws.com -c "AWS Access Key ID"=xxxxx -c "AWS Secret Access"=xxxx

Am I using the wrong command. Can someone please help with a couple sample commands to add the main providers as service brokers?

Thanks in advance

**Comment by htbase** [comment]
anyone know this?

**Comment by nettoclaudio** [comment]
Hi @htbase. 

The command looks good, maybe missing the credentials params such as `--token` or `--user` and `--password` (use the `tsuru service-broker-add --help` to list all options). You can also get the full documentation about OSB at Tsuru Docs (https://docs.tsuru.io/stable/services/open-service-broker.html).

**Comment by htbase** [comment]
Thanks @nettoclaudio 

I did look at the document before but it does not show the correct command to pass when adding AWS service broker

In case of AWS, what would be the --token, --user or --password? I thought that the secret-key and access-key would be the key info when connecting with AWS

**Comment by guilhermebr** [comment]
@htbase you need to run the `aws-servicebroker` (you can run as a tsuru app). 
then you pass the `aws-servicebroker` as the endpoint in `tsuru service-broker-add ...`

Here more details: https://github.com/awslabs/aws-servicebroker/tree/master/docs

**Comment by htbase** [comment]
Thanks @guilhermebr 

Is there any documentation on the Tsuru side with more info on running it as an app in Tsuru?

**Comment by guilhermebr** [comment]
@htbase I can`t test now, but it's something like that, I will try later to confirm and update the docs:

`tsuru app-create aws-osb`

```
tsuru env-set -a aws-osb \
        SECURITY_USER_PASSWORD=... \
        INSECURE=false \ 
        AWS_ACCESS_KEY_ID=.... \
        AWS_SECRET_ACCESS_KEY=... \
        BROKER_ID=awssb \
        PARAM_OVERRIDE_awssb_all_all_all_VpcId=... \
        PARAM_OVERRIDE_awssb_all_all_all_target_account_id=... \
        PARAM_OVERRIDE_awssb_all_all_all_target_role_name=... \
```
`tsuru app-deploy -a aws-osb -i awsservicebroker/aws-servicebroker:stable`

**Comment by brunoa19** [comment]
Thanks @guilhermebr, I tried it but get an empty service list. Im sure Im doing it wrong:

$ tsuru service-broker-list
+------+----------------------------------------+----------+------+---------+
| Name | URL                                    | Insecure | Auth | Context |
+------+----------------------------------------+----------+------+---------+
| aws  | aws-servicebroker.xxxxxx.nip.io | false    | None |         |
+------+----------------------------------------+----------+------+---------+

$ tsuru service list
$ 

Here are the env I have set prior to deploying the app:

$ tsuru env-set -a aws-servicebroker SECURITY_USER_PASSWORD=xxxxx
---- Setting 1 new environment variables ----
$ tsuru env-set -a aws-servicebroker INSECURE=true
---- Setting 1 new environment variables ----
$ tsuru env-set -a aws-servicebroker AWS_ACCESS_KEY_ID=xxxxxx
---- Setting 1 new environment variables ----
$ tsuru env-set -a aws-servicebroker AWS_SECRET_ACCESS_KEY=xxxxxxx
---- Setting 1 new environment variables ----
$ tsuru env-set -a aws-servicebroker BROKER_ID=awsservicebroker
---- Setting 1 new environment variables ----

**Comment by guilhermebr** [comment]
@htbase How did you added the service-broker? you need to pass the aws-osb authentication param, like:

`tsuru service broker add aws-osb aws-osb.xxxxxxx.nip.io -i -u admin -p SECURITY_USER_ADMIN`

**Comment by brunoa19** [comment]
$ tsuru service-broker-add aws aws-servicebroker.xxxxxxx.nip.io -i -u admin -p xxxxx

$ tsuru service-list
$

**Comment by guilhermebr** [comment]
When you run `tsuru service-list`, check the API logs to see if an error is returned.
You can also debug the `aws-servicebroker` app with `tsuru app-log -a aws-servicebroker`.

Have you made the prerequisites described at https://github.com/awslabs/aws-servicebroker/blob/master/docs/install_prereqs.md?

**Comment by brunoa19** [comment]
Thanks  @guilhermebr 

This is what I see on the API log

ERROR: [Broker=aws] error creating broker client: Only one AuthConfig implementation must be set at a time.

Regarding the install prerequisites, yes, all were done prior to adding the broker

**Comment by brunoa19** [comment]
Should I change anything on the way it is added in this case? @guilhermebr
