### ISSUE TITLE
auth/oauth: validate JWT params

### ISSUE THREAD

**Issue by morpheu** [tsuru/tsuru#2355]
Today, Tsuru always try to validate user token even if it is still valid. Probably we should verify JWT params and check it to avoid unnecessary auth API calls.

**Comment by cezarsa** [comment]
Another alternative to creating and managing JWT tokens is going full OIDC. Instead of relying on `auth/oauth` provider we could create a new `auth/oidc` auth provider which would require a OIDC server to generate the JWT token and manage verification of this token.
