### ISSUE TITLE
Software Defined Networking

### ISSUE THREAD

**Issue by kasra73** [tsuru/tsuru#2381]
**What is the problem?**
It's some time I use tsuru both in production and personal but private environments and I always consider the security a PaaS should provide if we want to provide services to public. As we know, SSL for domains provided on router level and behind the router , traffic transferred  to containers without any encryption; But the problem is all the containers in tsuru (especially docker provision) are connected to same bridge network and listening on default server ip address (public ip address actually).
![image](https://user-images.githubusercontent.com/7995238/71540813-b0ecd180-2964-11ea-855d-7c7944c2fdb3.png)

**A possible solution:**
What we can do about this problem is provide provision-based config to connect created containers to an specific network. This network can use a more advanced driver (e.g. calico, flannel, weave, etc) so we can define policies for containers networking as a result containers cannot communicate each other except through the router and they can still connect to service containers in and outside the docker node.

**How to implement?**
I think it's possible to add network name and driver options to tsuru config yaml (in provision scope) and add these details as NetworkingConfig to CreateContainerOptions when it's bees initiating.

**Additional Notes:**
I'm not very familiar with k8s architecture and development but a similar approach may be possible
even though I don't have an idea about it.

**Comment by ernani** [comment]
I do believe this can be done when combining the usage of tsuru and k8s, some sort of integration between tsuru namespaces and pods and policies to block/unblock them to talk to other members of an existing cluster.

**Comment by wpjunior** [comment]
The focus of Tsuru is to control k8s clusters, this feature is out of our roadmap, thanks.
