### ISSUE TITLE
Cant install Tsuru-Client on Ubuntu 20

### ISSUE THREAD

**Issue by Berndinox** [tsuru/tsuru#2458]
I created a new droplet at Digitalocean with Ubuntu 20 on it.

i follwed the guide: 
https://tsuru-client.readthedocs.io/en/latest/installing.html

Adding the Repositorie failed with:
```
E: The repository 'http://ppa.launchpad.net/tsuru/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Ok, so i tried it manuelly:
```
wget https://github.com/tsuru/tsuru-client/releases/download/1.8.3/tsuru-1.8.2-linux_amd64.tar.gz
tar vxf tsuru-1.8.2-linux_amd64.tar.gz && cd dist
./tsuru
./tsuru: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./tsuru)
```

GLIBC is 2.31! I found no solution on how to update on 2.32 "easily" with ubuntu 20.

**Comment by flaviamissi** [comment]
Reproduced running ubuntu on docker:
```bash
$ docker run -ti ubuntu:latest /bin/bash
$ apt-get install -y software-properties-common
$ apt-get update
$ apt-get install -y software-properties-common
$ apt-add-repository ppa:tsuru/ppa
```

Seems like the ppa isn't very up-to-date: https://launchpad.net/~tsuru/+archive/ubuntu/ppa.
Does it work for you to [use the binaries](https://tsuru-client.readthedocs.io/en/latest/installing.html#downloading-binaries-mac-os-x-and-linux)?

**Comment by cande1gut** [comment]
You can use the package cloud instead: 
```
curl -s https://packagecloud.io/install/repositories/tsuru/stable/script.deb.sh | sudo bash
sudo apt-get install tsuru-client
```
