### ISSUE TITLE
docker: 'deploy' is not a docker command

### ISSUE THREAD

**Issue by alberteddu** [tsuru/tsuru#2472]
**Description**

When running `tsuru install-create -c config.yml` on my local Mac with this config.yml (`<machine>` is the IP address of a Debian 10 machine):

```hosts:
  core:
    size: 1
    driver:
      options:
        generic-ip-address: ["<machine>"]
  apps:
    size: 1
    dedicated: false
    driver:
      options:
        generic-ip-address: ["<machine>"]
driver:
  name: generic
  options:
    generic-ssh-port: 22
    generic-ssh-user: root
```

I get:

```
Error: ssh command error:
command : sudo docker deploy -c /etc/tsuru/compose.yml tsuru
err     : exit status 1
output  : docker: 'deploy' is not a docker command.
```

**Steps to reproduce**
1. Get a machine with Debian 10 (I'm using Hetzner)
2. Install tsuru-client on a Mac
3. Use the command above with the config above

**Expected result**
Tsuru installed on the target machine.

**Attachments**
The complete log of the command:

```$ tsuru install-create -c config.yml
Running pre-install checks...
Running pre-create checks...
Creating machine...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with debian...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
Waiting for SSH to be available...
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Uploading registry certificate...
Deploying tsuru config...
Deploying compose file in cluster manager...
Error: ssh command error:
command : sudo docker deploy -c /etc/tsuru/compose.yml tsuru
err     : exit status 1
output  : docker: 'deploy' is not a docker command.
See 'docker --help'
```

**Environment information**

* Operating System: Debian 10
* Tsuru installation method `tsuru install-create`

**Cluster information**

* Node provider (umanaged/Cloud Stack/DigitalOcean/EC2): Hetzner
* Machine has 2GB RAM
* Provisioner (`default`/`kubernetes`/`swarm`): I think "default"
* Docker version (if applicable, use the `docker version` output): Docker version 20.10.5, build 55c4c88

**Comment by marcelosf** [comment]
I got the same error. I think the command would be `sudo docker stack deploy -c /etc/tsuru/compose.yml tsuru ` on compose.go

**Comment by ktfth** [comment]
Someone have started on that task?

**Comment by marcelosf** [comment]
I sent a pull request to tusuru-client [tsuru-client](https://github.com/tsuru/tsuru-client/pull/158)
