### ISSUE TITLE
Vim and Nano runs terrible on Tsuru Shell

### ISSUE THREAD

**Issue by joaoggnogueira** [tsuru/tsuru#2556]
**Description**
The Vim, or Nano editor will not be able to navigate over the text files. The cursor is stuck at the beginning of the file. This problem only happens when I runs this editors on app-shell

**Steps to reproduce**
> 1.  `tsuru app-shell -a application_name`
> 2.  `sudo apt-get install vim`
> 3.  `vim app.rb`
> 4.  Press any directional key
> 5.  The cursor get stuck

**Expected result**
> The cursor moving properly with the directional keys.

**Environment information**

* Client with Windows 10 (v 1.10.4.) using Prompt Command, PowerShell, WSL Ubuntu or Git Bash
* Server with Ubuntu 18.04 (v 1.11.2)

**Comment by arthurcgc** [comment]
Could not reproduce the issue. 
This does not seem to be a tsuru problem. 
Root cause may be a slow websocket connection.
