### ISSUE TITLE
Versionar variáveis de ambiente da aplicação 

### ISSUE THREAD

**Issue by juliolustosa** [tsuru/tsuru#2566]
Uma sugestão seria o próprio tsuru conseguir versionar as variáveis de ambiente de uma app junto com cada versão de deploy. Para ajudar nos casos de roollback.

Hoje estou usando o GCP Secret Manager para fazer isso fora do tsuru.

**Comment by arthurcgc** [comment]
Please open your issues in english.

**Comment by juliolustosa** [comment]
Atualmente o tusuru aceita link imagem docker, minha sugestão é que também aceite somente o Dockerfile para que o proprio tsuru faça build do meu Dockerfile e gere a imagem. Assim vamos conseguir reduzir o tamanho dos pipelines.
