### ISSUE TITLE
Document `make local` and `make local-mac`

### ISSUE THREAD

**Issue by arthurcgc** [tsuru/tsuru#2575]
**Is your feature request related to a problem? Please describe.**
> One of the new easy installations methods for tsuru is using the makefile recipe `make local` or, if you're on macOS `make local-mac`. These installation methods are not documented yet and would be of great value if they would.

**Describe the solution you'd like**
> Document the steps needed to setup tsuru starting from `make local` and `make local-mac` all the way to linking the newly installed cluster to tsuru

**Describe alternatives you've considered**
> N/A

**Additional context**
> To document the steps needed to link tsuru with the newly installed cluster, one could use [this doc](https://docs.tsuru.io/stable/contributing/compose.html#kubernetes-integration) as reference... Although a little outdated it's good starting point

**Comment by arthurcgc** [comment]
Partially solves: https://github.com/tsuru/tsuru/issues/2524

**Comment by vikramadityasinghs** [comment]
hi @arthurcgc, can i work on this particular issue?

**Comment by arthurcgc** [comment]
> hi @arthurcgc, can i work on this particular issue?

As my colleague @tcarreira said, please do :)
PS: If you stumble on any problems while running `make local` and  `make local-mac` and is forced to make any changes in the makefile, feel free to open another PR.
