### ISSUE TITLE
Could not run make local-mac on Apple M1

### ISSUE THREAD

**Issue by RaphaelVRossi** [tsuru/tsuru#2582]
**Description**
Run `make local-mac` on Apple M1 is not working

**Steps to reproduce**
Run the command `make local-mac` on `darwin/arm64`

```sh
minikube start --driver=virtualbox
😄  minikube v1.27.1 on Darwin 12.2 (arm64)
✨  Using the virtualbox driver based on user configuration

❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'virtualbox' is not supported on darwin/arm64

make: *** [local-mac] Error 56
```

**Expected result**
> Same as running `make local-mac` on MAC OS X

**Attachments**
> If applicable, provide logs, screenshots, screencast, etc to help explain your problem.

**Environment information**

* Operating System - Darwin WP086394 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
* Tsuru installation method - Docker Compose
* ./build/tsurud version
Client version: 1.12.2. hash 1ab0249a35bee9695f760d20602931fb52be43ad
Server version: 1.12.2.

**Cluster information**
N/A

**Comment by arthurcgc** [comment]
fixed with https://github.com/tsuru/tsuru/pull/2584
