### ISSUE TITLE
docker CAAS

### ISSUE THREAD

**Issue by gedw99** [tsuru/tsuru#2678]
**Is your feature request related to a problem? Please describe.**

Can I use tsar for CAAS ? Instead of for Kubernettes.

The docs seem to favour K8, but I want to control servers that are docker nodes and containers on bare metal providers like Hetzner etc.

thanks you...

**Comment by arthurcgc** [comment]
Hi @gedw99 , thanks for reaching out, as of right now we only support K8s as the underlying provider of units and services
