### ISSUE TITLE
Incompatible changes with Go 1.21

### ISSUE THREAD

**Issue by mauri870** [tsuru/tsuru#2697]
**Description**

After the latest changes and the migration to Go 1.21 some CI stages are failing. 

## govulcheck

https://github.com/tsuru/tsuru/actions/runs/9384516732/job/25840486005

We need at least Go 1.21.11 to make govulncheck happy.

## golangcilint

https://github.com/tsuru/tsuru/actions/runs/9384516732/job/25840487324

Given the stack trace containing `go/types` functions I'd guess we are on a version of the linter compiled with an older toolchain. We should migrate to version 1.59.0.

## test

https://github.com/tsuru/tsuru/actions/runs/9384516732/job/25840487661

There is also some changes in context in Go 1.21.

See https://tip.golang.org/doc/go1.21#contextpkgcontext

```
An optimization means that the results of calling [Background](https://tip.golang.org/pkg/context/#Background) and [TODO](https://tip.golang.org/pkg/context/#TODO) and converting them to a shared type can be considered equal. In previous releases they were always different. Comparing [Context](https://tip.golang.org/pkg/context/#Context) values for equality has never been well-defined, so this is not considered to be an incompatible change.
```

**Steps to reproduce**

See https://github.com/tsuru/tsuru/actions/runs/9384516732

**Expected result**

CI passes

cc @wpjunior

**Comment by mauri870** [comment]
I can't look into this today. All this was caused by the introduction of govulncheck, but I think it highlights that the project was relying on old tools. Given the release policy of the Go team the version 1.20 is not entitled to release security updates since the release of 1.22 in february, so this is more of a wake up call.

I can look into it later today, if it is still unresolved.

**Comment by wpjunior** [comment]
I think that golang 1.21.11 is recently released, then when we refer golang 1.21 on ci.yaml is still using the 1.21.10, let's wait util tomorrow to test again.

**Comment by mauri870** [comment]
Makes sense, it was released yesterday, will take some time until it becomes available in actions/setup-go.

**Comment by wpjunior** [comment]
hello @mauri870, right now, just govulncheck is broken

**Comment by mauri870** [comment]
Thanks, great news! For good measure we can also bump setup-go to v5. Other than that we should wait until 1.21.11 is available. Feel free to close this issue or keep it open as a reminder.
