### ISSUE TITLE
Review the flow for the swap command

### ISSUE THREAD

**Issue by magnotorres** [tsuru/tsuru#544]
We need to review the flow when for example we use the command "swap app1 app2", remove the app1(that was pointing to app2.cloud.tsuru.io) and create it again with the same name(app1 - tsuru will try to create a route to app1.gloud.tsuru.io, but it will be used by app2). For now, we may just need to block the app1 name for new apps as it is in use by the router (for another app - app2 in this case).

**Comment by wpjunior** [comment]
we have been review that in Router API 2.0. thanks
