### ISSUE TITLE
Split log files

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#572]
Each daemon should log in a dedicated log file to make an easier troubleshooting or at least each log line should start with daemon name.

Actually is impossible to know which daemon wrote the log line as everything is saved on syslog.

**Comment by fsouza** [comment]
This issues is from a time we had two daemons in a single binary: the api and the collector. Now we have just one daemon, with a single file configuration.

Also, we can see the name of the executable in syslog, so grepping for tsurud is fine (it used to be not fine to grep for tsr).
