### ISSUE TITLE
Restart or create on failures

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#585]
Let's assume a running app. In case of power failures or crashes or whatever , tsuru should detect the failed app and restart (or totally redeploy) it again.

Sometime tsuru restart command doesn't work properly and I have to delete the app and then redeploy it from scratch with git (app-remove + app-create + git push)

This should be done automatically by the health manager.

**Comment by andrewsmedina** [comment]
The healthcheck (http://docs.tsuru.io/en/master/using/tsuru.yaml.html?highlight=healthcheck#healthcheck) fix this problem.

If healthcheck is configured in tsuru.yml, tsuru will only finish the deploy if the healthcheck is ok, if not tsuru will rollback the deploy.
