### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#609]
Some CI (continuous integration) support should be added.
For example, a build should be started only if any CI server say OK.
This can be done by adding some hooks in pre-recieve and block pushing in case of failures.

Maybe a ci.yaml file in the root of project is good enough for configuring the CI system
(Something like Travis and github)

This because I see tsuru as much more web-oriented than other paas.

**Comment by andrewsmedina** [comment]
duplicated of  #750
