### ISSUE TITLE
Default timeout for service endpoint is too long?

### ISSUE THREAD

**Issue by sidnei** [tsuru/tsuru#618]
After fixing the problem with the broken resolver at #617 I've noticed that this package's test takes a really long time to complete:

```
ok      github.com/globocom/tsuru/service       134.315s
```

It seems like whatever Dial is used by DefaultClient.Transport could use a shorter timeout. Or maybe the test should use a custom Transport with a shorter Dial timeout.

**Comment by andrestc** [comment]
Hi @sidnei, this issue problably went lost and was fixed along the way. Currently we are using a client with a [5s timeout](https://github.com/tsuru/tsuru/blob/master/service/endpoint.go#L81). And, as can be seen on travis, we arent facing this issue on service tests anymore:

```
ok  	github.com/tsuru/tsuru/service	1.533s
```

Thanks for reporting and I'm sorry that it took all this time to answer.
