### ISSUE TITLE
Ability to pick which action from Procfile to run on each container.

### ISSUE THREAD

**Issue by nightshade427** [tsuru/tsuru#647]
Currently tsuru will run all actions specified in the Procfile. I need to be able to pick which ones run in what containers.

Use Case:
I have an app that has a "web" action and a "worker" action in the Procfile. I want to have 3 web container and 2 worker containers.

Suggestions:
"tsuru scale web=3 worker=2" or similar

**Comment by fsouza** [comment]
Coming together with #1136.

**Comment by fsouza** [comment]
So, working on it now, here's what we're going to do:

1. Introduce the concept of a process
1. Each app can have multiple processes, and each process can have multiple units
1. In the first deployment, tsuru will create one process per Procfile entry, and one unit per process
1. For now, tsuru will provide only one public port for the application, binding it to the process named ``web``, just like in Heroku. We can evolve it in the future so users can have multiple web processes
1. Users will be able to define per-process environment variables (``env-set -p`` to specify the process, where p is optional and there are two scopes: application-level and process-level environment variables, with higher precedence for process-level scope)
1. Users will scale units in a per-process basis (``unit-add -p`` and ``unit-remove -p``, where p is not optional)
1. Users will be able to start, stop and restart processes individually or the entire application (``app-restart``, ``app-start`` and ``app-stop`` with an optional ``-p`` flag)

That's what I thought so far, questions or comments?

**Comment by jblancett** [comment]
@fsouza sounds like that would remove the possibility of having all processes under 1 roof (current method)?

**Comment by fsouza** [comment]
@jblancett yes, it would. Is this a problem for you? What's your scenario? Are the processes of your applications sharing some files/directories in the filesystem?

**Comment by jblancett** [comment]
imo scaling them out independently should be optional - but I'm open to whatever

**Comment by fsouza** [comment]
I'm closing this issue, and moving the effort to #1136.

At this point, we're already creating and scaling units based on Procfile entries (processes), we're still working to get status reporting and logging to work.
