### ISSUE TITLE
provison/docker: custom registry: how to use it?

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#663]
I'm testing a custom registry for docker provisoner (the one that comes from your ubuntu repo) but it doesn't work as expected.

I've set "docker:registry" in tsuru.conf and I'm able to see that tsuru is trying to fetch an image from that registry.

I've also uploaded an image to the custom registry.
The issue is that tsuru is trying to access to the wrong url:

```
DEBUG: create container for app test, based on image http://docker-registry.mycloud.com:8080/tsuru/php, with cmds [/var/lib/tsuru/deploy git://git.mycloud.com/test.git origin/master TSURU_APPNAME='test' TSURU_HOST='http://10.0.0.1:8080' TSURU_APP_TOKEN='dcc6c389ed954b10d22b8988c86f1f50507d3185' ]
```

but:

```
$ curl http://docker-registry.mycloud.com:8080/tsuru/php
404 page not found
```

After pushing, registry told this url:

```
Pushing tags for rev [970c35dd071e] on {http://docker-registry.mycloud.com:8080/v1/repositories/tsuru/php/tags/latest}
```

**Comment by wpjunior** [comment]
Recently we added support to dedicated registry per tsuru cluster, I believe that it is interesting to be well documented. Adding `hacktobeerfest` label to encourage people to contribute with that.
