### ISSUE TITLE
Shared folders

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#681]
Some apps needs a writable storage to be shared across multiple units.
For example, folder "wp-content" in a wordpress installation should be shared across all unites to have the same uploaded content available on each container.

Is tsuru supporting this? Any way to configure a shared directory like on pagodabox 
http://help.pagodabox.com/customer/portal/articles/175475#shared-writable-dirs ?

Any future plans for this? Without a similiar function, mostly every application will not workproperly when scaled on multiple units if not "tsuru-aware"

**Comment by cweagans** [comment]
The way that Flynn handles this is by having a Ceph service, and you connect your app to that service. I don't accept that using s3 is a good solution. If I'm going through all the trouble of hosting my own PaaS, why would I offload file storage to somebody else?

**Comment by fsouza** [comment]
@cweagans what's suggested above is using an object storage _like_ S3. So Swift and Ceph Object Storage both qualify. 

Does Flynn support connecting apps to Ceph Block Storage or does it use Ceph just _like_ S3?

**Comment by cweagans** [comment]
I think it uses Ceph Block Storage, but personally, I'd rather use something like NFS.

**Comment by fsouza** [comment]
Ceph Block Storage is like NFS (from the Block Storage user point of view). Ceph Object Storage is like S3.

As far as I can tell, mounting a Ceph block storage inside a container would require fuse, which is not possible in a Docker container, but we will run some experiments. Thanks!

**Comment by ggarnier** [comment]
This should be solved with #1599

**Comment by andrestc** [comment]
Closing this as #1599 adds support for volumes on swarm and kubernetes.
