### ISSUE TITLE
Custom mount points inside container

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#700]
Actually, by design, docker doesn't allow to use mount command from a container.

I would like to automatically mount a shared S3 filesystem (with s3ql) on every deploy. To do this I have to mount the S3 filesystem in docker node and then bind it to a directory inside the container.

How can I automate this? Do you have any hooks that are executed on each deploy, on each docker node?

Reference: https://github.com/globocom/tsuru/issues/681

Using an external object storage is not always possible for many reasons.
Not all apps are "cloud-aware". In example, wordpress wp-content can be replaced by an external FS with some plugins but not all applications will do this (prestashop, for example, doesn't allow this)

**Comment by wpjunior** [comment]
The tsuru now supports volumes is the official way to create mount points.
