### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#733]
Any plans to add a metrics collector for each container?
https://github.com/etsy/statsd could be used as an aggregator.

**Comment by andrewsmedina** [comment]
Currently we use [bs]() to get the metrics (cpu, memory, io) from all containers. For more info you can see the [tsuru docs](https://docs.tsuru.io/stable/advanced_topics/metrics.html?highlight=metrics) and [bs docs](https://github.com/tsuru/bs#metrics) about it.
