### ISSUE TITLE
Log collector

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#736]
Any plans on this?
Actually, faster way would be using rsyslog from container logging to a remote rsyslog server. Less than 1 hours of works.

This solution lacks of a good gui (something like loggly.com). Do you have plans for log aggregation in tsuru ?

**Comment by andrewsmedina** [comment]
this issue is not valid anymore. currently is possible to use external log managers like logstash or fluentd using the `bs` `syslog` backend: https://github.com/tsuru/bs#log_backends
