### ISSUE TITLE
Support for geographical regions

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#740]
Why not add support for geographical regions so that users can choose their region when deploying apps.

In example:
`tsuru app-create myapp --region UK`

will deploy app choosing from docker servers with hostname like `UK.*` (example: `uk.docker01.mycloud.tld`)

Obviously these servers will be located in UK.

It shouldn't be to hard to add. Region must be saved in Mongo and then fetched on each deploy or unit-add.

what do you think ?

**Comment by wpjunior** [comment]
Nowadays it is available with multiple tsuru pools distributed across the globe. Thanks =)
