### ISSUE TITLE
Gracefully handle SIGEXIT signal in tsr

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#776]
SIGEXIT should wait for ongoing requests to end before shutting down the server. Some references of projects that help with this:
https://github.com/braintree/manners
https://github.com/cupcake/mannersagain

**Comment by cezarsa** [comment]
Related commit: 558f65091dc1803cb843928a71e1d0e0665ce050

**Comment by cezarsa** [comment]
Finished but forgot to reference issue in commits. :/

**Comment by fsouza** [comment]
<img src="http://replygif.net/i/307.gif">
