### ISSUE TITLE
app: tsuru command to force rebuild app image

### ISSUE THREAD

**Issue by morpheu** [tsuru/tsuru#813]
App actually is rebuild on each 10th deploy or when platform is updated. Admin or even user could force an app image update on next deploy via tsuru-client.

**Comment by gabrielpjordao** [comment]
:+1: on this. Would definitely be useful.

**Comment by tupy** [comment]
+1

**Comment by andrestc** [comment]
I think this could be supported as a param to app-deploy, `tsuru app-deploy -a app --rebuild .`; would not cover the git deploy workflow, tho.
