### ISSUE TITLE
Reset lock?

### ISSUE THREAD

**Issue by jonaskac** [tsuru/tsuru#858]
I keep getting the following error:
Error: App locked by tsr, running POST /apps/*****/repository/clone. Acquired in 2014-07-21T08:15:54+03:00

What's the best way to reset the lock?

**Comment by tatiana** [comment]
BTW: the command is: `tsuru-admin app-unlock --app <app-name>`

**Comment by jnana-rb** [comment]
```
root@vagrant-ubuntu-trusty-64:/home/vagrant# tsuru-admin app-unlock --app svcpack
tsuru-admin: command not found
root@vagrant-ubuntu-trusty-64:/home/vagrant# tsurud version
tsurud version 1.5.0-rc15. hash c72388547d65bbdeac2fb6c914f7d5270e1d5eb6
root@vagrant-ubuntu-trusty-64:/home/vagrant# tsuru version
tsuru version 1.4.0.
```

**Comment by magnotorres** [comment]
@jnana-rb the command "tsuru" absorbed all the tsuru-admin commands, so, just type tsuru app-unlock -a svcpack. Tsuru will figure out if you have the admin privileges to perform the desired action
