### ISSUE TITLE
Git push hangs on completion

### ISSUE THREAD

**Issue by bobobo1618** [tsuru/tsuru#882]
After pushing a repo with a rather long setup process, the post-receive hook fails to terminate.

The build process for my particular app goes:
- apt-get install
- gem install some stuff
- npm install some stuff
- pip install some stuff

Git ceases receiving output about half way through the pip install.

SSH to the relevant Docker host shows that the image build succeeds and the process terminates.

Linux reports two connections to the Docker host's API port, both from the Tsuru API server. One is ESTABLISHED, the other is CLOSE_WAIT.

This is the reason for my other ticket about app-remove terminating an app. After this process, the app is locked and nothing can be done to remove it, save removing the lock manually from MongoDB.

**Comment by fsouza** [comment]
I will close this issue, lot has changed since in one year. @bobobo1618 please let us know if you face this or any other issue again in the future.
