### ISSUE TITLE
app: add an environment variable with the application version

### ISSUE THREAD

**Issue by fsouza** [tsuru/tsuru#885]
The version is provided to the application clone endpoint, and is _usually_ the hash of the Git commit.

This can be useful for developers that wanna have a /version endpoint to display the current running code. The variable could be something like ``TSURU_APP_VERSION``.

**Comment by fsouza** [comment]
We no longer require the concept of "version", so I don't think that this issue makes sense anymore.

**Comment by ggarnier** [comment]
@fsouza when you use the [blue-green plugin](https://github.com/emerleite/tsuru-bluegreen/), you already have a `TAG` environment variable available.
