### ISSUE TITLE
Possibility to have multiple hipache load-balancers

### ISSUE THREAD

**Issue by jonaskac** [tsuru/tsuru#907]
We are putting quite a lot of systems om Tsuru today. Which is great!
But what we are experiencing is that we are really dependent on the hipache-service working.

This problem is two-fold:
1. If we update the system, and something goes wrong all our services goes down, with two hipache we can redirect the DNS to the one that is working, and all is well.
2. If the load grows between the different systems, we have no way distributing this further. 

By making it possible for Tsuru to handle several hipache instances this would be solved. The cool thing would also be that we can start a setup in another part of the world, and point the DNS to that locales hipache instance.

This would help us a lot!

**Comment by gfronza** [comment]
I'm sorry for raising this old topic, but it seemed the right place to ask my question.

@magnotorres you said that you have as many hipache instances as you need, but for tsuru would be like it was only one at a time? I mean for HA. Say I want to avoid a single point of failure (hipache router) would I have multiple servers (running hipache) with a floating VIP and then use this VIP to link docker router in the tsuru.conf? Is there a better way of getting HA in tsuru/hipache?

**Comment by magnotorres** [comment]
Hi @gfronza! Here at Globo.com we are using planb(https://github.com/tsuru/planb - a go router with the same hipache api, better performance and steroids ;-) ). To have HA, we create a VIP and point it to the VMs with planb router (as many) we needed, each one with a redis slave(to improve the read performance and latency). The redis master only receive writes from tsuru api(and sync to the redis slaves). Is also possible to configure a healthcheck, making a HTTP request to the Host: __ping__ and if everything is ok with the planb, it will respond "OK".

It's also possible to have multiple VIPs with isolated planb routers and also other routers like vulcand or galeb. 

We have a lot of applications (> 500) and routers here(routers planb/galeb per environment: dev/homolog/prod/etc), and we deal with a lot of requests/s, with great performance and speed.

Feel free to ask anything you want, and good luck!
