### ISSUE TITLE
new quota management based on memory

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#935]
Quotas should be configured by team, and not by individual users.
Users ability to create new teams should be limited by a tsuru configuration option expressing the maximum number of teams a user is able to create (a value of 0 would mean only an admin is able to create new teams).
Also quotas shouldn't be based on the number of apps or units a team can create, it should be expressed by how much memory is available to each team. This gives flexibility to users to create apps with plans (see #933) consuming more from their quota if this is needed.

**Comment by wpjunior** [comment]
Nowadays it is achievable with Kubernetes Resource Quotas by Tsuru Pool: https://kubernetes.io/docs/concepts/policy/resource-quotas/
