### ISSUE TITLE
Ability to run existing docker images as a tsuru service

### ISSUE THREAD

**Issue by cezarsa** [tsuru/tsuru#942]
We should explore the possibility of running existing docker images as tsuru services.

The idea is having a service descriptor, similar to our existing service.yaml file that will allow you to declare a docker image, possibly already available in the https://registry.hub.docker.com/, and a set of configuration options that would describe how tsuru should start and scale this image. tsuru would then be able to manage containers based on this image and export allow applications to bind to this service.

The biggest challenge I can see right now is which possible configuration options are necessary to describe how the image should be handled.
We would need to describe:
- container start flags
  - plans: All the following options could be segregated by plan.
  - bind port: Which port will be exported by the container. tsuru should manage which port is exported in the host system to prevent docker dynamically re-allocating theses ports on container restart.
  - volumes: For images requiring mounted volumes (like databases), declare which paths should be available inside the container. tsuru should manage these paths in the host filesystem segregated by service. e.g.: declaring `volume: /var/lib/mysql` would be equivalent to `docker run -v /tsuru_services/<instance_name>/var/lib/mysql:/var/lib/mysql`
  - envs: Declare which envs will be passed on container creation. We should support some dynamically generated values for use cases like password generation. (something like PASSWORD=$random_16 for a 16 digits random string.) We should also be able to expand existing environment variables that will be made available during service creation (USER=user_$SERVICE_INSTANCE_NAME).
  - memory/cpu limits: These should be sent on container creation.
  - volume size limit: Images with volume mounting should have a limited space, tsuru should monitor this in some way and cause errors if the container tries to exceed it.
  - scalable: Whether or not tsuru should allow scalling this container, this means starting new containers for an existing service instance. This is useful for images that allow clustering (mongo replicaset, redis sentinel/cluster).
  - web hooks: The idea is specifying urls that will be called after or before the creation of a new container for a service instance. This should not be mandatory, it could be useful for setting up clustered services though. If a webhook is specified it should be responsible for returning the set of variables that will be made available when the container is created. Having web hooks defeat the idea of having services available without any code, however it adds greater flexibility and simplifies a lot creating services.
- exported environment variables on bind:
  - For services described without a web hook, there should be a way to declare which variables will be available to applications after binding. We should be able to use variables previously defined as a container start  environment variable (e.g MYSQL_PASSWORD=$CONTAINER_START_PASSWORD). We should also be able to use the machine hostname and allocated port (e.g MONGO_URI=mongodb://$HOST_IP:$CONTAINER_ALLOCATED_PORT)

**Comment by sroze** [comment]
:+1: it would be nice !

**Comment by robsonpeixoto** [comment]
:heart: this idea

**Comment by fsouza** [comment]
We've somehow started it at diaats: https://github.com/tsuru/diaats

Still needs lots of improvements, though.

**Comment by wpjunior** [comment]
Nowadays make more sense using kubernetes-operators for each service that we want, they care about of creation, update, backup and other operational aspects.
