### ISSUE TITLE
Improved healthcheck for Tsuru API

### ISSUE THREAD

**Issue by magnotorres** [tsuru/tsuru#967]
Would be great to have a better healthcheck for tsuru api to analyze all components necessary for the correct work of tsuru like gandalf, git daemon, registry, mongo, redis, swift, IaaS, etc.  
It would be useful for people starting with tsuru to find which service is missing from what is needed to the api (e.g. try tsuruapi.yourcompany.com/healthcheck?check=all before open a issue)

**Comment by msabramo** [comment]
@joaopaulovieira: You might want to look at https://github.com/tsuru/gandalf/pull/178. In that PR, I enhanced `/healthcheck` for gandalf so that it outputs a detailed JSON response:

```
$ http http://127.0.0.1:8000/healthcheck/
HTTP/1.1 200 OK
Cache-Control: private, max-age=0
Content-Length: 189
Content-Type: application/json
Date: Sat, 03 Jan 2015 16:56:49 GMT
Server: gandalf-webserver/0.5.2
X-Gandalf-Version: 0.5.2

{
    "database": {
        "name": "gandalf",
        "url": "127.0.0.1:27017"
    },
    "git": {
        "bare_location": "/var/lib/gandalf/repositories",
        "bare_template": "/home/git/bare-template"
    },
    "pid": 17442,
    "status": "OK",
    "uid": 502
}
```

**Comment by msabramo** [comment]
As @andrewsmedina said in https://github.com/tsuru/gandalf/pull/178, perhaps there should be a new /healthcheck.json endpoint?

**Comment by joaopaulovieira** [comment]
Should be yes, @msabramo.
The healthcheck routes that are being created for services are only returning "working" and will conflict with the .json return you implemented.
And as @andrewsmedina mentioned, some information would not need to be exposed in json.
one solution is leaving the optional json return in Tsuru API and have a struct error to return both the response of "working" as json.

**Comment by fsouza** [comment]
We have now an "advanced" healthcheck that will be invoked when we access ``/healhtcheck?check=all``.

Currently, it will check:

- routers
- docker (node and registry)
- database
- gandalf
- iaas (CloudStack and EC2)

We may add others checkers in the future, it's quite simply, just using the hc package.

**Comment by magnotorres** [comment]
\o/
